### ISSUE TITLE
Dismissing popovers when focus leaves

### ISSUE THREAD

**Issue by josepharhar** [openui/open-ui#1060]
I just saw @SaraSoueidan talk at CSS day about how you must make popovers close with javascript when focus leaves them in order to make them accessible, which seems like a reasonable default for popover=auto. Was this behavior considered here before?

@mfreed7 @scottaohara

**Comment by scottaohara** [comment]
yes -  this has been discussed a few times and as Luke notes, the latest time was in https://github.com/openui/open-ui/issues/1047

i don't know exactly what was said, but that's an oversimplification if that was the takeaway message.  

We should probably update the explainer or something to try and mitigate this (or at least have something to point to beyond previous github issues)

**Comment by scottaohara** [comment]
reposting my message from the other thread to mitigate people missing out on rational:

for further context - light dismiss on focus out was explicitly called out as being a potential problem when going over that feature with Aaron Leventhal (google a11y), was mentioned as an accessibility concern when discussing with people from Vispero (makers of JAWS screen reader), and when talking about this with coworkers of mine who use screen readers. The light dismiss via mouse was deemed less problematic (though still could be problematic for people with motor disabilities who may be prone to accidental clicks/taps outside of a popover) - but at least if one can see, then they would be aware of their accidental dismiss.

The problem is that some types of popovers (e.g, a select's listbox popup and other form control 'pickers') do dismisses on focus leaving - but because popover can be applied to anything, all the other stuff it would be unexpected behavior and could have resulted in people constantly dismissing the content they were attempting to interact with, because tab key just let them leave the popover. In other words, we did not add auto dismiss to popovers on focus out specifically for accessibility.

Additionally when mason, aaron and i were going through this, we generally agreed that it would be far easier for developers to add the autodismiss functionality with JS (it is rather trivial considering all the things popover has done for the developer, by default), than it would be for developers to suppress the behavior.

**Comment by scottaohara** [comment]
provided a much longer explanation over here - https://github.com/openui/open-ui/issues/1047#issuecomment-2154662021

**Comment by SaraSoueidan** [comment]
Hi! Sara here 🙏🏻

Just to clarify: I mentioned that the popover should close if you are using it to create more complex patterns like dialogs. The point I was making is that popover enables some behavior but you may need to add more behavior if you use it for modal dialogs or if the open "popover" obscures focusable elements on the page, like the navigation drawer.

My example was not meant to be a generalization. It was a reminder that popover does specific things and depending on your use case you may need to use JS to make your pattern accessible. 🙏🏻

**Comment by scottaohara** [comment]
i would argue that even for non-modal dialogs (because obviously focus leaving modal dialogs should not even be a thing), auto dismiss behavior could be rather frustrating for some users outside of very specific use cases.

appreciate that you meant it as a generalization sara, and this was a misunderstanding of that fact.  so thanks for clearing that up.

**Comment by mfreed7** [comment]
Thanks for the additional comments here. I just want to emphasize the last thing in Scott's post on #1047, which is that the current behavior (**not** dismissing when the focus leaves) was specifically decided **based on accessibility**. That behavior, when applied **generally** is more frustrating than helpful. So we wanted the default to be generally useful, while the special case behavior is still possible. But this is yet another reason why I'm fairly against making all of the light dismiss triggers optional - it's hard to reason about, and I don't want to throw developers to the wolves to figure it out each time. Let's do the right thing generally, and deal with the special cases as special cases.

One additional point: popovers **always** dismiss with one press of the ESC key, no matter where focus resides. So it's always easy for keyboard users to dismiss a popover. For that reason also, it's better not to auto-close when focus *happens* to jump out of the popover. If that was on purpose, the user can hit ESC to close the popover. If that wasn't on purpose (which is more likely) they can easily shift-Tab to get back to the content they were navigating.
