### ISSUE TITLE
Proposal: allow nested <OPTGROUP> in HTML spec

### ISSUE THREAD

**Issue by oriadam** [openui/open-ui#150]
Currently `<OPTGROUP>` is only allowed as a direct child of `<SELECT>`.

The proposal is to also allow `<OPTGROUP>` to be a parent of `<OPTGROUP>` in the HTML standard, thus allowing a semantically accurate and mobile friendly hierarchy of options - nested option groups.

This was recommended on the HTML4 reference:
https://www.w3.org/TR/html401/interact/forms.html#h-17.6

> _Note. Implementors are advised that future versions of HTML may extend the grouping mechanism to allow for nested groups (i.e., OPTGROUP elements may nest). This will allow authors to represent a richer hierarchy of choices._

The common workarounds today are:

1. Adding (em)spaces to the start of the option element. This causes visual bugs on mobile, RTL issues, and it disables the usability of jumping to an option by pressing its first letter.
2. Adding padding. Not supported in mobile. Not supported in some browsers. 

Here is a usage example:
https://bug79431.bmoattachments.org/attachment.cgi?id=37115

p.s. this proposal is far from being original or new. i found a mention of this in 1997, which was rejected because the developers of Netscape were overwhelmed at the time...

related to:
https://html.spec.whatwg.org/multipage/form-elements.html#the-optgroup-element

openUI entry: https://open-ui.org/components/select

**Comment by una** [comment]
I like this idea. `<optgroup>` can be very useful for `<select>`'s. Adding a screenshot from your demo to the discussion:

![Uploading Screen Shot 2020-08-12 at 4.56.46 PM.png…]()

**Comment by scottaohara** [comment]
Talked about this today during the Open UI meeting.

This seems like a request that should be made directly to HTML, especially since this would require parser changes.  So, we would suggest re-opening the issue with HTML if there is a strong desire to see this considered further.

there are some accessibility concerns with nested groups (specifically the increase in the cognitive load to understand where one is within a nested grouping - particularly if it gets 'deep').
