### ISSUE TITLE
Website doesn't display well on mobile esp contribute page

### ISSUE THREAD

**Issue by matt-auckland** [openui/open-ui#170]
First off, love the idea behind this site I think I'll be making use of it from now on.

As for the issue, what I expect is the sidebar to be hidden on mobile, and shown via some kind of navbar menu dropdown/button.

Another thing is on pages with code blocks (for example: https://open-ui.org/contribute ) things overflow massively.

Edit: I'm just assuming it's the codeblocks and not something else, I haven't thoroughly investigated

![Screenshot_20200828-121919.jpg](https://user-images.githubusercontent.com/12672050/91507363-bbfb6580-e928-11ea-8fc1-529cb5757670.jpg)

**Comment by aardrian** [comment]
Came here to report the same thing. On Android with Chrome/Firefox and on iOS, I get as the screen shot above.

Frustrating to use, but more importantly impacts credibility of the project.

**Comment by aardrian** [comment]
I think it is the `, shrink-to-fit=no` in the viewport `<meta>`, but not in a position to test.

**Comment by gregwhitworth** [comment]
Thanks for filing folks - yeah I've likewise noticed this but haven't had a chance to tackle it yet so thanks for raising it.

**Comment by brianespinosa** [comment]
We should probably make sure this gets addressed overall with #29 too if there is a new design coming.

**Comment by gregwhitworth** [comment]
@brianespinosa completely agree that said I was more thinking along the lines of a stop gap type approach, less so a full end to end

that said I appreciate you linking them - @ststimac ^ fyi

**Comment by aardrian** [comment]
I cannot figure out where to edit the inline CSS, and I am not a Gatsby/etc. user, but if you want a stop-gap fix sans a PR, here is a suggestion...

For this wrapper div:
```
<div style="display:flex;padding:0 1rem;margin:0 auto;max-width:1200px;">
```

Add `flex-wrap:wrap`:
```
<div style="display:flex;padding:0 1rem;margin:0 auto;max-width:1200px;flex-wrap: wrap;">
```

For its child nav:
```
<nav style="margin-right:2em;">
```

Add `flex: 1 1 15em` (or whatever you want its default width to be, which you may want in pixels given you are using pixels on the `max-width`):
```
<nav style="margin-right:2em;flex: 1 1 15em;">
```

For the wrapper's child div / sibling to the nav:
```
<div style="flex:1;">
```

Give it the ability to shrink and grow and give it a maximum width:
```
<div style="flex: 1 1 auto;max-width: calc(100vw - 2em);">
```

And the thing that keeps it from wanting to shrink appears to be the code blocks:
```
<pre class="prism-code language-" style="color:#9CDCFE;background-color:#1E1E1E;padding:0.25rem 0.5rem">
```

So make them overflow and set a maximum width:
```
pre.prism-code {
    overflow: auto;
    max-width: calc(100% - 1em);
}
```

And because those code blocks need to support a keyboard-only user to scroll, they will need a `tabindex`, which necessitates and region and accName so a screen reader user understands what this tab-stop is:
```
<pre class="prism-code language-" style="[...]" tabindex="0" role="region" aria-label="Code block">
```

This is tough because the CSS is inline, which means I cannot quickly debug on mobile. So yeah, it's a hack and you should never attribute it to me, but it can at least make it usable on mobile right now.

**Comment by jasikpark** [comment]
Not sure if this is the right issue to mention this, but I have to scroll all the way to the bottom of the page to access the lower half of the menu, instead of the page and menu being individually scrollable.

**Comment by aardrian** [comment]
I know the first effort did not, but according to the oldest WayBack I could find, it looks like sometime between [3 December 2021](https://web.archive.org/web/20201203202046/https://open-ui.org/) and [11 December 2021](https://web.archive.org/web/20201211155159/https://open-ui.org/), when the hamburger navigation button was added.

So PR #234 appears to have sorted it and this just was not closed as part of it.

**Comment by andrico1234** [comment]
Closing this,  as @aardrian has pointed out, the issues seems to have been solved!
