### ISSUE TITLE
[Popup] Do we need the "open" content attribute?

### ISSUE THREAD

**Issue by melanierichards** [openui/open-ui#311]
On [MSEdgeExplainers #467](https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/467), @mfreed7 asked:

> The "open" attribute was recently re-added to the proposal. I'm wondering what the driving use case is for that attribute. I can see from the [explainer](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/Popup/explainer.md#option-b-the-open-attribute) that opening a popup on "load" is listed there. Is that it?
> 
> An easy alternative to the "open" attribute, for that use case, is:
> 
> ```javascript
> window.onload = () => {myPopup.show();};
> ```
> 
> I ask because there are complexities:
> 
> 1. What if multiple non-nested (or nested!) popups have the "open" attribute?
>     1. In this case, only one of them should show, so at least an order needs to be determined. Perhaps the behavior should be as-if the `.show()` method were called in tree order on all of them?
>     2. For the non-shown popups above, should a "hide" event be fired on them?
>     3. For the non-shown popups above, should their "open" attribute be removed? If not, then they'll still be wearing the "open" attribute while not actually being displayed. (The UA stylesheet cannot therefore simply use `popup:not([open]) {display: none !important;}` to hide the popup.)
> 3. When an open `<popup>` is removed from the tree, the `<popup>` plus all of its non-ancestor `<popup>`s need to be hidden.
>     1. Without the "open" attribute, this is relatively easy, because hiding popups doesn't affect the DOM tree, just the layout tree.
>     2. However, when the "open" attribute needs to be removed from each of those hidden popups, this gets more tricky. Node removal (in Chromium, and I think by spec, modulo mutation events) is forbidden from modifying the DOM tree. Therefore, the removal of the "open" attribute would need to be done at a later time (micro-task timing?), which would be observable.
> 2. What if a disconnected `<popup open>` node is created?
>     1. Is it confusing that `popup.getAttribute('open')` is non-null for this disconnected, non-displayed `<popup>`?
>     2. What if this node is appended to the document? Should it act as if `.show()` were called upon insertion? If so, some of the same concerns as <span>#</span>2 above apply here - other `<popup>`s will need to be hidden as this node is inserted into the document.
> 
> All of the above can be overcome, but I'm curious if the added complexity is worth the benefit provided by the "open" attribute. I do know that parallelism to `<dialog>` has been brought up here. But in this case specifically, `<dialog>` is quite different - many `<dialog>`s can be open at a time, and they don't close each other. So none of the complexity above applies to `<dialog>`.

**Comment by melanierichards** [comment]
We heard this feedback from a few different sources:

* [HTML editor](https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/455) feedback, from the perspective of alignment with `<dialog>`. FWIW Domenic also offered reconsidering that attribute for `<dialog>`.
* [TAG review](https://github.com/w3ctag/design-reviews/issues/599#issuecomment-772497485), "so that authors can a) open the popup declaratively and b) target opened popups with an attribute selector."
* [Authors](https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/437), who were concerned that `popup` would not have a mechanism for declarative invocation. Part of this is solved by the `popup` attribute, but there was a specific request or two to have some method for invocation effectively "on page load".

I think those requests capture the extent of my awareness of use cases here:

* Showing a `popup` before interaction w/ other elements
* Styleability

Before digging into the various technical complexities Mason listed out + finding a resolution for these, I think it would be good for the group to discuss whether there are other use cases for the `open` attribute on `popup`, as well as how critical this attribute is for authors given the ability to invoke via 1) the `popup` attribute and 2) the `show()` event.

**Comment by mfreed7** [comment]
Thanks for these pointers! A few replies below...

> * [HTML editor](https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/455) feedback, from the perspective of alignment with `<dialog>`. FWIW Domenic also offered reconsidering that attribute for `<dialog>`.

Here, I note that the feedback is really to make `<popup>` and `<dialog>` as close together as possible, and I agree with that. @domenic explicitly states that there are already problems with the `open` attribute on `<dialog>`, and says this:

> Second-best would be making the affirmative decision in the HTML and implementer community that `open=""` on `<dialog>` was just a mistake, and should never be used; we would then deprecate it (i.e. tell web developers not to use it, even if implementations have to support it), and provide another styling hook for open `<dialog>`s and `<popup>`s.

I like this option the best, by far.


> * [TAG review](https://github.com/w3ctag/design-reviews/issues/599#issuecomment-772497485), "so that authors can a) open the popup declaratively and b) target opened popups with an attribute selector."

Here, I think a) just means what is said below: the ability to open the popup "on page load". If the intention is to allow `setAttribute('open','')` to open the popup, then I'm not sure what the advantage is over `popup.show()`. As for b), I am curious about the use case for that. When the popup is in the closed state, it is by definition invisible. So `popup[open] {my styles}` should be functionally equivalent to `popup{my styles}` because whenever `my styles` apply, the popup must be open. Help me understand that point, I'm sure I'm missing something. In addition to this, as I mentioned in the OP, since multiple popups can have an `open` attribute, but per the rules, only one can be shown at a time, selectors of the sort `popup[open]` will improperly target invisible popups.

> * [Authors](https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/437), who were concerned that `popup` would not have a mechanism for declarative invocation. Part of this is solved by the `popup` attribute, but there was a specific request or two to have some method for invocation effectively "on page load".

Discussed a bit above, and in my OP, but can you help me understand how/why this is easier/better than just `window.onload = () => {myPopup.show();};`. Using the `open` attribute is subject to a lot of ambiguity and confusion (e.g. closed popups that still have the `open` attribute). Requiring either JS or the `popup` attribute seems pretty clean.

> Before digging into the various technical complexities Mason listed out + finding a resolution for these, I think it would be good for the group to discuss whether there are other use cases for the `open` attribute on `popup`, as well as how critical this attribute is for authors given the ability to invoke via 1) the `popup` attribute and 2) the `show()` event.

Agreed +100 here. I really don't want to cut off use cases, if there are good ones. I just want to avoid complexity where it isn't needed.

**Comment by flackr** [comment]
To add on to the [example](https://jsbin.com/leyosok/edit?html,css,js,output) I presented during the discussion, I think we can avoid a lot of the complexities here by following the pattern used by checked on input elements.

In particular,
* The checked html attribute sets the initial state but is not live. The last checked radio button is the one which is ultimately checked (i.e. as if it is done in order).
* The checked IDL attribute is live.

**Comment by mfreed7** [comment]
Thanks to everyone for the great discussion on this issue. I want to add some comments about what I heard:

- First, the title of this issue really should be "Do we need the 'open' **content** attribute?". I see the value of the 'open' IDL property (i.e. `const popupIsOpen = popup.open`) and there isn't any technical complexity around implementing that. This issue is about the **content** attribute specifically: `<popup open>`.
- Another thing I heard which is a good point is that we should consider Find in Page: should the content of a hidden `<popup>` be findable? And when found, should the popup be auto-opened? I've added that as a [comment in another issue](https://github.com/WICG/open-ui/issues/315#issuecomment-816154468), for further discussion.
- There was some discussion of another possible attribute (e.g. 'dismissable') that would "turn off" the light dismiss behavior. This seemed like a better use case for the `<dialog>` element, but the point was also made that `<dialog>` is a 1-engine element at the moment.
- As mentioned in the comment just now, @flackr proposed a new direction, for a content attribute that **only** controls the visibility on page load, but doesn't reflect current state, and can't be used to "control" the visibility of the `<popup>`. I really like this proposal, as it alleviates all of the complexities I brought up in the OP. We'd need to choose a good name - how about `initiallyopen`? And it would have to be better-defined **when** exactly it should be opened. On `DOMContentLoaded`? Before that?

The general tone seemed (to me at least!) to be that it was "ok" not to have a full-featured `open` content attribute, particularly if the `initiallyopen` suggestion was available. That's at least what I heard, but I am obviously biased. Please chime in if I missed an important use case for the `open` content attribute.

**Comment by domenic** [comment]
I like the `initiallyopen=""` idea, and it seems like it's headed in a good direction. In particular I want to emphasize @mfreed7's point of using a good name (*not* `open=""`) for the content attribute.

In particular, although the general idea of separating the content attribute and IDL attribute like checkbox does, the specific choices checkbox made are _not_ good and cause a lot of developer confusion. For checkbox, the `defaultChecked` IDL attribute reflects the `checked=""` content attribute, and the `checked` IDL attribute represents read-write live state (which usually does not, but sometimes does, correlate with the `checked=""` content attribute, depending on form resets and various other fun).

A clean model would be something like an `initiallyOpen` IDL attribute which reflects the `initiallyopen=""` content attribute, and a separate `open` IDL attribute which has *no correlation with* `initiallyOpen`/`initiallyopen=""`. (Except, of course, that if `initiallyopen=""` happens to actually cause the popup to open, then `open` will be true.)

(As for `defaultopen=""` vs. `initiallyopen=""` vs. other ideas, I don't have strong feelings. `defaultChecked` is a small precedent, but since it's part of a weird model it's not a great precedent.)

**Comment by BrentARitchie** [comment]
I just wanted to chime in and say that for the styling argument, we could simply expose the state through a pseudo class as is the norm. Using a live attribute seems wrong as state has been communicated through pseudo classes for some time now.

It would also allow for consistency with other elements such as <detail>.

**Comment by gregwhitworth** [comment]
With regards to styling - I completely agree with @BrentARitchie by defining a new pseudo class that applies to certain elements (eg: `dialog:open`, `popup:open`). There are enough use-cases where popups are visible on load and so I think that initialOpen content attribute is a solid approach to deal with this scenario. 

@domenic thanks for linking in the TAG review as that does highlight a headache we should avoid.

**Comment by mfreed7** [comment]
> With regards to styling - I completely agree with @BrentARitchie by defining a new pseudo class that applies to certain elements (eg: `dialog:open`, `popup:open`). There are enough use-cases where popups are visible on load and so I think that initialOpen content attribute is a solid approach to deal with this scenario.

Thanks for all of the comments here. I just wanted to highlight one of them - above. @BrentARitchie and @gregwhitworth can you clarify (e.g. with an example) what could be done with a `popup:open` pseudo-state that cannot be done with a simple `popup` selector? See my [point above](https://github.com/WICG/open-ui/issues/311#issuecomment-814413263), but TL/DR since the popup is only visible when it is open, I don't understand why you'd need to select only *open* popups. I'm honestly trying to understand the use case, because I feel like I'm missing something. Perhaps it's just ease of use with `querySelector()` or something?

**Comment by BrentARitchie** [comment]
In response to @mfreed7, I created a basic demo for a use case using dialog. It has many of the same concerns we are talking about with the Popup element. The the demo is at https://codepen.io/saveoney/full/bGgvQNZ.

Essentially what I am doing is making the Dialog partially visible (bottom left) to denote that something needs attention. When the dialog is clicked the rest of the content is then shown as normal. This is only a single use case. For the popup specifically, I could envision part of it being shown as a hint and then expanded/opened as needed.

This technique uses what is already available to cut down on DOM nodes and JavaScript. To note, this demo does not consider accessibility, and is slightly broken in that respect, but fixable with a little more code. I also don't claim that this is an example of great technique, just something conceivable in the real-world.

**Comment by gregwhitworth** [comment]
This was discussed in today's telecon - here are the resolutions:

> RESOLUTION: <popup> will not contain an "open" content attribute. It will still have an "open" IDL attribute that reflects its open/hidden status. It will have an "initiallyopen" content attribute, which is reflected in an "initiallyOpen" IDL attribute. If "initiallyOpen" is present on page load, the popup will be shown.

and here is the resolution regarding styling:

> RESOLUTION: the <popup> will have a pseudo state (name TBD) which reflects the open state of the popup.

@melanierichards to open a new issue regarding the pseudo selectors.

**Comment by davatron5000** [comment]
As the lone dissenter from last week's meeting, I wanted to log an opinion in regards to the styling options question.

As an author, I value consistency. In my day-to-day building systems, I encounter a lot one-off inconsistencies in the platform. Especially when crossing between HTML, CSS, and JS. Not to create too big of a strawman, but in order to lazyload an asset, you do the following: `<img loading=“lazy”>`, `<script async|defer>`, `<link rel=“preload” as=“style”>`). Three distinct APIs to do more or less the same thing hints at a lot of one-off bespoke problem solving.

So, as an author, the currently existing way of styling off of `[open]` offers me a lot of consistency versus a new `:open` pseudo-class that doesn't exist yet.

An `[attribute]` in hand is worth two `:pseudo-classes` in the bush, as it were.

This element in particular introduces a handful of :new: attributes and pseudo-classes. 

- `initiallyOpen`
- `anchor`
- `delegatefocus`
- `popup`
- `:open`

I'm not saying each of these low-level APIs don't have value or solve problems, I'm only pointing out we're inventing quite a few new concepts without a broader plan or strategy.

After reading a handful of Github issues, specifically https://github.com/whatwg/html/issues/5802, I understand the specific problems with `[open]`. The `:open` pseudo-state does seem like a better solution so long as other elements (`<dialog>/<details>`) also get a consistent styling API. Because as it stands, this would introduce an inconsistency where `foo.open == true` in JavaScript but that wouldn't be reflected in HTML.

**Comment by gregwhitworth** [comment]
> The :open pseudo-state does seem like a better solution so long as other elements (<dialog>/<details>) also get a consistent styling API. Because as it stands, this would introduce an inconsistency where foo.open == true in JavaScript but that wouldn't be reflected in HTML.

Agreed. Given details & summary are widely supported the attribute probably can't be removed and while `<dialog>` isn't supported everywhere I'm sure there will still be some compat pain. However, I do agree that the pseudo-class should be supported on any element that has an `open` state. So ultimately, when this pseudo class goes to the CSS WG we would want to ensure that we list out the elements concretely in the spec (and of course update the pseudo class with each new component/control).

> I'm not saying each of these low-level APIs don't have value or solve problems, I'm only pointing out we're inventing quite a few new concepts without a broader plan or strategy.

Can you scope in on what you mean by "broader plan or strategy" as it pertains to this issue?

**Comment by melanierichards** [comment]
Hey folks, for the purposes of agenda-building, anything we want to revisit or discuss on this issue at this week's telecon?

**Comment by zcorpan** [comment]
From https://github.com/openui/open-ui/issues/416#issuecomment-973292160

I would prefer shorter and easy-to-spell names for HTML, generally. (c.f. [misspellings of `<script language>`](https://web.archive.org/web/20060203025300/http://code.google.com/webstats/2005-12/scripting.html).)

`initiallyopen` might be a bit long and subject to misspellings, alternatives could be `initopen` or `autoopen` (to mirror `autofocus`).

**Comment by mfreed7** [comment]
Given the resolutions above, I'm going to close this issue. I've [opened a fresh issue](https://github.com/openui/open-ui/issues/470
) to discuss the third part of this issue, the CSS pseudo class for top layer status.

Thanks!

**Comment by mfreed7** [comment]
Well, I don't have issue closing permissions, so I'll just say that I think this issue can be closed, and hope someone does that. 😀
