### ISSUE TITLE
[Popup] [Dialog] Evaluate which popup-related primitives should be extended to other elements

### ISSUE THREAD

**Issue by melanierichards** [openui/open-ui#323]
This discussion should come later on in popup incubation once popup-related primitives are more mature. We introduce a number of primitives that are necessary for `popup`, and we imagine that many of these would be useful in other contexts (e.g. `delegatesfocus`). We should go through each one and consider how these will be applicable to other elements (dialog, "all top-layer elements", or otherwise).

This also came up on https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/455

**Comment by mfreed7** [comment]
Since this issue was opened, `<popup>` as an element was abandoned, and the set of features has matured significantly. I think the only potentially "more general" feature might be `delegatesfocus`, which [likely will become](https://github.com/openui/open-ui/issues/368#issuecomment-1126481557) a general-purpose feature that is completely separate from popup.

I'm going to close this issue.
