### ISSUE TITLE
[popup] Consider to add popupshowing, popupshown, popuphiding and popuphidden events

### ISSUE THREAD

**Issue by smaug----** [openui/open-ui#342]
The proposed popup elements shares lots of common with XUL popup element (which is used in Firefox UI to create all sorts of  popups). Very common way to use a popup is to fill its content just when it is about to be shown. That is why there is popupshowing DOM event. Other commonly used events are popupshown, popuphiding and popuphidden.

(There is also [popuppositioned](https://searchfox.org/mozilla-central/source/dom/webidl/PopupPositionedEvent.webidl) event.)

**Comment by mfreed7** [comment]
The pop-up API has evolved significantly since this question was raised. In particular, the `show` and `hide` events have been more fleshed out as synchronous events, which allows a pop-up to have its content updated prior to being shown, and/or retrieve data from the pop-up prior to being hidden. Also, the [animation behavior has been resolved](https://github.com/openui/open-ui/issues/335), allowing easy animations of pop-up show and hide. I'm curious what use cases are still left out of the [existing proposal](https://open-ui.org/components/popup.research.explainer#animation-of-pop-ups) that might require more events than just `show` and `hide`. Thoughts?

**Comment by mfreed7** [comment]
I'm inclined to close this issue, given that I believe (subject to being told I'm wrong!) that the current proposal functionality covers all relevant use cases.

**Comment by mfreed7** [comment]
Re-opening to let @smaug---- comment with some use cases.

**Comment by mfreed7** [comment]
> * Popupshown (fired after the popup is already visible) is used for example to implement autohide after some time.

This use case could just as easily be done in the "beforetoggle" event, right? I.e. this is some variant of `setTimeout(doAutohide,500)`, which works before or after.

> And possibly more important use case is to focus certain element in the popup.

For focusing elements, we have the `autofocus` attribute, which declaratively does this in exactly the right way (for a11y) at exactly the right time. I'd be hesitant to encourage developers to manually call `.focus()` in event handlers, since it would be easy to do it wrong and hurt user experience. @scottaohara 

> * Popuphiding isn’t used too often and popuphidden could have been used in many places.

I guess this is an argument that either can work?

> * Popuppositioned fires if the position or size changes

This last bit is related more to anchor positioning, I think. Doesn't the ResizeObserver or IntersectionObserver take care of this use case though?

> I think some variant of popupshown is pretty critical, especially because of the focus handling.

We have discussed this question several times, not just in this issue, but also in https://github.com/openui/open-ui/issues/607#issuecomment-1278045033, and more [when I proposed it as a more general WHATWG issue](https://github.com/whatwg/html/issues/8386). There haven't been compelling developer-driven arguments that there's a use case for the "after" events. Or at least none have emerged thus far in all of the testing and demos for Popover.

Let's discuss further - I've added this to the agenda for a future meeting (will be next year).

**Comment by dbaron** [comment]
@smaug---- We were curious if you'd be able to make a future OpenUI meeting to present/discuss this.  They're currently Thursdays at 14:00 New York / 11:00 Los Angeles, which (except during the weird summer time weeks) is I think 21:00 Helsinki.

**Comment by mfreed7** [comment]
> Sure, 21:00 should be fine.

Great! @gregwhitworth  can we please make sure this issue gets back on the agenda for this week Thursday so @smaug---- can participate?

**Comment by mfreed7** [comment]
Side note: we just decided in the HTML spec triage meeting to rename `aftertoggle` to `toggle` but otherwise retain the behavior described in the resolution above.

**Comment by annevk** [comment]
Side note: such decisions are non-binding: https://whatwg.org/working-mode#meetings.
