### ISSUE TITLE
[Popup] Suppressing rendering of popup when its activating element receives focus?

### ISSUE THREAD

**Issue by melanierichards** [openui/open-ui#359]
The `popup` attribute enables rendering of a popup when the user interacts with a related element (where the `popup` attribute is specified).

Invoking/clicking/etc a `button` or `input type="button"` shows the popup. Setting focus to an input of type `text`, `email`, `url`, or `phone` will show the popup. For example, setting focus in this combobox field will render the listbox popup:

```html
<input role="combobox" type="text" popup="listbox">
<popup id="listbox">...</popup>
```

Should we have a way to suppress this popup rendering upon focus, so that the author can enable the popup to be shown upon text entry (or some other logic) instead?

**Comment by leolopes** [comment]
Hi @melanierichards , the idea is that by default `focus` __will__ render the popup, independently from any explicitly determined logic, right?

If so, I think it's interesting to have a standard way to suppress the rendering, but it would feel a bit lacking if it just does that and not prescribe a different standard behavior.

I say that because if people are to write the whole new behavior on JS, maybe JS could also handle the suppression...

Perhaps instead of a `suppress-popup` attribute, there could be a `popup-behavior` attribute, that allows the developer to choose from a set of standard behaviors. Setting it to `none` or `custom` would then require the develeper to create the custom behavior.

**Comment by melanierichards** [comment]
Thanks Leo, this is correct!

> the idea is that by default focus will render the popup, independently from any explicitly determined logic, right?

Actually, awhile back we were thinking about an attribute similar to `popup-behavior` that could take key-separated values denoting what interactions would trigger rendering of the popup (e.g. `invoke`, `focus`, etc). IIRC we had dropped that because it seemed to add a lot of complexity to attributes that might be better handled in script (also a lot of popup-specific attributes).

Options for consideration here:

a) Explore the invocation behavior attribute described above
b) Have authors call `preventDefault()` on focus of these inputs to suppress rendering of the popup; would need to investigation implications of doing so.
c) Decide not to support this default behavior (render popup on focus), and the attribute when used on one of these particular input types is a semantic relationship only.

**Comment by melanierichards** [comment]
Also want to invite web developers to comment on the following:

* Is the default behavior described here useful to you? It is important to have the platform handle this for you, or would you prefer to script your own logic?
* What logic do you use when displaying a popup that is semantically tied to an input? Comboboxes are a good example. Do you display the popup upon focus, text entry, entry of specific characters, a timeout, etc.

**Comment by leolopes** [comment]
Hi @melanierichards , let me give my two cents:
> a) Explore the invocation behavior attribute described above
It seems my proposed `popup-behavior` is related to _what should happen_ when invoking the popup, while the one you mentioned is related to _what should invoke_ the popup, right? Maybe yours is better, because it takes for granted that popups "should behave like popups", the only difference is _how_ to trigger the behavior.

> b) Have authors call preventDefault() on focus of these inputs to suppress rendering of the popup; would need to investigation implications of doing so.
This is interesting because it would be very close to what we do with links, so it's something devs are kind of used to.

> c) Decide not to support this default behavior (render popup on focus), and the attribute when used on one of these particular input types is a semantic relationship only.
I think this is the least desired proposal, because it keeps the developers in basically the position they are now, that is, having to think of all the implications of a popup and then having to develop the behaviors. If accessibility would be built in, it would be an improvement, but still, it does not help the majority of use cases.

===

> Is the default behavior described here useful to you? It is important to have the platform handle this for you, or would you prefer to script your own logic?
I think so much of the poorly designed UI we see in the wild is due to every developer having to create everything from scratch, or compromising to partially adequate frameworks (or worse, mixing several code bases to create a Frankenstein's monster). So, if we can avoid this by providing basic behavior that serves most use cases, that would be optimal.

> What logic do you use when displaying a popup that is semantically tied to an input? Comboboxes are a good example. Do you display the popup upon focus, text entry, entry of specific characters, a timeout, etc.
It depends on the kind of data and choice. `select` opens on click because the choices are all there and just need to be selected. `autocomplete` text fields, however, only open upon character entry, so that the search is more focused to the probable options.

**Comment by melanierichards** [comment]
Thanks a bunch Leo for the additional feedback! I see you mentioned a couple use cases in your response. Do you have any use cases where a popup would be shown when focus is sent to one of the text-entry input types, or is it only character entry? `<select>` behavior makes sense, invoking its button part should show the popup.

> while the one you mentioned is related to what should invoke the popup, right? 

Right, that's what I'm thinking.

> I think this (c) is the least desired proposal

That's my instinct as well, thanks for weighing in!

**Comment by una** [comment]
RESOLVED: preserve the behavior where when a user places focus into a text-entry-oriented control that has the popup attribute, the related popup will be shown. The platform will not provide a primitive to suppress this default behavior.

**Comment by leolopes** [comment]
Hi folks, glad this is resolved. I'll take a look at the minutes, I'm curious about the reasoning.
Anyway, answering @melanierichards 

> Do you have any use cases where a popup would be shown when focus is sent to one of the text-entry input types, or is it only character entry?

Actually I thought a bit and couldn't come up with any reasonable use case.

**Comment by SebastianZ** [comment]
> > Do you have any use cases where a popup would be shown when focus is sent to one of the text-entry input types, or is it only character entry?
> 
> Actually I thought a bit and couldn't come up with any reasonable use case.

I do have some:

1. Date and time input fields. Those sometimes show a popup on focus that allows you to pick a date or time in addition to the normal input. A concrete example would be the one implemented in Firefox for `<input type="date">`.
2. Comboboxes with a few predefined entries. If the number of options to choose from is limited, it makes sense to show them right when focusing the input field. An example for that is the `<datalist>` implementation in Chrome.

Sebastian

**Comment by melanierichards** [comment]
Thanks for weighing in with use cases, @SebastianZ!
