### ISSUE TITLE
[select] To what extent should customizable select implement the old <select>'s interface?

### ISSUE THREAD

**Issue by dandclark** [openui/open-ui#380]
This is a broad question that we've danced around in the past, but I think we need to settle on a direction for the new customizable `<select>`'s interface.

I see two competing directions:
1) Customizable select (I'll use the working name `<selectmenu>`) should have the same interface as the web platform's [old `<select>`](https://html.spec.whatwg.org/multipage/form-elements.html#the-select-element) to the extent that this is possible.
2) We should design customizable `<selectmenu>`'s interface from scratch, ignoring any precedent set by old `<select>`.

Thus far the content at https://open-ui.org/components/select has mostly followed approach (1), where the set of properties is basically a copy/paste of old `<select>`. Advantages of this approach are that developers already familiar with `<select>` would be able to learn the new `<selectmenu>` more easily, and pages written with the old `<select>` could more easily be converted to use the new `<selectmenu>`. Unnecessary differences between the two element types could be a source for confusion.

On the other hand, the new element is a good opportunity to improve or modernize the old `<select>`'s interface. For example, @domenic pointed out [here](https://chromium-review.googlesource.com/c/chromium/src/+/3055671/comments/a6c7b97a_f2fd5a01) that `HTMLOptionsCollection` is a legacy "fake array" type, and introducing new instances should be avoided.

Should we consider drafting an IDL for `<selectmenu>` from scratch? Or use basically the same IDL, with some edits to remove or replace legacy stuff like `HTMLOptionsCollection`? Or something in between?

I have a slight preference to start from scratch and at least see what we can come up with, but I'd like to hear thoughts from others.

**Comment by domenic** [comment]
+1 to starting from scratch, carrying over only the good parts. To me that's one of the biggest benefits of using a new element type.

I'd suggest

- `disabled`, `form`, `name`, `labels`, and validity checking interfaces as common to all form elements

- `required`, `multiple`, and `autocomplete` if `<selectmenu>` supports them; I'm not sure what the latest thinking is especially on `multiple`.

- `type` I'm not so sure about; all form controls have it, so probably `<selectmenu>` should? But `<select>`'s precedent of `"select-one"` + `"select-multiple"` is very strange, and I've never heard of anyone actually using `type`, so I dunno.

- I honestly don't remember what `size` does (and it's not so obvious from the spec) so you'd need to figure out something there.

- Probably do not have any of the child manipulation stuff (`options`, `length`, named and indexed getters and setters, `add()`, `remove()`). The DOM itself is good for that. You could contemplate an `ObservableArray<HTMLOptionElement>` but I wouldn't.

- `selectedOptions` (or `selectedOption` if you're not supporting `multiple`) seems good

- `selectedIndex` seems not so useful comparatively and I'd drop it (and it seems actively bad if you're supporting `multiple`)

- `value` seems likely too useful to omit, although again it's problematic if you're supporting `multiple`.

**Comment by melanierichards** [comment]
Agree with a principled approach of:

1. Start with `select`
2. Inventory interfaces, evaluate what to keep ("the good parts")
3. Evaluate what is missing/odd behavior and seize the opportunity to do something better

We should be mindful that updating `<selectmenu>`'s interface will impact:

* User agent implementation details
* **Developer experience:** we may want a principle that roughly says, "if we create inconsistencies in the DX from `<select>`, those changes should be meaningful in that they unlock new, desirable functionality or address old pain-points or confusion". Even a good change is something that developers will have to keep track of, particularly with progressive enhancement…I could see this principle being an artificially high bar, though, so it's certainly up for discussion.
* **Potentially, the user experience:** we should be most careful with this category and should validate with user research depending on the change. Thinking here of things like typeahead behaviors that sort of blur the lines between a combobox and a selectmenu. Perhaps I'm thinking about this at too broad of a scope, though e.g. whether to support `multiple` would be relevant here.

**Comment by stubbornella** [comment]
Capturing the principles we discussed today and were added to the issue. Please consider this a bad first draft to be heavily edited. :) This will eventually go in "principles" on the open-ui site.

Consider the following when deciding whether or not to carry forward an existing control's interface:

* Does the old interface makes sense? (we should define "makes sense")
* If changing the interface creates inconsistencies in the DX from <select>, those changes should be meaningful in that they unlock new, desirable functionality or address old pain-points or confusion
* Would changing the interface improve the UX, based on UX Research?
* Is the interface is common to all form elements like validity checking?
* How frequently the interface is used?
* Does the interface do something sensible, predictable, and reasonable in the context of the new control?
* Are there generic APIs that deliver the same functionality as the control specific interface? Ex. Rely on DOM methods when possible for child manipulation
* Align with developer sentiment.
* Is this interface used in popular implementations of the control in the ecosystem/popular frameworks? Do those implementations expose a similar interface?

## Process when choosing to diverge

* Add a description to the research in Open-UI outlining why the decision was made to change the interface/control

**Comment by stubbornella** [comment]
@domenic do you mind checking if I properly abstracted the principles from your example.

**Comment by bkardell** [comment]
I am really supportive of the idea of trying to outline principles like this, so I'm happy to see this started.  I'd like to try to rephase/clarify my comments from the meeting which I think helped us wind up here but I think were slighly different (probably poor articulation on my part), because I still think they are important, but am not sure if we discussed/agree on it...

It seems to me we have broad agreement (including from me) that we should approach this as something like "inspired by prior art in the platform where pracitical, but free from unnecessary or unfortunate baggage".  However, that's a somewhat fuzzy as a statement, and easy enough to agree with.  At the end of the day, we will be proposing a very specific API - some developers will learn about it when it is still words or filed as an intent somewhere.  We know they will have questions and reactions. I have seen a lot of things go badly on either end of that and intended to suggest that once we had concrete ideas ("here is the IDL") on this specific API, we should not consider it "baked". 
 That we should specifically try to go out and explain why we made those those particular choices in a way that is simple and accessible... "Here is a specific proposal, and we know there are likely to be questions - some things will feel familiar, some are new -- here are some answers to questions we expect you'll have, and we'd like to field more questions or hear feedback"
.

**Comment by domenic** [comment]
> @domenic do you mind checking if I properly abstracted the principles from your example.

Which example are you referring to?

**Comment by gregwhitworth** [comment]
Since I missed this session, I'm curious what the concrete scenarios for `<selectmenu>` are that we're referring to? As the principles seem to be what we're already doing for `<selectmenu>` or am I missing something?

**Comment by korenevskiy** [comment]
Hello. what do you think? Do you think this could be an analogue of the new "Fully stylable and accessible selects https://codepen.io/captainbrosset/pen/jOGVebx " function, it seems to me that it is very similar in many ways https://github.com/openui/open-ui/issues/283 , but at the same time it has wider possibilities. We can use Labels as options for the text field. This way we will get an expandable SELECT, but we can also design many other new controls.

**Comment by josepharhar** [comment]
Thanks for the feedback domenic. I believe that the current selectmenu implementation agrees with all of your points, especially since we aren't handling multi-select with the current selectmenu element

> disabled, form, name, labels, and validity checking interfaces as common to all form elements

disabled, form, name, labels, and checkValidity have been implemented.

> required, multiple, and autocomplete if <selectmenu> supports them; I'm not sure what the latest thinking is especially on multiple

required is implemented.

We aren't going to do multiple for now. We might use a different tag name instead of multiple when we do multi-select.

Autocomplete will be supported when we implement autofill support: https://bugs.chromium.org/p/chromium/issues/detail?id=1427728

> type I'm not so sure about; all form controls have it, so probably selectmenu should? But select's precedent of "select-one" + "select-multiple" is very strange, and I've never heard of anyone actually using type, so I dunno.

Type is supported and returns "selectmenu". I'm not worried about extending it for multiple if we reuse the same element for multiselect since I don't think its likely, but if we do, then I guess we could extend it like select does "selectmenu-multiple"

> I honestly don't remember what size does (and it's not so obvious from the spec) so you'd need to figure out something there.

The size attribute is for multi select right? The current selectmenu element doesn't support multi select and doesn't implement the size attribute, and I think we should keep it unsupported.

> Probably do not have any of the child manipulation stuff (options, length, named and indexed getters and setters, add(), remove()). The DOM itself is good for that. You could contemplate an `ObservableArray<HTMLOptionElement>` but I wouldn't.

Selectmenu does not implement any of these

> selectedOptions (or selectedOption if you're not supporting multiple) seems good

selectmenu.selectedOption is supported and implemented

> selectedIndex seems not so useful comparatively and I'd drop it (and it seems actively bad if you're supporting multiple)

selectedIndex is not supported

> value seems likely too useful to omit, although again it's problematic if you're supporting multiple

value is supported

**Comment by josepharhar** [comment]
If anyone has any further suggestions for things to implement or not from the existing select element, please open new issues. I don't think that there is any further actionable feedback in this issue
