### ISSUE TITLE
[Popup] New IDL for Pop-Up content attributes, which allow Element references

### ISSUE THREAD

**Issue by e111077** [openui/open-ui#382]
_NOTE: this issue was originally written when the popup proposal still included a `<popup>` element. It has since been edited, but there may be some inconsistencies_

## The problem

The current Popup explainer seems to be missing some imperative API docs for certain features such as the `anchor` and `togglepopup` attributes.

## The background

The reason why an imperative API would help is that ID's for associating elements leads into multiple problems:

* IDs do not penetrate shadow roots
* componentizing a popup button or a popup itself will require the component author to generate IDs on the fly

For example, shadow roots:

```html
<button togglepopup="my-popup" id="my-anchor">toggle the popup</button>
<my-popup>
  <template shadowroot="open">
    <div popup id="my-popup" anchor="my-anchor">
      <slot></slot>
    </div>
  </template>
</my-popup>
```

The above example has an anchor with id `my-anchor` and a popup inside of a shadow root (using the declarative shadow dom api). Adding `[anchor=my-anchor]` to `div[popup]` will not work as ID's cannot penetrate shadow roots, and `button[togglepopup=my-popup]` will also not work because it won't be able to penetrate the shadow root to find the popup.

Example ID generation:

```jsx
// PopupButton.jsx
import React, { useState } from "react";
let idCounter = 0;

export default () => {
  const [currentId] = useState(idCounter++);

  return (
    <>
      <button togglepopup={`popup-button-${currentId}`}>
        Click me to open popup
      </button>
      <div popup id={`popup-button-${currentId}`}>...</div popup>
    </>
  );
};
```

The above example in react would require generating an ID to link a popup button with a popup (same situation would exist with anchor) when an imperative solution (like a ref or a function callback) would suffice.

## Proposed solution

Defining an imperative way to associate element's popup or anchor.

I see two options here:

1. Allowing `anchor` and `togglepopup` **properties** on `HTMLElement` to support element references as well as string
2. Creating a setter method for `setAnchor(el: HTMLElement)` and `togglePopUp(el: HTMLPopupElement)`

Both of these options solve the problems above, but have different tradeoffs.

### Allowing property to support Element references

**The positives** about this approach is that it will allow for better declarative programming on modern templating frameworks such as React and lit-html. For example:

React:

```jsx
// PopupButton.jsx
import React, { useRef } from "react";

export default ({anochorIdOrRef} /* type is string|HTMLElement|undefined */) => {
  const [popupRef] = useRef(undefined);

  return (
    <>
      <button togglepopup={popupRef.current}>
        Click me to open popup
      </button>
      <div popup ref={popupRef} anchor={anochorIdOrRef}>...</div>
    </>
  );
};

// usage: <PopupButton anchorIdOrRef="my-anchor" />
```

Lit:

_note: the `.propName=${val}` syntax denotes a property binding not an attribute binding e.g. `el.propName = val` rather than `el.setAttribute('propName', val)`_

```js
// popup-button.js
import {LitElement, html} from 'lit';

class PopupButton extends LitElement {
  get popupEl() { this.shadowRoot?.querySelector('popup') ?? undefined; }
  static properties = {anchorEl: {attribute: false}};
  anchorEl = undefined; // type is HTMLElement|undefined

  render() {
    return html`
      <button .togglepopup=${this.popupEl}>
        Click me to open popup
      </button>
      <div popup .anchor=${this.anchorEl}>...</div>`;
  }
}

customElements.define('popup-button', PopupButton);

// usage: <popup-button .anchor=${document.body.querySelector('#my-anchor')}></popup-button>
```

**The negatives** are that there is current no precedent that I know of for an element property accepting both a string, or an element reference.

### Function setters

**The Positives** about this approach are that it will enable all these use cases and it fits with precedent (not having a single property accept HTMLElement or string)

**The Negatives** requires component authors to wire things up a bit more. e.g.

React:

```jsx
// PopupButton.jsx
import React, { useRef, useCallback } from "react";

export default ({anchorIdOrRef}) => {
  const popupRef = useRef();
  const buttonRef = useCallback(buttonEl => {
    buttonEl.togglePopUp(popupRef.current);
  }, [popupRef]);

  useCallback(() => {}, []);

  return (
    <>
      <button ref={buttonRef}>
        Click me to open popup
      </button>
      <div popup ref={popupRef} anchor={anchorIdOrRef}>...</div>
    </>
  );
};
```

Lit:

```js
// popup-button.js
import {LitElement, html} from 'lit';

class PopupButton extends LitElement {
  get buttonEl() { this.shadowRoot?.querySelector('button') ?? undefined; }
  get popupEl() { this.shadowRoot?.querySelector('popup') ?? undefined; }
  static properties = {anchorEl: {attribute: false}};
  anchorEl = undefined;

  render() {
    return html`
      <button>
        Click me to open popup
      </button>
      <div popup>...</div popup>`;
  }
  
  firstUpdated() {
    this.buttonEl.togglePopUp(this.popupEl);
  }
  
  updated(changed) {
    if (changed.has('anchorEl')) {
      this.popupEl.setAnchor(this.anchorEl);
    }
  }
}

customElements.define('popup-button', PopupButton);
```

## Acceptance criteria

Some sort of element-reference imperative API for `anchor` is defined, or something that makes it easy to componentize HTMLElement[popup], especially in Shadow DOM

**Comment by e111077** [comment]
This is in reference to the discussion on #357

Additionally, by not declaratively linking two components via IDs and general ID incompatibilities with shadow dom, this means it might require strong support from #329 likely via `role` and `aria-*`

**Comment by mfreed7** [comment]
Thanks for opening this issue and enumerating the various possible courses of action. Sorry there's been such a delay. But I'm in the process of implementing a prototype of the [new Popup API](https://open-ui.org/components/popup.research.explainer) and I got to the part where I might implement this bit.

Of your two approaches, it sounds like you think <span>#</span>1 is the most developer-friendly. If so, I agree. I'm in favor of just allowing the `anchor` and `popup` (actually [now it's called](https://open-ui.org/components/popup.research.explainer#declarative-trigger-the-triggerpopup-attribute) `triggerpopup`) properties to directly accept an `Element` or a `DOMString`. While there isn't a precedent of this exact combination, there are definitely other WebIDL attributes that accept multiple types. So I don't think that's too much of an issue.

The open issues that I can see are:

1. This might (?) be the first case where we're allowing a cross-shadow reference between elements like this, and I'm worried that there might be some kind of a shadow element leak. I can't think of how, since to hook things up, you already need references to both sides of the "linkage". But I'd like smarter people than myself to think about this and confirm.

2. What happens in this case?

```html
<button>Click me</button>
<div popup=popup>I'm a popup without an id</div>

<script>
const button = document.querySelector('button');
button.triggerPopup = document.querySelector('[popup]');
const attr = button.getAttribute('triggerpopup'); // What does this return?
</script>
```

**Comment by e111077** [comment]
Heya no worries on the timing, just happy to hear this is getting some love!

1. I think this specific manner may be first of its kind (via a setter) as most I've seen are references via getters with a clear point of diassociation. e.g. `HTMLInputElement.form` will return the associated `HTMLFormElement` but disassociates on element disconnect or `<label>`'s `.control` property. I think the closest that comes to this is the Accessibility Object Model currently under work ([explainer link](https://wicg.github.io/aom/explainer.html))
2. It should return the current attribute (`null`) like `<input>` treats `value`'s attribute vs property.

**Comment by emilio** [comment]
For reference, as a point of prior art, the anchor in XUL popups is specified only on open, as an element reference:

 * https://searchfox.org/mozilla-central/rev/d34f9713ae128a3138c2b70d8041a535f1049d19/dom/webidl/XULPopupElement.webidl#78

The element has a readonly getter for that (that returns non-null while open):

 * https://searchfox.org/mozilla-central/rev/d34f9713ae128a3138c2b70d8041a535f1049d19/dom/webidl/XULPopupElement.webidl#174

Reading the original test-case in https://github.com/openui/open-ui/issues/382#issue-961097192, I'd also note that it is probably reasonable to let popups look _up_ the containing DOM tree. The problematic case is digging into shadow trees for IDrefs (which is a no-go). Things like nested `<svg:use>` already look into containing trees, for the record.

**Comment by mfreed7** [comment]
> For reference, as a point of prior art, the anchor in XUL popups is specified only on open, as an element reference:
> 
> * https://searchfox.org/mozilla-central/rev/d34f9713ae128a3138c2b70d8041a535f1049d19/dom/webidl/XULPopupElement.webidl#78
> 
> The element has a readonly getter for that (that returns non-null while open):
> 
> * https://searchfox.org/mozilla-central/rev/d34f9713ae128a3138c2b70d8041a535f1049d19/dom/webidl/XULPopupElement.webidl#174
> 
> Reading the original test-case in [#382 (comment)](https://github.com/openui/open-ui/issues/382#issue-961097192), I'd also note that it is probably reasonable to let popups look _up_ the containing DOM tree. The problematic case is digging into shadow trees for IDrefs (which is a no-go). Things like nested `<svg:use>` already look into containing trees, for the record.

Thanks for this comment (and the discussion just now). A few comments/counterpoints:
 - As much as possible, one of the [goals for this API](https://open-ui.org/components/popup.research.explainer#goals) is to enable functionality without requiring Javascript. In fact, that's the entire purpose of the `togglepopup` attribute. I don't think there'd be a point in that attribute if it was required as part of `.showPopup()`. Perhaps your point is a good one w.r.t. the `anchor` attribute though.
 - Another counterpoint for `anchor` is that we're hoping to re-use this attribute as part of the [anchor positioning proposal](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/CSSAnchoredPositioning/explainer.md), and the way that's going, it might not require things to be in the top layer. If so, I'd hate to tie `anchor` back to the `.showPopup()` call.
 - Allowing a shadow-contained element to "connect" to an IDref in a containing tree. I hadn't thought about that, but you're right it's a possibility. That might even open up most of the typical use cases? I am a bit hesitant to follow the lead of `<svg:use>` just given how different that one is. But ok. This might be a way around allowing assignment of element references in order to (basically) support shadow dom.

**Comment by e111077** [comment]
For looking up the tree for idrefs, I think the most-reasonable behavior is perhaps like you said not to go digging in shadow roots, but it sounds vaguely similar to `:host-context()` and _may_ run into the same concerns Emilio raised in w3c/csswg-drafts#1914.

But limiting anchor / idref lookup _only_ to the parent tree (please lmk if I'm misunderstanding your suggestion) might run into issues such as the use case of using a singleton popup element, which is what we ended up doing at YouTube, since the number of inert / unused popup tooltips on a site that large was starting to cause performance problems.

Though, if this proposal fixes the stacking context problem that required popups to be hoisted to the end of `<body>` it might be doable to write a simple JS function to dynamically append a popup element inside the fed element reference.

**Comment by emilio** [comment]
I'm curious about whether there's a use case for changing the target anchor while the popup is already open (and whether hiding and reopening the popup is not an option / acceptable workaround, assuming that's an edge case).

Reason for that question is that it can change the different trade-offs significantly. For example, looking up idrefs in arbitrary trees "up" is trivial with such a model (you just go up calling `getElementById` just before opening the popup). It's however non-trivial if we need to track all those mutations (because suddenly an idref depends on mutations in various dom trees and so).

**Comment by scottaohara** [comment]
one use case is the reuse of a common component (popup) that can be invoked by different triggers.

for instance, i see this a lot with react applications where there is a single popup that is reused across multiple instances and the contents of the popup, even if they don't necessarily change - e.g., menu items - are associated with a different invoking element and it's parent context.

For instance, a table/grid that contains rows of data where there is a menu button that invokes a menu popup that allows a user to do various actions.  A single popup component can be reused for each of these invoking buttons.  Additionally, a common use case here is for these menu popups to contain a delete menu item.  In these cases an alternate "anchor" element needs to be specified to ensure that focus does not return to the body - which commonly results in screen reader users being sent back to the top of the document and needing to re-navigate the page to return to where they last left off.

Whether or not both of these situations is exactly the intent of the anchoring mechanism, it is at least related to what  authors need to do now, and have expressed frustration over, not to mention the fact that users who need this mechanism in place are left to wait for custom implementations.

**Comment by emilio** [comment]
@scottaohara sure, but I don't see how that would change the anchor _while the popup is open_, right? What am I missing?

**Comment by scottaohara** [comment]
Ah, that could be useful for what people have referred to as info tours / teaching ui. Where a popup points to different ui elements and there are “previous” and “next” buttons in the popup to have its content change and it be associated with those different ui. 

I suppose you could have the popup close and a new one reopen with its new anchor instead?

**Comment by mfreed7** [comment]
So I should have realized this, but combining the resolution above with [the conversation here](https://github.com/openui/open-ui/issues/549#issuecomment-1163273809), we can't do both. Essentially, we've decided:

- The function to show the popup is `myPopup.showPopUp();`.
- The IDL to set the `showpopup` attribute is `myPopup.showPopUp = 'idref';`

Same goes for `hidePopUp`. We need new names. I suggest that the things that we rename be the new IDL attributes we resolved to add above, and not the `showPopUp()`/`hidePopUp` functions, since those are much more commonly-used.

One idea is:
```javascript
myPopup.togglePopUpAttr = 'idref';
myPopup.showPopUpAttr = 'idref';
myPopup.hidePopUpAttr = 'idref';
```

Thoughts? @domenic

**Comment by domenic** [comment]
IDL attribute names really need to match content attribute names. So please don't do this Attr suffix thing. Either rename both the content and IDL attributes, or rename the methods.

**Comment by mfreed7** [comment]
> IDL attribute names really need to match content attribute names. So please don't do this Attr suffix thing. Either rename both the content and IDL attributes, or rename the methods.

I swear, naming is the hardest part of this pop-up API.

I'm putting this back on the Agenda to discuss. My new proposal is that we **do not** provide IDL reflections of the string values for the `togglepopup`, `showpopup`, and `hidepopup` content attributes. In the future, we might (as discussed above) provide a set of IDL attributes that allow setting the elements directly (not through idrefs), but that would anyway have a different name.

The OP of this issue is really about allowing element references directly. The resolution above, which allows access to the **idref strings** didn't solve that problem. And I'm not sure it solves **any** problem. What is the use case for setting these idref values through JS? The explicit point of `togglepopup`, `showpopup`, and `hidepopup` content attributes is to allow a declarative (in HTML) connection between an invoking element and a pop-up. If you're using Javascript already, would you not just use the `element.showPopUp()` and `element.hidePopUp()` functions to show and hide the pop-up as you'd like? Or if you really want to use the content attributes, you can use `element.setAttribute('showpopup','idref');`.

I'm afraid that by renaming `togglepopup`, `showpopup`, and `hidepopup` content attributes, we'll make them harder to understand and use in the primary (HTML) use case. We spent some significant time getting to good [names](https://github.com/openui/open-ui/issues/508) and [behaviors](https://github.com/openui/open-ui/issues/523) for these attributes, I think.

**Comment by domenic** [comment]
All content attributes need to have IDL reflections!! I'm sorry this is hard, but these are basic HTML design principles. Please do not violate them.

**Comment by mfreed7** [comment]
> All content attributes need to have IDL reflections!! I'm sorry this is hard, but these are basic HTML design principles. Please do not violate them.

Two options on the table, then:

- Rename `showPopUp()` and `hidePopUp()`, or
- Rename the `showpopup` and `hidepopup` (and likely `togglepopup`) content attributes.

Preferences? Ideas?

**Comment by mfreed7** [comment]
My backup plan, absent a better suggestion, is to rename the activation functions as:

`element.showThePopUpOnTheScreenRightNowPlease()`
`element.couldYouPleaseHideThisPopUpNow()`

since they won't clash with anything.

**Comment by VicGUTT** [comment]
Preferences to renaming the methods.

Ah! You kid but they have the benefit of being the upmost explicit 😉

I'm guessing alternatives could be `(open|close)PopUp()` but we'd loose the "show/hide" parallel with the content attributes (and therefore the IDL reflections as well).

Or `(open|close)AsPopUp()` maybe ?

I'd have to brainstorm a bit more for other possible alternatives. The only solution allowing us to keep the "show/hide" parallel would be elongating the method names anyway.

**Comment by e111077** [comment]
Heya, sorry to detract from the naming conversation, I've updated the issue to be in sync with the latest proposal of popup now being an attribute.

But looking at [Mason's earlier comment](https://github.com/openui/open-ui/issues/382#issuecomment-1143821910) idrefs are still quite a hassle especially in SD since the lookup would not necessarily be in the parent tree. When we implemented YouTube tooltip we had to make a singleton tooltip that would be reused as the sheer number of hidden tooltip nodes across the site was causing significant performance issue. Simply converting the YT's situation to this proposal it would look like this:

```html
<yt-app-shell>
  # SR
    <yt-text-with-tooltip id="a"></yt-text-with-tooltip>
    <yt-text-with-tooltip id="b"></yt-text-with-tooltip>
    <yt-text-with-tooltip id="c"></yt-text-with-tooltip>
    <!-- showPopUp or attribute added or removed dynamically on the above nodes -->
    <yt-reusable-component>
      # SR
        <!-- shadow roots can reuse id's -->
        <third-party-component-that-needs-a-tooltip id="a" />
      #/SR
    </yt-reusable-component>
  #/SR
</yt-app-shell>
<singleton-popup>
  # SR
    <div popup id="singleton-popup" anchor="b">
      <slot></slot>
    </div>
  #/SR
  <!-- dynamically-inserted content -->
</singleton-popup>
```

Would you recommend that for the situation above one would need to dynamically render a `<singleton-popup>` (no longer singleton i guess) in each shadow root of each owned component that requires a tooltip and as a sibling to any third-party components in which the shadow root cannot be modified? e.g.

```html
<yt-app-shell>
  # SR
    <yt-text-with-tooltip id="a">
      # SR
        ...
        <!-- dynamcially render <yt-popup anchor=${this.id}> and call show|hidePopup() -->
      #/SR
    </yt-text-with-tooltip>
    <yt-text-with-tooltip id="b">
      # SR
        ...
        <!-- dynamcially render <yt-popup anchor=${this.id}> and call show|hidePopup() -->
      #/SR
    </yt-text-with-tooltip>
    <yt-text-with-tooltip id="c">
      # SR
        ...
        <!-- dynamcially render <yt-popup anchor=${this.id}> and call show|hidePopup() -->
      #/SR
    </yt-text-with-tooltip>
    <!-- showPopUp or attribute added or removed dynamically on the above nodes -->
    <yt-reusable-component>
      # SR
        <!-- shadow roots can reuse id's -->
        <third-party-component-that-needs-a-tooltip id="a" />
        <!-- dynamcially render <yt-popup anchor="a"> and call show|hidePopup() -->
      #/SR
    </yt-reusable-component>
  #/SR
</yt-app-shell>

<!-- example definition of yt-popup -->
<yt-popup>
  # SR
    <!-- yt-popup exports the div's show|hide|togglePopup methods and forwards the anchor attribute to the div -->
    <div popup anchor="${this.anchor}">
      <slot></slot>
    </div>
  #/SR
  <!-- dynamically-inserted content -->
</yt-popup>
```

In general it might be a bit annoying of a setup, but might be doable for this use case.

Though this solution would not be satisfactory for the "tutorial of this site" setup where you'd want to animate a singleton popup between steps. You'd still run into the initial case where the the popup would need to reference an ID across shadow roots that are not a sibling or in ancestor chain

**Comment by dbaron** [comment]
I feel like it should be possible to come up with a reasonable naming distinction that distinguishes between `element.showPopUp()` and `element.hidePopUp()` (which are methods to be called on the popup element) and the `togglepopup`/`showpopup`/`hidepopup` attributes (which are attributes that go on the popup's triggering element).

A  few possibilities that I can think of (where I assume that we rename the two methods or the three attributes equivalently, and only describe one of the changes, except as noted):
1. rename `togglepopup` to `popuptotoggle` (etc.)
2. rename `togglepopup` to `popuptarget`, `showpopup` to `popupshowtarget`, and `hidepopup` to `popuphidetarget`.
3. rename `element.showPopUp()` to `element.popUpShow()` (etc.)

...though I don't particularly like any of them (but maybe dislike 2 the least).

**Comment by hidde** [comment]
I like this approach from @dbaron: 

> rename togglepopup to popuptarget, showpopup to popupshowtarget, and hidepopup to popuphidetarget.

as it is nice and short and relatively easy to read.

In general I feel it would be great to avoid synonyms for showing/hiding and work around in ways like the ones @dbaron describes.

**Comment by VicGUTT** [comment]
@hidde Agreed

**Comment by mfreed7** [comment]
Per the resolution, we've solved the issue of attribute reflections (of the string values) for the three triggering attributes. I'll leave this issue open for the (longer term) discussion about non-string-valued IDL reflections, which allow element references to be directly set.

**Comment by dbatiste** [comment]
@mfreed7 apologies if this is on a slight tangent to the original topic. Back in April you mentioned above:

>Another counterpoint for anchor is that we're hoping to re-use this attribute as part of the [anchor positioning proposal](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/CSSAnchoredPositioning/explainer.md), and the way that's going, it might not require things to be in the top layer. If so, I'd hate to tie anchor back to the .showPopup() call.

Are you suggesting that depending on the outcome of the anchored positioning proposal, that the popup attribute may not require positioning on the top-layer? It sounds like even with anchor positioning as outlined in the proposal, the popup would still be constrained to the bounding container having overfow `scroll`, `hidden`, `clip`. This is the primary use-case that I am hopeful the popup attribute will help with (currently experimenting).

**Comment by mfreed7** [comment]
> Are you suggesting that depending on the outcome of the anchored positioning proposal, that the popup attribute may not require positioning on the top-layer? It sounds like even with anchor positioning as outlined in the proposal, the popup would still be constrained to the bounding container having overfow `scroll`, `hidden`, `clip`. This is the primary use-case that I am hopeful the popup attribute will help with (currently experimenting).

No, sorry, I meant that the anchor positioning API will allow not **just** pop-ups to be anchor positioned, but also ordinary elements that are fixed/absolute positioned. The pop-up API definitely still puts elements into the top layer, which escapes overflow containers, transforms, etc.

**Comment by mfreed7** [comment]
Based on the HTML spec PR review, the IDL reflections for these three attributes has been changed to be element references, and renamed accordingly: `popoverToggleTargetElement` returns `Element?`.

I'm going to close this issue.
