### ISSUE TITLE
[select] Clarify use of Enter/Space keys for opening/closing listbox

### ISSUE THREAD

**Issue by dandclark** [openui/open-ui#386]
The tables in https://open-ui.org/components/select#events-1 suggest that either Enter key or Spacebar can be used to open the select's listbox when the popup is closed. If the listbox is opened (and contains focus), either Enter key or Spacebar can be used to close it.

The behavior I observe in browsers is a bit different:
**Chromium**: Either Enter or Spacebar can open the listbox. Only Enter can close it.
**Firefox**: Only Spacebar can open the listbox. Only Enter can close it.
**Safari**: Only Spacebar can open the listbox. Either Enter or Spacebar can close it.

Is there any particular reason to prefer any of these? My preference is to keep the current behavior at https://open-ui.org/components/select#events-1, but since all these browsers are different maybe there's some reason to be more restrictive that I'm not understanding.

**Comment by chrisdholt** [comment]
@dandclark Should we perhaps drive towards a more objective standard here in the ARIA practices documentation? Select is essentially a non-editable combobox (though I suppose we are looking to support that behavior as well). Should the behavior in question align to [this document](https://w3c.github.io/aria-practices/#combobox)?

**Comment by dandclark** [comment]
Yes, aligning to the ARIA practices does seem like the reasonable thing to do here.

**Comment by andrico1234** [comment]
It also looks like the Open UI spec supports [typeahead](https://open-ui.org/components/select#typeahead). Could this  cause a conflict as the `space` could both close the select box and type text?

**Comment by chrisdholt** [comment]
> It also looks like the Open UI spec supports [typeahead](https://open-ui.org/components/select#typeahead). Could this cause a conflict as the `space` could both close the select box and type text?

In the case of aligning to ARIA practices, I don't believe space would close the box: https://w3c.github.io/aria-practices/#combobox-keyboard-interaction - a benefit of aligning with that standard rather than with browser specific conventions is that we avoid the issue altogether :)

**Comment by chaance** [comment]
I quickly read through the IRC logs and I didn't see it noted, but if the selectmenu is used as a form control I'd expect `Enter` to trigger an [implicit submission for UAs that support it](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission). Would that distinction make a difference for a selectmenu that isn't associated with a form?

**Comment by scottaohara** [comment]
unless things have somehow changed in the past year+, it seems that Dan's initial observation of behavior was windows specific for chromium?  on macOS its consistently space to open (among other keys that are platform specific) and enter to select an option to close across all browsers.  and firefox matches that behavior on windows as well.


imo, the opening behavior should match the majority of the implementations.  i'm curious why windows chromium deviates.

space does not close the popup so long as focus is actually on an option from the listbox.  depending on the platform, focus may not move to the options on initial opening, which would mean that space could close the popup.  This seems an area where it'd be nice to align on one behavior across platforms.

**Comment by josepharhar** [comment]
I read through https://w3c.github.io/aria-practices/#combobox and these are my findings:

### Spacebar when listbox is open

Spacebar should be for typeahead instead of selecting an option and/or closing the listbox:

> When focus is in a listbox popup:
> Any printable character:
> If the combobox is editable, returns the focus to the combobox without closing the popup and types the character.
> Otherwise, moves focus to the next option with a name that starts with the characters typed.

### Spacebar when the listbox is closed:

> When focus is in the combobox:
> Printable Characters:
> If the combobox is editable, type characters in the combobox. Note that some implementations may regard certain characters as invalid and prevent their input.
> If the combobox is not editable, optionally moves focus to a value that starts with the typed characters.

I guess that spacebar should also be for typeahead instead of opening the listbox? However,  in [the example](https://w3c.github.io/aria-practices/examples/combobox/combobox-select-only.html) space opens the listbox...

Personally I don't see any reason why pressing space shouldn't open the listbox, especially since all browsers (on all platforms?) currently open the `<select>` dropdown with spacebar. @chrisdholt @scottaohara what do you think?

### Enter when listbox is open

The currently selected option should be chosen and the listbox should be closed:

> When focus is in a listbox popup:
> Enter: Accepts the focused option in the listbox by closing the popup, placing the accepted value in the combobox, and if the combobox is editable, placing the input cursor at the end of the value.

### Enter when the listbox is closed

> When focus is in the combobox:
> Enter: If the combobox is editable and an autocomplete suggestion is selected in the popup, accepts the suggestion either by placing the input cursor at the end of the accepted value in the combobox or by performing a default action on the value. For example, in a messaging application, the default action may be to add the accepted value to a list of message recipients and then clear the combobox so the user can add another recipient.

It doesn't say what to do when the combobox is not editable. However, [the example](https://w3c.github.io/aria-practices/examples/combobox/combobox-select-only.html) opens the listbox when enter is pressed. Perhaps we should also open the listbox when enter is pressed? @chrisdholt @scottaohara what do you think?

**Comment by josepharhar** [comment]
@scottaohara @aleventhal If yall have any thoughts about [my last comment](https://github.com/openui/open-ui/issues/386#issuecomment-1439156154) and/or could attend the next openui meeting to discuss it would be greatly appreciated

**Comment by scottaohara** [comment]
>I guess that spacebar should also be for typeahead instead of opening the listbox? However, in [the example](https://w3c.github.io/aria-practices/examples/combobox/combobox-select-only.html) space opens the listbox...

per my previous comment, space is used to open the combobox - matching the native HTML select element - which is what the linked example is attempting to emulate (sans platform specific behaviors, since that'd be annoying for a developer to do).  since selectmenu isn't an editable combobox, all the behaviors associated with editable combobox should be ignored for now.  

>Enter when the listbox is closed

I also touched on this in my previous comment.  Enter to open is odd since that key SHOULD be used to submit a form (if the element is associated with a form).  Windows Chromium is the outlier in behavior - this seems like a potential bug unless there is some reasoning for the deviation, and the deviation ONLY on windows since Chromium on macOS also only allows space to open the select element.  

Reminder that APG is a good reference, but it does not represent official behavior.  especially since being custom implementations to demonstrate ARIA, the authors made specific choices of browser behaviors to emulate from the different platforms.

**Comment by josepharhar** [comment]
Thanks scott! Here is my proposed behavior/resolution:

#### 1. Spacebar while the listbox is closed should open the listbox.

As scott mentioned, this is what the existing select element currently does. This is also what the ARIA practices example does.

#### 2. Spacebar while the listbox is open should do typeahead.

This is what the existing select element does and is what the ARIA practices says to do.

#### 3. Enter when the listbox is open should choose the selected item and close the listbox.

This is what the existing select element does and is what the ARIA practices says to do.

#### 4. Enter when the listbox is closed should submit the form.

This is what the existing select element does except on windows chromium. The ARIA practices is unclear and their example opens the listbox, but as scott suggested it would be better to match the existing select element and we should not open the listbox even if the selectmenu isn't associated with a form.

**Comment by josepharhar** [comment]
We resolved to do the proposal in my last comment

**Comment by josepharhar** [comment]
Since we decided to reuse the select element instead of create a new selectlist/selectmenu element, the diverging keyboard behavior got some negative feedback: https://issues.chromium.org/issues/429647164

I am planning on reverting it back to do the same thing that appearance:auto select does.
