### ISSUE TITLE
[select] Clarify the need for both part="option" and <option>

### ISSUE THREAD

**Issue by ipopescu93** [openui/open-ui#396]
Should we support both `part="option"` and `<option>` or just update the [content model](https://html.spec.whatwg.org/multipage/form-elements.html#the-option-element:concept-element-content-model) for `<option>` to support arbitrary content when it is a descendant of `<select>`?

Note that supporting both `part="option"` and `<option>` could lead to inconsistency when reading / writing the IDL property (e.g. `selected=false`);

**Comment by dandclark** [comment]
My preference is to apply part behavior only for `<option>` (and update the `<option>` content model), for the reason you point out (inconsistency with the IDLs for `<div part="option">` vs `<option>`).

Supporting two ways to supply options seems like extra complexity without any concrete benefit.

There's also some precedent for this now since we only allow the listbox part to be a `<popup>`, i.e. `<div part="listbox">` doesn't work.

**Comment by chrisdholt** [comment]
> My preference is to apply part behavior only for `<option>` (and update the `<option>` content model), for the reason you point out (inconsistency with the IDLs for `<div part="option">` vs `<option>`).
> 
> Supporting two ways to supply options seems like extra complexity without any concrete benefit.
> 
> There's also some precedent for this now since we only allow the listbox part to be a `<popup>`, i.e. `<div part="listbox">` doesn't work.

I'd agree here - the only thing I could see as being a suitable and reasonable replacement from an attribute standpoint would be an element with a role of option. I probably wouldn't tie to `part`, but I would probably push to support elements with a `role` of option if it wasn't *overly* complex. The primary reason here is that option itself may have limitations from a visual system standpoint. This is the approach we've taken in FAST. We'll support our own custom option element, `option`, or elements with a role of option as slotted content with behaviors. I think there is some benefit here and it doesn't fall apart as much as targeting part because you are hooking off an attribute which is communicating the same underlying behavior to assistive tech, which would be my primary worry with hooking into `part` (we get an inaccessible control). 

I've missed a few calls recently where perhaps this was discussed, but is there a specific reason to *not* support something such as: `<div role="option">Foo</div>`?

**Comment by dandclark** [comment]
Hmm, customElement options are a use case I hadn't thought of. Allowing that might be enough of a reason to support non-`<option>` option parts.

The reason we'd been considering not supporting them basically comes down to complications regarding differences in the IDL properties of options vs non-options. For example, consider the `disabled` IDL property of [HTMLOptionElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionElement#properties), which is reflected with the "disabled" content attribute (see https://developer.mozilla.org/en-US/docs/Glossary/IDL#content_versus_idl_attributes).

Consider this case:

```html
<selectmenu>
    <option disabled>one</option>
    <div disabled part="option">two</div>
</selectmenu>
<script>
    const option = document.querySelector("option");
    const div = document.querySelector("div");
    console.log(option.disabled); // true
    console.log(div.disabled); // undefined
</script>
```

If controller code uses the IDL property to determine disabled status, then the option will be disabled but the div will not be, since the disabled content attribute is not reflected to the IDL property for divs. This could be confusing for authors.

Instead, the controller code could check the `disabled` content attribute to determine disabled status, but then authors who try to set disabled status in this way will run into problems:

```html
<selectmenu>
    <option>one</option>
    <div part="option">two</div>
</selectmenu>
<script>
    const option = document.querySelector("option");
    const div = document.querySelector("div");
    option.disabled = true;
    div.disabled = true;

    console.log(option.hasAttribute("disabled")); // true
    console.log(div.hasAttribute("disabled")); // false
</script>
```

So, there are some stumbling blocks for both implementers and developers here. Allowing only `<option>`s is the most straightforward way to resolve it. But, the use case of custom option elements might be important enough to make it worth handling these tricky cases in other ways, e.g. considering an option part to be disabled if *either* the IDL property or the content attribute are set.

Separately, using `role` instead of `part` seems like a potential improvement. I'll raise that over at https://github.com/openui/open-ui/issues/354.

**Comment by chrisdholt** [comment]
> So, there are some stumbling blocks for both implementers and developers here. Allowing only `<option>`s is the most straightforward way to resolve it. But, the use case of custom option elements might be important enough to make it worth handling these tricky cases in other ways, e.g. considering an option part to be disabled if _either_ the IDL property or the content attribute are set.

I think the callout for something like disabled IDL and other variations is definitely something to be aware of. I do, however, think that not supporting custom elements here would be a miss. While less than ideal, I think that a little added logic could make it relatively easy to support everything here by hooking off `role`. If `role="option"` is present, we have pretty clear guidance as to what needs to be true/exist from an API standpoint in order for these states to be conveyed to AT. In this case we're likely making some assumptions, but we could also think of it as a contract :). We have clear guidance from ARIA regarding what an element with `role="option"` should support, so while it's a bit more code, I think we *could* likely check for a few things and set/act according to what's present there. I will note, that it is possible with custom elements to define a disabled attribute/idl so it *may* exist...but in this specific case could we not check for `disabled` OR `aria-disabled="true"`?

**Comment by chrisdholt** [comment]
Thinking through the end of today’s call and @mfreed7’s comment on being able to walk and pierce the shadow root for option elements, it sounds like Safari is the outlier here. Firefox appears to be imminent with delegatesFocus and we already leverage this pattern elsewhere as it stands.

So, changing my tune a bit - I’m fine if we want to only support option elements so long as we have a method of addressing the custom element scenario (sounds like we do). Ideally I’d love to support both here but if every issue ends up being an issue with WebKit support, we shouldn’t let that stop us from doing what we think is right and correct. As a library author we’ll need to deal with these regardless. @gregwhitworth and @dandclark as FYI :)

**Comment by dandclark** [comment]
Per the resolution [here](https://github.com/openui/open-ui/issues/396#issuecomment-954084906) I think we can consider this issue to be resolved. Closing.
