### ISSUE TITLE
[Meta] Better onboarding for new Open UI members or non-members

### ISSUE THREAD

**Issue by davatron5000** [openui/open-ui#398]
It has come up in the Discord a few times about "how do I get involved?" or "where do I start?" or "can I start research on [some component]?" I also think there's opportunity to give visibility to non-members into what Open UI is working on. 

Just riffin some ideas...

- List or kanban where research/proposals are mapped to [our 0-4 working mode stages](https://open-ui.org/working-mode)
- Welcome message/channel in Discord directing people to starting points to get involved
- How-to guide for Design System contributors to add their design systems to the [Component Matrix](https://open-ui.org/research/component-matrix)
- Better leveraging of [`good first issue`](https://goodfirstissues.com/), `help wanted`, or `discussion` labels 
- Maintain 1-paragraph TL;DRs for each initiative and its status.

My heart isn't committed to any of these (except the Kanban), would love to hear thoughts.

**Comment by gregwhitworth** [comment]
Thanks @davatron5000 and yeah this is a common problem. I like the stages Kanban approach; let's do that for sure. I did add a bot to the Discord channel but have no idea if it's working or not so I'll need to dig into a bit as I'm not a discord expert by any stretch of the word.

Regarding how to guides we do have them generally:

* [Adding a design system](https://open-ui.org/design-system-analysis-guide)
* [Getting Involved](https://open-ui.org/get-involved)

The thing that I'd like to see that I've noted in the past for simplifying "Getting Involved" is pivoting from the stages/objectives to a JTBD type format.

EG: I'd like a page that is something like: "I'd like to create a new HTML element"

That would then list out the general process of what it will take in order to achieve that. This will result in going through all of those stages but also help in the "getting involved" aspect.

> Better leveraging of good first issue, help wanted, or discussion labels

Agreed, one thing that I think also hurts us a bit here is that there are so few contributors to the project. I'd like to get all regularly engaged members to be added to the contributors team so they can add labels and help triage issues. Overall great suggestions.

One thing to make it so that this doesn't just go stale - do you mind taking a shot at the Kanban board?

**Comment by gregwhitworth** [comment]
This still can be improved but no one is actively going after this currently so I'm going to close this.
