### ISSUE TITLE
[Notification/Message] Defining component behaviour

### ISSUE THREAD

**Issue by andrico1234** [openui/open-ui#400]
> Naming things is hard
>   --Everyone, probably

We've had some great discussion and input in this [issue](https://github.com/openui/open-ui/issues/397) focused on naming the toast/notification/message component.

What's blocking progress, and I'm [not](https://github.com/openui/open-ui/issues/397#issuecomment-912864574) [the](https://github.com/openui/open-ui/issues/397#issuecomment-913428808) only one who feels this way, is the lack of a definition for the component's behaviour. We can't make an informed decision around what to call this component if we don't have a general idea about what it does.

Judging from the issue, there are two broad definitions.

*For the sake of this issue I've given them names and described behaviours but nothing is confirmed, everything is still up for conversation.*

## Convenience wrapper for live region

Used as a convenience wrapper around a number of  live region roles, like alert, status, and log. The [proposal draft](https://docs.google.com/document/d/1TYvACxInNMSjf7WQTkG9qEJKYbW8ZMrk5xmEpeXXH4M/edit?usp=drivesdk) has a bit more context around this.

I might be wrong here, but going with this implementation could mean little/no change around interaction behaviour.

A benefit to this approach is improved usability for those using [assistive technologies](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions).

A concern brought up in the [std-toast discourse](https://discourse.wicg.io/t/proposal-toast-ui-element/3634/25), is that the onus for implementing an accessible interaction still lies on library authors and frontend developers.

## Time-sensitive and non-disruptive notice

This kind of behaviour would fall more in line with what we associate as a notification, alert, or toast. This is the kind of implementation I had in mind when proposing this component. I proposed it because there are a lot of similar implementations out there from developers roll on their own, or use via component libraries.

In short:

> A time-sensitive and non-disruptive notice to let the user know of a change in the application's state.

Yinonov describes similar [behaviour in the issue](https://github.com/openui/open-ui/issues/397#issuecomment-913232513).

This is the kind of behaviour that's described in the [component matrix](https://open-ui.org/research/component-matrix) as `alert`, `toast`, `notification`.

Off the bat, a component like this offers up dilemmas around dismissing interactivity and default styling in relation to the document flow.

## Other

Are there any other possible definitions for behaviour that I've missed out? I'll be happy to add them to my list.

I've expressed the options I had in mind when proposing this component, but am not tied to the `notice` implementation. I'm willing to go with whichever option we believe would provide the most benefit to the web.

**Comment by andrico1234** [comment]
just adding that I'd like to take it to next week's Telecon

**Comment by yinonov** [comment]
laying out few key points to 
- **Interaction** - is it possible to have action buttons toggled by authors? so that it can act as both `toast` & `snackbar`, there's also a legacy web differentiation named `alert` & `prompt` (it **IS** being deprecated so maybe shouldn't be aligned with)
- **Stacking** - single instance at a time? some libraries stack multiple notifications 
- **Positioning** - customizable? a predefined set of positions? browser defined?

**Comment by andrico1234** [comment]
I'd like to not focus too much into interaction specifics (though these are all valid questions and I'll add them to the proposal draft), but more a question on the scope of behaviour,

I.e. should the Notification/Message be a convenience wrapper around aria roles, or should be a standardized implementation of similar to components  like [Ant's message](https://ant-design-vue.github.io/antv-doc/components/message/)

My bad, i should've been more explicit in the initial issue message!

**Comment by chrisdholt** [comment]
I think the key here to defining behavior is to understand what the right role is for this control. As I mentioned on another thread or issue, the fundamental question is whether or not the control can/will include interactive elements. Certain roles permit interactive content while others do not; understanding the intent behind these roles are key to understanding how all users will interact with a given control. Just because things look similar, are common, or exist across design systems (toast, snackbar) doesn't mean they are 1) a good, accessible pattern, 2) the *same* implementation.

[alert](https://w3c.github.io/aria-practices/#alert) - _"Because alerts are intended to provide important and potentially time-sensitive information without interfering with the user's ability to continue working, it is crucial they do not affect keyboard focus."_ If the plan is to support interactive elements within the "toast", then `alert` is likely not the ideal underlying role or pattern. If we determine that toasts should *not* include interactive content, this is likely a fine candidate for the element role itself.

[alertdialog](https://w3c.github.io/aria-practices/#alertdialog)- _"An alert dialog is a modal dialog that interrupts the user's workflow to communicate an important message and acquire a response. Examples include action confirmation prompts and error message confirmations."_ I don't think every toast would fall into this category.

[dialog](https://w3c.github.io/aria-practices/#dialog_modal) - Dialogs may contain interactive content. Dialogs may or may not be modal. 

Tagging @gregwhitworth as this pertains to his comment [here](https://github.com/openui/open-ui/issues/397#issuecomment-913201519). I'm not sure that `dialog` is the best implementation for *every* toast, nor do I think it's necessarily the right name. My thought is that depending on requirements, this may be best accomplished as a *pattern* and/or guidance. If we can align on this only containing non-interactive content, then the `alert` role is fine and we can move on with naming given that context. However, if we believe that something like `toast` and `snackbar` are basically the same with exception that one includes interactive content, I think we should reconsider if this is best accomplished as a component or a pattern/guidance. Popup provides all hooks necessary to support the visual appearance and behavior of this from a positioning/elevation standpoint, while leaving open the ability to support any of the above roles based on the content model. In the case that the content model needs to support both text-only and interactive content, is it reasonable to consider that as an option here?

**Comment by aardrian** [comment]
This may be redundant to all participants, but I want to bring over what I think should be a starting point from the previous toast discussions — identifying how this is exposed to existing accessibility APIs. Otherwise we risk specifying something that cannot be implemented by devs because it has no accessibility affordances in browsers or AT.

To reprint my [2019 comment](https://github.com/jackbsteinberg/std-toast/issues/25#issue-455478352) about mapping to existing roles:

> [ARIA 1.2](https://www.w3.org/TR/wai-aria-1.2/) contains roles that do not have native HTML counterparts, as outlined in _[2.14 Aria roles and properties not available as features in HTML](https://www.w3.org/TR/aria-in-html/#aria-roles)_. A collection of roles that may apply to this proposal:
> 
> * [alert](https://www.w3.org/TR/wai-aria-1.2/#alert)
> * [log](https://www.w3.org/TR/wai-aria-1.2/#log)
> * [marquee](https://www.w3.org/TR/wai-aria-1.2/#marquee)
> * [status](https://www.w3.org/TR/wai-aria-1.2/#status)
> * [timer](https://www.w3.org/TR/wai-aria-1.2/#timer)
> 
> Each of these roles identifies how it is exposed to the accessibility APIs and what states and properties they should expose.
> 
> For any of these roles that you feel applies to the proposed toast element, then you may want to mint attributes to indicate which (eg: `type="alert|status|timer"`) and their associated ARIA states & properties (eg: `live="polite|assertive"` and/or `atomic="true|false"` and/or …).
> 
> At the very least, a native toast implementation should look to adopt one or more of these roles and follow the interactions already defined in the ARIA specification.

Where `alert` and `status` seemed to be the most straightforward fit.

Limiting to those roles also helped move along the conversation around the issue _[Avoid Interactive Children](https://github.com/jackbsteinberg/std-toast/issues/29)_.

**Comment by chrisdholt** [comment]
> This may be redundant to all participants, but I want to bring over what I think should be a starting point from the previous toast discussions — identifying how this is exposed to existing accessibility APIs. Otherwise we risk specifying something that cannot be implemented by devs because it has no accessibility affordances in browsers or AT.

I like to think this enhances my note above :). Thanks for posting.

**Comment by andrico1234** [comment]
Cheers folks! I'm in agreement with @aardrian that `alert` and `status` seem like appropriate starting points. I think you both better expressed what I had in mind as the `Time-sensitive and non-disruptive notice`.

**Comment by travisleithead** [comment]
Hmm. Just saw this and wondered to what extent it might overlap with https://wicg.github.io/aom/notification-api.html? (Geared specifically toward assistive technology users.)

**Comment by andrico1234** [comment]
To paraphrase on the 

Based on the Telecon resolution, we're going ahead with an `alert` component with the expectation that it will land  as an element in the HTML spec. I'll close this issue and continue work on the Stage 0 proposal for Alert.
