### ISSUE TITLE
[Popup] popup="" is supported on <button type=submit> but not <input type=submit>

### ISSUE THREAD

**Issue by zcorpan** [openui/open-ui#409]
https://open-ui.org/components/popup#the-popup-attribute

>The popup attribute is supported on a subset of interactive elements:
>
>button
>input in the button state
>input in the email, number, search, tel, text, or url states

There's an inconsistency between the first two: `popup` is supported on all `button` elements, including submit and reset buttons, but for `input` element only the `Button` state is supported.

https://html.spec.whatwg.org/multipage/form-elements.html#attr-button-type
https://html.spec.whatwg.org/multipage/input.html#attr-input-type

**Comment by gregwhitworth** [comment]
@mfreed7 friendly ping

**Comment by melanierichards** [comment]
This is my spec error. Personal POV is that we fix the discrepancy by limiting support to `button` in the `button` state, and do not support on `reset` or `submit`. The reset and submit states imply specific actions that will occur, and the button state is more appropriate to general-purpose commands (i.e. progressively show supporting UI).

**Comment by mfreed7** [comment]
Sorry for the delay, but I agree with @melanierichards. “Buttons” in either form (`<button>` or `<input type=button>`) should be supported. Buttons with prescribed actions (submit, reset) should not be supported. I think this makes sense and is consistent.

**Comment by melanierichards** [comment]
Thanks Mason! Adding to the agenda, hopefully this will be a quick resolution.

**Comment by zcorpan** [comment]
From what I can tell from the meeting notes above, the `input` element was discussed, but not the different `type`s of the `button` element. So that we're clear, is the resolution to allow `popup` for:

- `button` element whose `type` attribute is in the Button state
- `input` element whose `type` attribute is in the Button state
- `input` element whose `type` attribute is in the Email, Number, Search, Telephone, Text, or URL states

**Comment by scottaohara** [comment]
The different types of buttons were discussed, but allowing popup on the different text inputs you mentioned was only briefly mentioned.  It does seem reasonable that popup would be allowed on the inputs that presently allow the `list` attribute, so that authors can one day create styled type-ahead comboboxes.

per buttons specifically, the gist was that popup should not be allowed on a button that would submit or reset a form.

So for any of the following that are descendants of a form which can be submitted, or associated with such a form, popup would not be allowed:
* `input type=submit`
* `input type=reset`
* `input type=image`
* `button` with no `type` since it defaults to submit
* `button type=submit`
* `button type=reset`

But if any of those button types are used outside of a form / not associated with a form, in reality the reason to not use popop on these types goes away, since they will not submit or reset anything.

**Comment by zcorpan** [comment]
Making the rule depend on whether the button is associated with a form seems like unnecessary complication and confusion IMO. What's the benefit?

**Comment by scottaohara** [comment]
Understood.  The point is that a button can't both invoke a popup and submit/reset a form though.  So either the popup attribute is only allowed on buttons that have an explicit type=button, or the attribute is allowed on buttons so long as they don't submit a form.

**Comment by mfreed7** [comment]
To quickly summarize:
 - The question of **non-button** triggers is discussed in https://github.com/openui/open-ui/issues/420.
 - For **button** triggers, the desire is to make any button **that would not otherwise submit a form** able to trigger a popup. The open question is how best to specify and implement that desire.

Implementation-wise, at least in Chromium, that'd be relatively easy to do within the default `domactivate` event handler for buttons ([1](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/html/forms/html_button_element.cc;l=111;drc=5630be48e70e6de3514eb1f1e44c235bbec41d09), [2](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/html/forms/image_input_type.cc;l=99;drc=5630be48e70e6de3514eb1f1e44c235bbec41d09), [3](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/html/forms/submit_input_type.cc;l=67;drc=5630be48e70e6de3514eb1f1e44c235bbec41d09)) - we'd just check if the button being activated would be a successful form submitter, and if so, submit the form. Otherwise, activate the popup. How difficult this would be to spec, I don't know.

**Comment by scottaohara** [comment]
Would it be possible to have the toggle pop up attribute take priority over a button’s form submission functionality?

that would probably be helpful for situations where an author uses a button element and specifies the togglepopup attribute but fails to specify type=button

**Comment by mfreed7** [comment]
> Would it be possible to have the toggle pop up attribute take priority over a button’s form submission functionality?
> 
> that would probably be helpful for situations where an author uses a button element and specifies the togglepopup attribute but fails to specify type=button

I'm inclined to think we should avoid touching form submission logic. For example, I could see confusion when an otherwise-working form that uses a `type`-less `<button>` to submit, and a developer adds `togglepopup` to that button. Now the button doesn't submit the form. I think I'd prefer, in that case, that the developer make a conscious choice to no longer submit the form, rather than the system silently doing that for them. (I've been bitten by form submission bugs too many times in the past, I think. 😄 )

Given the [resolution](https://github.com/openui/open-ui/issues/409#issuecomment-973176547) and subsequent clarifications on this issue, I'd like to close it as resolved. If you disagree with my above thoughts, perhaps you could open a fresh issue to discuss?
