### ISSUE TITLE
Arrow key up/down on closed <selectmenu>

### ISSUE THREAD

**Issue by dandclark** [openui/open-ui#433]
Another `<selectmenu>` behavior to discuss: what should happen when the control's listbox is closed, and a user arrow keys up/down on the control's button?

Per my testing of `<select>` in Chromium and Gecko on Windows, up/down arrow keys advance backwards/forwards through the list of options without opening the listbox.

However looking at the example at https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html, up/down arrow open the listbox in addition to moving to the next previous option.

> Down Arrow	
> - Moves focus to and selects the next option.
> - If the listbox is collapsed, also expands the list.
> 
> Up Arrow	
> - Moves focus to and selects the previous option.
> - If the listbox is collapsed, also expands the list.

The guidance in https://www.w3.org/TR/wai-aria-practices/#listbox_kbd_interaction doesn't state that up/down arrow should open the listbox.

> Down Arrow: Moves focus to the next option. Optionally, in a single-select listbox, selection may also move with focus.
> Up Arrow: Moves focus to the previous option. Optionally, in a single-select listbox, selection may also move with focus.

So I'm not clear on whether the best practice is to open the listbox or not when up/down arrow is pressed. Thoughts?

(Thanks @mfreed7 for pointing this out).

**Comment by scottaohara** [comment]
I'm glad you opened this @dandclark, as I was reading through #386 and noticed this hadn't been mentioned yet.

The APG isn't going to be what can be looked at here for the definitive behavior since the `select` behaves differently depending on the platform, and the APG pattern takes a bit of both, though leaning a bit more towards macOS behavior.  On macOS, the listbox always popsup when using the <kbd>up</kbd> or <kbd>down</kbd> arrow keys.  Firefox on macOS allows for <kbd>left</kbd> and <kbd>right</kbd> arrows to cycle through the select's options when in the collapsed state.  Safari and Chromium don't seem to behave that way, though.

On Windows, the expectation is that <kbd>up</kbd>, <kbd>down</kbd>, <kbd>left</kbd> and <kbd>right</kbd> will cycle through the select element's options without opening the listbox (firefox, chrome, edge).  To open the listbox with arrow keys, someone would also need to use the <kbd>alt</kbd> key, along with <kbd>up</kbd> or <kbd>down</kbd> to get the listbox to popup.

Per the discussion the other day about #429, these differences in the listbox popping up or not matter a bit less since the `change` event will fire the same either way.  

I'd imagine that preference for behavior may be contingent on people's familiarity with their primary OS.

**Comment by josepharhar** [comment]
https://w3c.github.io/aria-practices/#combobox-keyboard-interaction says a few things about up and down:

> Down Arrow: If the popup is available, moves focus into the popup:
> * If the autocomplete behavior automatically selected a suggestion before Down Arrow was pressed, focus is placed on the suggestion following the automatically selected suggestion.
> * Otherwise, places focus on the first focusable element in the popup.
> 
> Up Arrow (Optional): If the popup is available, places focus on the last focusable element in the popup.

I don't understand what it means by "if the popup is available" though. Does that mean if the popup listbox is showing? Does it have something to do with the combobox being editable? Is it about the autocomplete suggestion rather than the actual listbox? I'm going to assume it means what the example does:

[The example](https://w3c.github.io/aria-practices/examples/combobox/combobox-select-only.html) opens the listbox popup when pressing up or down, and it doesn't change the option at all. I'm a little hesitant to do this since it doesn't seem to be the same as what `<select>` does on most platforms, but if that's whats best for users then I guess we ought to go for it. Based on [the resolution here](https://github.com/openui/open-ui/issues/386#issuecomment-916336828), it sounds like we already have consensus to just follow these aria authoring practices.

I also just noticed that there is no recommendation for right or left arrow keys in the aria authoring practices... maybe those should cycle the selected option without opening the listbox like Scott mentioned in his last comment?

**Comment by josepharhar** [comment]
I tested out the behavior on various platforms and browsers:

- Up and Left choose the previous option, Down and Right choose the next option. The listbox is not opened.
  - Windows Chrome
  - Windows Firefox
  - Linux Chrome
  - Linux Firefox
- The listbox is opened. The selected option is focused but not moved forwards/backwards. Left and Right do nothing.
  - MacOS Chrome
  - MacOS Safari
  - MacOS Firefox

As scott mentioned, the behavior is platform specific and not browser specific, and users may expect it to act the way the existing select element does on their OS.

As I mentioned in my last comment, the ARIA practices seem to suggest doing the MacOS behavior but with an added funny behavior where pressing down opens the listbox and selects the last option.

My proposed resolution is to do the same thing that the existing select element does and change the behavior based on the OS because that is most likely to be what the user expects, but I am open to suggestions.

**Comment by josepharhar** [comment]
We resolved to make up, down, left, and right open the listbox without changing the selected option.

**Comment by aphillips** [comment]
This issue got mirrored to I18N's repo due to the `i18n-tracker` label and I dug around to find the reason for the tag in the IRC log above:

> <hdv> [ gregwhitworth to create an issue for appearance native and for native cycle capability ]
> <dbaron> BTW, I think the left/right doing the same as up/down means vertical writing modes all work isn't great -- I think it either (a) gets vertical CJK languages wrong or (b) assumes we'll never add support for vertical-lr scripts like Mongolian, Manchu, etc.
> <jarhar> Proposed resolution: Up, down, left, and right open the listbox without changing the selected option
> <bkardell_> dbaron: why?
> <hdv> gregwhitworth: **let's at the i18n label so that the horizontal i18n group at W3C can look at it**
> <hdv> s/at/add
> <dbaron> bkardell_, for vertical Japanese/Chinese, I'd expect the first item in a select to be at the right and the later items to move left, whereas for Mongolian or Manchu script, I'd expect the reverse
> <bkardell_> ah I get what you mean now... I don't think up down and left right as synonomous is affected by that though, is it?
> <dbaron> bkardell, I think it depends what the up/down/left/right behavior is
> <dbaron> bkardell_, if it's all "open the select" it's fine, if it's about moving between items then there may be issues
> <hdv> masonf: important to note it is 'resolved for now' we will likely look at it again
> <hdv> gregwhitworth: exactly
> <bkardell_> ⬆️ ⬇️ : ⬅️ : ➡️

Just to confirm, arrow keys can signal either logical or physical movement, depending on context. Physical movement means "left is left and right is right (etc.)" regardless of text directionality or writing mode. Logical movement means that "left is towards the start (in an LTR context) vs. right is towards the start (in an RTL context)". Physical vs. logical movement depends on the operation in question. 

List navigation should generally be logical rather than physical, with up being towards the start and down being towards the end. Left is "towards start" for LTR (`dir=ltr`) and `vertical-lr` modes and "towards end" for RTL (`dir=rtl`) and `vertical-rl` modes (with right mirroring the behavior).

Since you resolved to open the select (and not navigate), is there an equivalent issue somewhere about navigation? I don't see a reason here to reopen this issue.

**Comment by scottaohara** [comment]
since i could make the call, just commenting to clarify that while I had mentioned that people may have preferences, that for this topic that wasn't meant to indicate that I wouldn't also agree that cross-browser/platform consistency.

i actually think this is a good change.  

however, because I"m me, i also wanted to respond to:
>I wonder what existing web frameworks do, when they build custom components?

looking to design systems to mimic how they've implemented custom components like this would often mean a bunch of behaviors from the native equivalent were dropped.  e.g., was left/right selection not implemented because of a purposeful choice, or because it wasn't ever thought about since the requirements were written by someone unfamiliar with the variations.  Or, was it deemed too complex to implement?  That often happens with custom select-only comboboxes in regards to the type ahead functionality.  Most instances i come across don't allow for the quick jump to an option by pressing the first few characters of that option's label.  For instance, neither Fluent UI or Salesforce comboboxes allow for this if using the select-only combobox.  They also don't allow someone to click on their custom labels to move focus to the associated combobox element.  That's not a dig on these, or anyone who worked on them.  it's not "required" that they do these things.  But they are missing features from what the current select element provide (or from what other custom made components may or may not provide).  

So, very long way of saying "yes, let's look at what other design systems are doing. BUT ALSO, let's look at what they didn't do compared to what they were trying to recreate. What did they leave out, and if something hit the cutting room floor, why?"

**Comment by mfreed7** [comment]
> So, very long way of saying "yes, let's look at what other design systems are doing. BUT ALSO, let's look at what they didn't do compared to what they were trying to recreate. What did they leave out, and if something hit the cutting room floor, why?"

Totally agree! I just wanted to make sure we weren't limiting our research to native select menus. Really, I think everyone in this week's meeting seemed to agree that the right way to pick the "right" behavior was to consider what's best for users, and do that. As I said at the end of the meeting, I'm quite sure this issue isn't closed, it's just "closed for now". Please add your thoughts on what's best and we'll keep discussing.
