### ISSUE TITLE
Adding docs for controls to the site

### ISSUE THREAD

**Issue by captainbrosset** [openui/open-ui#438]
A new native control is being implemented in Chromium based on the open-ui `select` proposal. Its name is `selectmenu` and it can already be used in Chromium-based browsers (not sure of the version yet, better stick to Canary for now if you want to try), with the `Experimental Web Platform features` flag enabled.

I'm filing this issue to propose writing some technical documentation about `selectmenu` (and others when they become available) in order for early testers to try it out and provide feedback.

While it's way too soon for the control to be production ready and have docs on MDN and so on, it is far enough along that it'd be good for a few early testers to build demos with it and report limitations with the design, and bugs with the implementation.
These early testers can only do so effectively if they have access to documentation about the control (its anatomy, how to use `::part()`, how to extend the markup, etc.).

This documentation needs to be separate from the spec I think, and it could be listed as a new table of content node under "Documentation" on the site.

I drafted some docs on a branch here: https://github.com/captainbrosset/open-ui/blob/selectmenu-docs/research/src/pages/prototypes/selectmenu.mdx

Pinging @dandclark @ststimac and @gregwhitworth who I've discussed this with.

**Comment by gregwhitworth** [comment]
Thank you for filing the issue, I greatly appreciate it. One thing that I was thinking about is the goal of this documentation and whether we should have a consistent paradigm for new controls. I like your post above because it's effectively showing how the model that Open UI builds on top of works. So I'd like to get a link from the home page to this with something like: "Learn how to use the experimental `<selectmenu>` based on Open UI today".

I don't know how I feel about another menu section. We've already gotten feedback that we're confusing folks with duplicate entries. For now I think I'd like it to be a part of the `<select>` specification that denotes the difference between the implementation spec and the person using the component. Maybe we actually just place this at the end of the spec with a large heading, "How to use this component"?

Then there is the other question of this may conflict with MDN. Since we plan to have this be a part of the web platform I think our docs should follow the same pattern as our specs and be prepared to land where web developers expect them; which is MDN.

**Comment by captainbrosset** [comment]
> So I'd like to get a link from the home page to this with something like: "Learn how to use the experimental `<selectmenu>` based on Open UI today".

That sounds good to me. I can try that on my branch, and see how this works.

> I don't know how I feel about another menu section. We've already gotten feedback that we're confusing folks with duplicate entries.

Ah, I see. Yeah I can understand how this would be confusing.

> For now I think I'd like it to be a part of the `<select>` specification that denotes the difference between the implementation spec and the person using the component. Maybe we actually just place this at the end of the spec with a large heading, "How to use this component"?

Indeed, grouping all select-related resources under the same <select> table of content node would make a lot of sense. For now, I'll apply your suggestion of having it be linked from the bottom of the spec.

> Then there is the other question of this may conflict with MDN. Since we plan to have this be a part of the web platform I think our docs should follow the same pattern as our specs and be prepared to land where web developers expect them; which is MDN.

Agreed, long term, this should go to MDN, and follow the same structure as other docs there. For now though, I think we need to target early testers only, and therefore make this more like a quick tutorial, rather than a ref doc. What do you think?
