### ISSUE TITLE
[Select] Vertical align positioning

### ISSUE THREAD

**Issue by atomiks** [openui/open-ui#482]
New here, but I recently went on a deep dive recreating the native macOS `<select>` using CSS/JS: https://twitter.com/atomiksdev/status/1501847263102246916

In the current demo when opening the menu it won't limit its height at the top: 

<img width="973" alt="Screen Shot 2022-03-13 at 3 10 45 pm" src="https://user-images.githubusercontent.com/22450188/158044698-ae0b8c91-2c5c-4274-aa7d-a4fedba323d4.png">

In my custom solution there was a lot of work with:

- Limiting `max-height` and allowing it to expand `onWheel`
- Syncing `.scrollTop` with how much it got limited in that direction

Is this possible with the `<selectmenu>` implementation?

**Comment by josepharhar** [comment]
Do you want the listbox popover to move to stay completely on screen instead of having it be able to scroll out of view?
Do you want the listbox to shrink to fit the available space in between its original bottom and the top of the screen?
I'm having a hard time getting the button of a native macos select to be scrolled out of view while the listbox is open because I can't scroll the page while the listbox is open.

**Comment by josepharhar** [comment]
closing due to lack of feedback
