### ISSUE TITLE
<selectmenu> always snaps shut when opened with mouse

### ISSUE THREAD

**Issue by oluoluoxenfree** [openui/open-ui#483]
Hi,

The openui selectmenu is being tried out in our site in this PR: https://github.com/dvdherron/oddleventy/pull/1 in Chrome canary

We've been unable to get the dropdown to stay open when navigating it it using a mouse: it immediately snaps shut before you're able to click any of the other options.

From my colleague @dvdherron: "The element is setup just like other demos I've seen online and I've tried changing the placement of the "selected-value" attribute but that doesn't seem to prevent the menu from closing on clicks either."

We have a deploy preview here: https://deploy-preview-1--frosty-pike-798e73.netlify.app/ 

You can access the selectmenu under the light/dark button at the top.

**Comment by dandclark** [comment]
This is an interesting case, thanks @oluoluoxenfree for trying out `<selectmenu>` and reporting the issue.

What's happening here is that the `<selectmenu>` is inside a `<form>` element, and the `<button>` element that the site provides to the `<selectmenu>` is causing the `<form>` to submit when it's clicked. That refreshes the page. If you look closely you can see the whole page flash as it refreshes when the `<selectmenu>`'s button is clicked.

This submit behavior with `<button>` is strange but is a longstanding part of the web platform (independent of `<selectmenu>`); per https://html.spec.whatwg.org/multipage/form-elements.html#attr-button-type,  the default type of `<button>` is `submit`. This has caused some confusion over the years, e.g. see this [relevant stackoverflow](https://stackoverflow.com/questions/2825856/html-button-to-not-submit-form).

One way to work around this is by adding the `type="button"` attribute to the `<button>` element so that it doesn't submit the form. I tried this out via DevTools and with that change, the site works as expected.

We could eliminate this issue for `<selectmenu>` by specifying that elements in the flat tree subtree of a `<selectmenu>` do not have any form association. That could eliminate other strange corner cases where an element has both form association and `<selectmenu>` controller code applied.

**Comment by gregwhitworth** [comment]
@dandclark I removed the agenda label - please re-apply it when you're prepared to discuss this again

**Comment by dandclark** [comment]
I think we should try again to reach a resolution on this.

The form association behavior in the spec has some quirks; see the [form element pointer](https://html.spec.whatwg.org/multipage/parsing.html#form-element-pointer) and how it's used to set form [association](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#concept-form-association). It's probably a risky move to try to make changes to this, and would add complexity to behavior that's already confusing.

Also, this isn't limited to `<selectmenu>`. Any custom element that takes slotted content will be affected in the same way, where the slotted content may be unexpectedly associated with a `<form>` in the light DOM. So, while this behavior may be kind of surprising, I'm not sure that we need a specific fix for `<selectmenu>`.
