### ISSUE TITLE
[popup] More crisply define the interactions between `popup=popup`, `popup=hint`, and `popup=async`

### ISSUE THREAD

**Issue by mfreed7** [openui/open-ui#525]
The explainer has [a section dedicated to the behaviors](https://github.com/openui/open-ui/blob/main/research/src/pages/popup/popup.research.explainer.mdx#classes-of-ui---dismiss-behavior-and-interactions) of each of these popup types, but there are some gaps:

1. Should "nested" `popup=hint` (tooltips) be allowed, in the same way that `popup=popup` is allowed to nest? It seems like tooltips and other `popup=hint` UI should really be constrained to be **exactly** "one at a time", with nested tooltips prohibited. But are there use cases for tooltips nested within tooltips?
2. Should `popup=popup` be allowed to "nest" inside tooltips? Again here, it seems like the answer should be no, but perhaps there are use cases?
3. When a tooltip is shown while there are open popups, and then the topmost popup is hidden (either with light dismiss or via `hidePopup()`), should the tooltip be hidden also? It seems like "yes", but what do UI folks think?
4. How should `initiallyopen` (maybe [renamed](https://github.com/openui/open-ui/issues/500) to `defaultopen` soon) behave when there are all three popup types. It would seem that only the first occurence of either `<div popup=popup initiallyopen>` **or** `<div popup=hint initiallyopen>` should be shown upon page load. It would also seem that an unlimited number of `<div popup=async initiallyopen>` should be auto-shown on load, independent of `popup=popup` or `popup=hint`.

I have [a CL](https://chromium-review.googlesource.com/c/chromium/src/+/3606540) up to implement my best guesses at the above questions, so perhaps an easy way to get answers is for folks to wait for that to land in a Chromium Canary and test it out. But thoughts appreciated.

**Comment by scottaohara** [comment]
1. nested tooltips shouldn't be allowed.  Generally if someone is in a position where they might need something like that, then it's very likely that the initial tooltip popup should be a different type of popup, so that a user can directly enter/interact with the content (and thus be able to invoke the second tooltip popup).
2. again no, because a tooltip should not be receiving focus / contain any interactive elements.  if someone has a need for their popup to receive focus / contain sub-popups, then they should use the default popup behavior.
3. from what i gather here i also think yes?  but maybe it'll be more clear once i see a demo of the use case?
4. Agreed on `async`.  Agreed that only the first instance of `popup=popup` should be respected.  Seriously wondering if a hint should even be allowed to be open by default?  

Since a hint/tooltip would otherwise only be revealed on hover/focus of the element it describes, and auto-dismiss when someone hovered or moved focus away from the invoking element, wouldn't having it open by default result in an immediate closure once someone starting moving keyboard focus or moving their mouse?  What if an element was set to have its tooltip opened by default, but it wasn't the first element on the page that had an associated tooltip popup.  Someone navigating the page sequentially with keyboard would come to that other element first, its tooltip popup would be invoked, and then would that not close the initially opened tooltip popup?  (yes the same would happen for a standard popup - but only if the user specifically invoked another element's popup, rather than passively invoking a hint popup merely by hover/focus).  If others don't agree and think there's a use case for a hint to be exposed by default, I'd really like to hear those use cases.  I'm just stuck on the awkwardness of it / how the behavior of its displaying (auto-dismiss on mouseout) would change compared to other initially opened popups.

**Comment by mfreed7** [comment]
@scottaohara thanks for the very helpful input!

> 4. Agreed on `async`.  Agreed that only the first instance of `popup=popup` should be respected.  Seriously wondering if a hint should even be allowed to be open by default?
> 
> Since a hint/tooltip would otherwise only be revealed on hover/focus of the element it describes, and auto-dismiss when someone hovered or moved focus away from the invoking element, wouldn't having it open by default result in an immediate closure once someone starting moving keyboard focus or moving their mouse?

This is a great point, and I think I agree with you. Perhaps only `<div popup=popup>` and `<div popup=async>` should be allowed to use `defaultopen` ([renamed](https://github.com/openui/open-ui/issues/500) from `initiallyopen`). This also raises other points about how `popup=hint` works, and I've opened https://github.com/openui/open-ui/issues/526 to discuss that further.

**Comment by mfreed7** [comment]
Ok, so in the meeting today, I took an action item to more-crisply define the proposed behavior. This comment is that definition.

-----

First, some terminology:
- I'll use "default popup" to mean an element with `popup=popup` (or its [replacement value](https://github.com/openui/open-ui/issues/491#issuecomment-1117526245)).
- I'll use the word "tooltip" to mean an element with `popup=hint`.
- I'll use the word "toast" to mean an element with `popup=async`.
- I'll use the word "popup" to mean a default popup, a tooltip, or a toast.
- I'll use "triggering element" to mean a supported activatable element (e.g. a button) containing one of these content attributes: `togglepopup`, `showpopup`, or `hidepopup`, and "target" to mean the popup with `id` matching the value of the triggering attribute.
- I'll use the verb "show" to mean either calling `.showPopup()` on a popup, or showing the popup via activating a triggering element.
- I'll use the word "open" to mean a popup that has been shown.
- For a given open popup (call it P), an "ancestral" popup is another open popup (call it A) where any of the following is true:
    1. A is a DOM ancestor of P.
    2. P has an `anchor` attribute whose value is equal to A's `id` or any descendent of A's `id`.*
    3. A has a descendent triggering element whose target is P.

<span>*</span> [See this issue](https://github.com/openui/open-ui/issues/493#issuecomment-1119085158) for a discussion generally about whether `anchor` should form an ancestral relationship.

Ok. Now, the proposed behavior:

1. If a tooltip is shown, it should hide **any** other open tooltips, including ancestral tooltips. (**"You can't nest tooltips".**)
2. If a default popup is shown, it should hide **any** open tooltips, including if the tooltip is an ancestral popup of the default popup. (**"You can't nest a popup inside a tooltip".**)
3. If you: **a)** show a default popup (call it D), then **b)** show an **ancestral** tooltip of D (call it T) , then **c)** hide D, the tooltip T should be hidden. (**"A tooltip can be nested inside a popup."**)
4. If you: **a)** show a default popup (call it D), then **b)** show an **non-ancestral** tooltip (call it T) , then **c)** hide D, the tooltip T should be left showing. (**"Non-nested tooltips can stay open when unrelated popups are hidden."**)
5. The `defaultopen` attribute should have no effect on tooltips. I.e. this attribute cannot be used to cause a tooltip to be shown upon page load.
6. The `defaultopen` attribute can be used on as many toasts as desired, and all of them will be shown upon page load.
7. Only the first default popup (in DOM order) containing the `defaultopen` attribute will be shown upon page load. (This is per-explainer, and included here for completeness.) 


-----


Clearly I need to fold a lot of this into the explainer, which needs work. But are there thoughts about the above? Objections?

**Comment by mfreed7** [comment]
> there may need to be an exception for tooltips to always be on top.
> 
> thinking a menu popup which has a menuitem that both invokes a tooltip/submenu, where the submenu could be positioned atop the tooltip and then the descriptive information would be obscured

@scottaohara So at first I thought this was a good idea. But on reflection, I think it might not matter. Given the [resolution](https://github.com/openui/open-ui/issues/525#issuecomment-1125293226) to adopt [these rules](https://github.com/openui/open-ui/issues/525#issuecomment-1119093412), there can only be one `popup=hint` displayed on a page at a time, and it must be the last-opened popup on the page. I.e. if you have a `popup=popup` displayed, and then you display a `popup=hint`, it'll be topmost. If you then open another `popup=popup`, that will close the`popup=hint`. So I don't think we need a special exception to make sure tooltips are on top, I think that's the only place they can be within the [rules](https://github.com/openui/open-ui/issues/525#issuecomment-1119093412). But maybe I missed a way for this to happen?

**Comment by mfreed7** [comment]
Based on the resolution, I'm going to close this issue.

**Comment by scottaohara** [comment]
@mfreed7, makes sense.  if an unwanted situation actually comes up in reality, we can always discuss then

**Comment by mfreed7** [comment]
> @mfreed7, makes sense. if an unwanted situation actually comes up in reality, we can always discuss then

Awesome, thanks!
