### ISSUE TITLE
The popup attribute should allow the empty string value

### ISSUE THREAD

**Issue by domenic** [openui/open-ui#533]
I had an offline discussion with @mfreed7 regarding invalid, empty, and missing values which I wanted to relay here. Summary: **I think `popup` (or, equivalently, `popup=""`) should be allowed and should be equivalent to `popup=popup`. This does not cause forward-compat issues and makes the API more pleasant.**

As background, remember that in HTML, `attribute` is the same as `attribute=""`. There's nothing special about an attribute with no equal sign; it's just a shorthand for setting the attribute's value to the empty string. In particular there's no special booleanness vs. stringness for attributes; attribute values are strings, if the attribute is present at all. (Some parts of the spec will _interpret_ certain attributes as booleans, by saying any string value, including the empty string, is treated as "true", and a missing attribute is treated as "false".)

Also as background, the `popup` attribute is slated to be an [enumerated attribute](https://html.spec.whatwg.org/#enumerated-attribute). These have _states_ and _keywords_. _Keywords_ are the developer-facing API, and are the strings that appear inside the attribute value. _States_ are the underlying model.

It looks like you have the following states: _no-popup_, _popup_, _hint_, and _async_. (Some or all of these might be renamed per #491 and #532, but I'll use these names for now.)

Then the question is how to map attribute presence/values to those states. It seems like there's broad agreement on the following:

- ASCII case-insensitive match for `hint` will map to the _hint_ state
- ASCII case-insensitive match for `async` will map to the _async_ state
- Missing attribute will map to the _no-popup_ state. (In spec terms, this is the [missing value default](https://html.spec.whatwg.org/#missing-value-default).)
- Garbage value (e.g. `foo`) will map to the _no-popup_ state, for forward compatibility. (In spec terms, this is the [invalid value default](https://html.spec.whatwg.org/#invalid-value-default).)

The question is what values should map to the _popup_ state. **I think the empty string should map to that state.** That gives a nice DX, where the default behavior is expressed with just `<div popup>`. It has many precedents in other enumerated attributes: `crossorigin`, `translate`, `hidden`, `contenteditable`, and `spellcheck` are all cases where the empty string maps to some sort of "default useful state", and that default useful state is different than the missing value default.

Separately, **you probably want an explicit non-empty string keyword to also map to the _popup_ state**. Let's call it `popup`, although per #491 both the state and keyword will probably be renamed.

There is another option, which is to just have the empty string be the only keyword mapping to the _popup_ state. In that case the bikeshedding in #491 becomes much less urgent because the state name is a spec-internal concept and not part of the web developer-exposed interface. But all the example attributes I listed above have a non-empty string keyword as well as the empty string, and it's probably good to stay consistent.

**Comment by mfreed7** [comment]
Thanks for opening this issue @domenic. After listening to your arguments, I think I agree that it sounds like a good option to make `<div popup>` mean the "standard" popup, equivalent to [`<div popup={#491}>`](https://github.com/openui/open-ui/issues/491). There were some concerns expressed over something like `myPopup.popup=true` not working, but I think those are probably outweighed by the convenience of the shorthand.

One question: if we go this route, and recalling our [resolution](https://github.com/openui/open-ui/issues/491#issuecomment-1118927375) to only IDL-reflect valid values, what should this return?

```javascript
myPopup.popup = 'invalid value';
myPopup.popup; //  ??? 
```

It would seem "bad" to return the empty string, since that would round trip unfortunately:

```javascript
myPopup.popup = 'invalid value';
myPopup.popup = myPopup.popup;
myPopup.popup;  //  'popup' (or whatever #491 decides)
```

It seems like `null` or `undefined` would be appropriate, but thoughts appreciated.

**Comment by domenic** [comment]
For [reflection](https://html.spec.whatwg.org/#reflecting-content-attributes-in-idl-attributes), you have two choices in the current spec:

- [DOMString](https://webidl.spec.whatwg.org/#idl-DOMString) attribute whose content attribute is an [enumerated attribute](https://html.spec.whatwg.org/#enumerated-attribute), and the IDL attribute is limited to only known values
- nullable [DOMString](https://webidl.spec.whatwg.org/#idl-DOMString) attribute whose content attribute is an [enumerated attribute](https://html.spec.whatwg.org/#enumerated-attribute)

The former seems like it would work well if you added a keyword for the _no-popup_ state (e.g., `popup=none`). The latter seems like it would work well if you'd prefer not to do that.

We could also explore adding new reflection variations, but I'm not sure that'd be necessary.

**Comment by mfreed7** [comment]
> The former seems like it would work well if you added a keyword for the _no-popup_ state (e.g., `popup=none`).

I think this makes the most sense to me. There'll need to be an enum value ([there already is in Chromium](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/dom/element.h;l=161;drc=0376c8b974eed9fd09017758bce0cee4ec087baa)) that means "none", so let's expose it directly.

I'm going to add this to the Agenda for next week, since we just [resolved](https://github.com/openui/open-ui/issues/491#issuecomment-1132078846) to rename the main case to `popup=auto`. I'd like to get this one resolved also, so we can be done changing the `popup` attribute.

**Proposed resolution**: For the `popup` attribute, an empty string (`""`) value should map to `popup=auto`. Also add a specific attribute value, `popup=none`, which behaves identically to when the `popup` attribute is missing completely.

Any objections?

**Comment by zcorpan** [comment]
There's a third choice

* nullable DOMString attribute whose content attribute is an enumerated attribute, and the IDL attribute is limited to only known values

[crossOrigin](https://html.spec.whatwg.org/multipage/semantics.html#attr-link-crossorigin) has this setup, and also has the empty string being a state that's different from the *missing value default*.

Limited to only known values is good for feature-testing, so IMO it's a choice between having `none` as a synonym to missing attribute and the IDL return `none`, or no synonym and the IDL returns null.

Returning null for the no-popup state and non-empty strings for the other states allows for truthy/falsy checks in JS, which seems a bit nicer in terms of developer ergonomics.

**Comment by domenic** [comment]
Simon, I can't find that in the reflection section for some reason... Is crossOrigin just not well specified? Otherwise, yeah, that does seem a bit nicer.

**Comment by mfreed7** [comment]
> There's a third choice
> 
> * nullable DOMString attribute whose content attribute is an enumerated attribute, and the IDL attribute is limited to only known values
> 
> [crossOrigin](https://html.spec.whatwg.org/multipage/semantics.html#dom-link-crossorigin) has this setup, and also has the empty string being a state that's different from the _missing value default_.
> 
> [Limited to only known values](https://html.spec.whatwg.org/multipage/common-dom-interfaces.html#limited-to-only-known-values) is good for feature-testing, so IMO it's a choice between having `none` as a synonym to missing attribute and the IDL return `none`, or no synonym and the IDL returns null.
> 
> Returning null for the no-popup state and non-empty strings for the other states allows for truthy/falsy checks in JS, which seems a bit nicer in terms of developer ergonomics.

Ohh I like the third choice. I do agree returning `null` is nicer for truthy/falsy checks. Given that's a possibility, here's a new proposed resolution:

**Proposed resolution:** For the `popup` attribute, an empty string (`""`) value should map to `popup=auto`. The IDL will be limited to only known values, meaning it will return `null` for both *invalid* content attribute values and when the `popup` attribute is missing entirely. Do **not** add a specific attribute value meaning "no popup", e.g. `popup=none`.

**Comment by mfreed7** [comment]
> > If a reflecting IDL attribute is a nullable [DOMString](https://webidl.spec.whatwg.org/#idl-DOMString) attribute whose content attribute is an [enumerated attribute](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#enumerated-attribute), then, on getting, if the corresponding content attribute is in its missing value default state then the IDL attribute must return null, otherwise, the IDL attribute must return the keyword value associated with the state the attribute is in. If there are multiple keyword values for the state, then return the conforming one. If there are multiple conforming keyword values, then one will be designated the [canonical keyword](https://html.spec.whatwg.org/multipage/common-dom-interfaces.html#canonical-keyword); choose that one. On setting, if the new value is null, the content attribute must be removed, and otherwise, the content attribute must be set to the specified new value.
> 
> but indeed it seems like there's a spec bug since `crossOrigin` is defined to be "limited to only known values" but also nullable.

I, perhaps incorrectly, assumed there was an implied "and the IDL attribute is limited to only known values" in that paragraph.

In non-spec language, here are my assumptions about what we want:

| HTML | IDL | 
 | ------ | ------ | 
 | `<div popup=auto>` | `div.popup === 'auto'` | 
 | `<div popup=AuTo>` | `div.popup === 'auto'` | 
 | `<div popup=hint>` | `div.popup === 'hint'` | 
 | `<div popup=async>` | `div.popup === 'async'` | 
 | `<div popup>` | `div.popup === 'auto'` | 
 | `<div popup="">` | `div.popup === 'auto'` | 
 | `<div>` | `div.popup === null` | 
 | `<div popup=foobar>` | `div.popup === null` | 
 | `<div popup=true>` | `div.popup === null` | 
 | `<div popup=none>` | `div.popup === null` | 
 | `<div popup="     auto     "` | `div.popup === null` |

**Comment by mfreed7** [comment]
Would this look like the right WebIDL for the above table?

```webidl
[Unscopable, CEReactions, Reflect, ReflectOnly=("auto","hint","async"), ReflectEmpty="auto"] attribute DOMString? popup;
```

There's no way to use `ReflectMissing` or `ReflectInvalid` since we want them to be `null`, not a string. Right?

**Comment by zcorpan** [comment]
The table looks right to me.

As for the WebIDL, `Reflect` and `Reflect*` are non-standard chromium extensions I believe.

The current spec text for reflecting nullable enumerated attributes says to return `null` for the missing value default state, but we also want to return null for the invalid value default state, so the definition needs some massaging to allow for that.

**Comment by mfreed7** [comment]
> As for the WebIDL, `Reflect` and `Reflect*` are non-standard chromium extensions I believe.

Right, of course. Thanks.

> The current spec text for reflecting nullable enumerated attributes says to return `null` for the missing value default state, but we also want to return null for the invalid value default state, so the definition needs some massaging to allow for that.

Is that something that seems easy to add to the spec? @domenic thoughts?

**Comment by domenic** [comment]
Yeah, it's easy to add, and in fact something we need to do because currently the spec for `crossOrigin` is broken. I plan to do that sometime this week.

**Comment by domenic** [comment]
So I tried to work on a spec edit here and it appears crossOrigin is already working OK. Basically it appears nullable DOMString enumerated attributes are always implicitly "limited to known values". Whenever you are in the missing value default state, then you get back `null`. So if you want to get back `null` for invalid values too, then just make sure your invalid value default is equal to your missing value default. (That is _not_ what `crossOrigin` does.)

So for the table above I think you want the following spec:

- Enumerated attribute
- `DOMString?`
- invalid value default = missing value default = no-popup state
- No explicit keyword for the no-popup state

**Comment by mfreed7** [comment]
Great, thanks!

**Comment by emilio** [comment]
FWIW, I don't have permission to reopen, but it seems a bit more consistent to me to treat invalid popup values (like `popup="blah"`) to be still a popup (just like the `type=""` attribute in `<input>`), probably with the default behavior of `popup=""`?

It seems a bit of a better default, specially if we implement new popup types in the future? `<div popup="fancy">` will not show up at all on the versions of the browser that support the new attribute, but will be a regular element (or fixed-pos block as per #561), which seems really unfortunate / a pretty bad failure mode?

**Comment by mfreed7** [comment]
> It seems a bit of a better default, specially if we implement new popup types in the future? `<div popup="fancy">` will not show up at all on the versions of the browser that support the new attribute, but will be a regular element (or fixed-pos block as per #561), which seems really unfortunate / a pretty bad failure mode?

So the point of the existing behavior is forward compatibility, generally. The thing that worries me about making `<div popup=foobar>` behave like `<div popup>` is what happens if later we actually add `popup=foobar` as a supported value, with different behaviors? This will break the site, and if the breakage is large enough, we won't actually be able to ship `popup=foobar`.

Can I ask the flip-side question? Why do you want to support `<div popup=foobar>`? What's the use case?

**Comment by emilio** [comment]
> So the point of the existing behavior is forward compatibility, generally. The thing that worries me about making `<div popup=foobar>` behave like `<div popup>` is what happens if later we actually add `popup=foobar` as a supported value, with different behaviors? This will break the site, and if the breakage is large enough, we won't actually be able to ship `popup=foobar`.

Just to clarify, your concern is (let's call this "scenario A"):

 * Site uses `popup=foobar` _before it is supported_.
 * Site gets `popup=""` behavior and carries on, because it works.
 * We want `foobar` to do something else.
 * Suddenly `popup=foobar` behaves differently, in a way significant enough. The site breaks.

Is that right? If I got that right, let's consider two other scenarios.

Scenario B:

 * Sit uses `popup=foobar` _before it is supported_.
 * Site gets the proposed "no popup" behavior and carries on, the div is just regular content, or a fixed-pos div.
 * We want `foobar` to do something else.
 * Suddenly `popup=foobar` becomes a popup, and gets hidden, with no code to show it in the site. The site breaks.

Scenario C:

 * Site _doesn't use_ `popup=foobar`.
 * We want `foobar` to do something else.
 * Site starts using `popup=foobar`, but developer doesn't test in old versions of browsers (or other browsers that don't support `popup=foobar` yet).
 * Suddenly, in users of other or older browsers, page has a visible popup out of the blue, that users have no way of hiding without devtools.

Scenario B and C seem a bit worse to me that scenario A. In the (unlikely) case of A happening, we have alternatives (easiest one being "choose another string that's not in-use"), while B and C seem a bit less in our control, and worse for users.

> Can I ask the flip-side question? Why do you want to support `<div popup=foobar>`? What's the use case?

Preventing scenario B and C, basically, which I think are worse than scenario A. But it might be the case that there's another scenario that I'm not considering.

I think there's value in consistently hiding all elements with `[popup]` by default (due to the popup behavior). That seems better, to incrementally hiding them as we add new values, which makes adding values not so trivial.

How bad B/C are depends a bit on how we expect authors to style popups. If we expect authors to effectively do:

```
[popup]:not(:top-layer) {
  display: none;
}

[popup]:top-layer {
  display: block; ...
}
```

Then the concerns are a bit less, I think (but then again, maybe we should put that in a UA sheet). When discussing https://github.com/openui/open-ui/issues/561, it was my assumption that authors would just style the element regularly:

```css
#mypopup {
  display: flex;
  ....
}
```

And what would take care of controlling the visibility of the popup would be something along the lines of:

```css
[popup]:-internal-popup-hidden { display: none !important }
```

in the user-agent sheet. But I see that's not the case (there's no `!important` there), so... how do you envision the styling for authors that want to style their popups with e.g. `display: flex`? Along the lines of what I wrote above (`:not(:top-layer)`)? Something else?

**Comment by mfreed7** [comment]
You make some good points. I had been more worried about Scenario A, since it seems more likely to me. I.e. a developer who reads about the `popup` attribute, doesn't read the values, and just picks something that sounds right. If it happens to work, they keep it and move on. I suppose Scenario B (developer has never heard about the `popup` attribute, and uses it for their own purposes) is also possible. And Scenario C is a concern also, which I hadn't thought about.

I'm ok with making the Invalid Value Default equal to "auto", meaning `popup=foobar` behaves the same as `popup=auto`. In that case, feature detection is still possible, but slightly modified:

```javascript
function supportsPopUpType(type) {
  const div = document.createElement('div');
  div.popUp = type;
  return div.popUp === type.toLowerCase();
}
```

Not as easy as a null check, but not terrible. This would also mean we could go back to a non-nullable DOMString for the `.popUp` attribute. @domenic, thoughts/objections?

Your other point about the missing `!important` is interesting. I did that on purpose, back when animations were troublesome, to make it easier to animate to/from the hidden state. I didn't think about this side effect that you cannot set `display:{not-none}` without also then having to do your own management of showing vs. hiding. Now that [animations are handled](https://github.com/openui/open-ui/issues/335), I'm inclined to say we should add back the `!important` to the `display:none` rule. (I'll comment on https://github.com/openui/open-ui/issues/561 to point to this conversation.)

**Comment by domenic** [comment]
That change makes sense to me. I wonder about the Invalid Value Default choice of manual vs. auto? Manual seems like maybe a better fallback behavior for "we didn't understand what you asked for", but that's just my first impression; I didn't analyze all of scenario A/B/C for each choice.

**Comment by mfreed7** [comment]
> That change makes sense to me. I wonder about the Invalid Value Default choice of manual vs. auto? Manual seems like maybe a better fallback behavior for "we didn't understand what you asked for", but that's just my first impression; I didn't analyze all of scenario A/B/C for each choice.

Hmm, I tend to agree with this. I originally said we should default to `popup=auto` but I think that's just because that's the default for plain `popup` with no value. This is different, as you said, "we didn't understand". In that case, `popup=manual` confers just the basic pop-up behaviors (hidden by default, responds to `.showPopUp`, etc.) without all of the interactions with other pop-ups (via one-at-a-time behavior, etc.). That seems not only more correct in some sense, but likely also the safest for forward compat.

**Comment by mfreed7** [comment]
Seems like we might already be close to consensus. I'll put this on the agenda for next week.

**Comment by tbondwilkinson** [comment]
+1 to `popup="manual"` for cases where the attribute is unclear.

**Comment by scottaohara** [comment]
+1 to this as well.  my only concern was that if `manual` would be the expected default behavior... but if someone is putting unsupported values into the attribute and they don't get the behavior they're expecting.... well... this will be a signal to them to check their values?

**Comment by mfreed7** [comment]
> +1 to this as well. my only concern was that if `manual` would be the expected default behavior... but if someone is putting unsupported values into the attribute and they don't get the behavior they're expecting.... well... this will be a signal to them to check their values?

Right. I like `manual` for two reasons:
 1. It is the "minimal" set of pop-up behavior. For an invalid value, it seems like we should do the minimum.
 2. It feels like the most likely value to cause developers to realize that the pop-up isn't behaving as they expect, since it doesn't light dismiss or dismiss other pop-ups.
