### ISSUE TITLE
[popup] Top layer pseudo class questions

### ISSUE THREAD

**Issue by mfreed7** [openui/open-ui#557]
In https://github.com/openui/open-ui/issues/470 we [resolved](https://github.com/openui/open-ui/issues/470#issuecomment-1138868669) to **a)** have a pseudo class that matches when a pop-up is in the top layer, and **b)** call it `:top-layer`.

I [raised this issue](https://github.com/w3c/csswg-drafts/issues/7319) with the CSSWG, and several points were made:

1. While a pop-up is animating show/hide, it will be in the top layer, but needs to **not** match some pseudo class, so that transitions can be triggered from that pseudo class. (See [this description of pop-up animation behavior](https://github.com/openui/open-ui/issues/335#issuecomment-1168951980).) This might mean we need an additional pseudo class for the transitional state, which would likely be very specific to pop-up.
2. There was some discomfort (likely akin to the discussions on [#470](https://github.com/openui/open-ui/issues/470)) with using "top layer" as a name, since it isn't a term web developers are accustomed to using. However, it is the [name chosen by the spec](https://fullscreen.spec.whatwg.org/#top-layer) to describe it, so...?
3. Another [suggestion was made](https://github.com/w3c/csswg-drafts/issues/7319#issuecomment-1168531437) by @bramus to use a pseudo **element** instead of a pseudo **class**. The idea is a `::top-layer` element on the `<html>` element only, which can be used to select things in the top layer:

```css
::top-layer [popup]) {
  /* any pop-up that is in the top-layer */
}
:nth-last-child(1 of ::top-layer [popup]) {
  /* only the topmost pop-up in the top-layer */
}
```

General thoughts?

**Comment by mfreed7** [comment]
In particular, I should have mentioned, the CSSWG would like us (OpenUI) to discuss the `::top-layer` pseudo element approach, and bring our feedback back to CSSWG.

Agenda+ to do that, at least.

**Comment by futekov** [comment]
I feel like `:topmost` or similar is non-scalable in the long term - it's like having `:first-child` but no `:nth-child()`. Even if we cannot think of a use case for selecting the other popup layers this doesn't mean that developers won't find one.

A stacking selector like the tree-structural `nth-child` but for layers (similar to the [stacking idea](https://twitter.com/VictorGutt/status/1527770596871921669) by @[VicGUTT](https://github.com/VicGUTT)) would be in the spirit of existing CSS conventions. Maybe something with an index to allow for a flexible selection of the top (or any other) layer:
- `:nth-layer-top(1)` or `:nth-top-layer(1)`, because `:nth-layer(1)` seems confusing on whether it's the first created (bottom) or the topmost
- `:popup-top(1)`
- `:nth-top-popup(1)`

**Comment by mfreed7** [comment]
Since https://github.com/w3c/csswg-drafts/issues/7319 is on the agenda in CSSWG, I'm going to just close this issue and let it get resolved there instead of here.

**Comment by mfreed7** [comment]
CSSWG [just resolved](https://github.com/w3c/csswg-drafts/issues/7319#issuecomment-1225988203) to add `:open` for "things that are open". That would clearly apply to pop-up, assuming any reasonable definition for "open". As such, I'm going to update the explainer to use `:open` everywhere it currently uses `:top-layer`.
