### ISSUE TITLE
Selecting based on user changing values

### ISSUE THREAD

**Issue by astearns** [openui/open-ui#568]
The CSSWG is discussing adding a pseudo-class (or pseudo-classes) to let authors select and apply styling to an input where the user has changed its value.

https://github.com/w3c/csswg-drafts/issues/1533

I searched this repo and did not see this discussed here yet, but I may have missed if this is a duplicate.

Please take a look at the discussion in our issue and post there if you have opinions on how many of these pseudo-classes could be needed, and ideas on how to define when they match.

**Comment by SebastianZ** [comment]
As noted in [my comment in the CSSWG issue](https://github.com/w3c/csswg-drafts/issues/1533#issuecomment-1184810731), there are still some unresolved details. The main questions are

1. When exactly should such a pseudo-class match?
2. Should there be a way to unmatch it?
3. If there's a way to unmatch it, when should that happen?

I believe we can cover all use cases with a single pseudo-class. Though let's see what we come up with.

Note that HTML has the concept of a [dirty flag for inputs](https://html.spec.whatwg.org/#concept-fe-dirty) and text areas as well as for [select options](https://html.spec.whatwg.org/#concept-option-dirtiness). That flag basically indicates when the value has changed from its default value. It doesn't matter whether the user or some code caused that change.

Though I believe the pseudo-class should _only_ match on user interactions that directly result in a changed value. E.g. writing something into a text input field, changing the option of a select box, toggling a checkbox or radio button, selecting a date in a date popup, dragging the thumb of a slider, etc.

And there should be a way to reset the state of the form element so that the pseudo-class doesn't match anymore. This is important for single page applications or when a form is reset, among other things. So basically, if the value is set programmatically, the pseudo-class should _not_ match (anymore).

Sebastian
