### ISSUE TITLE
Initiate - Design to code

### ISSUE THREAD

**Issue by levirtevs** [openui/open-ui#605]

**Comment by levirtevs** [comment]
https://github.com/babel/babel/discussions/14910
https://github.com/webpack/webpack/issues/16226

**Comment by levirtevs** [comment]
https://github.com/babel/babel/discussions/14910

**Comment by tinydogio-joshua** [comment]
It appears the linked discussion was deleted.

**Comment by levirtevs** [comment]
Hello, I tagged those projects thinking that they will be interested. Looks like they aren't.

**Comment by tinydogio-joshua** [comment]
Fair enough. 😀

**Comment by levirtevs** [comment]
**Design to code philosophy** 

- A component is a rectangle
- A component can have content. Content can be image, text, and other component
- A component can show or hide its content
- A component have different states - Each state is visually distinct from one another. In UX terms, this is called variants.
- A parent component can pass state to child component.
- A child component can pass state or data to parent component.

**Comment by gregwhitworth** [comment]
Hey @levirtevs thanks for opening the issue; what is your overall goal/proposal here? Since you raised the potential of discussing this on a call I think it's important to understand that the issues need to be a prepared state for resolution on the call. If you're wanting to present a potential new proposal then it needs to first come with an explainer and the key goal of what you are hoping to achieve.

This issue regarding a measure element is a good one to follow: https://github.com/openui/open-ui/issues/499#issuecomment-1076568070

Even if your subject matter is not about a new element we still need to ensure that there is a concrete action you're wanting from the group. Let us know if you have any questions as we're more than happy to help.

**Comment by levirtevs** [comment]
hello @gregwhitworth  thanks for your response and sharing a reference material to present 

**What is the problem you're wanting to solve (don't lead with solutions)**
Web development is time consuming. Coding is time consuming. Frameworks are coming with their own cool tricks which doesn't address web problem. In addition to this, converting a design to code has been a challenging in the web mostly because there is no single standard that is a handshake between UX and UI. 


**Outline the current way in which web developers currently try to solve the problem**
Sit with UX, try to understand their thought process on why they thought a current solution addresses user problem. They exchange design specifications and developer code it up.

**What is your recommended solution**
Design a.k.a UX is the single source of truth for web development, Set standard for Design architecture for component. 
Document the specification (attached an illustration above)
Provide a concept that can help to create designs and generate code targeting frameworks. 

**What other solutions did you consider**
Plugins in designers tool

**Open Questions**
TBD or anyone can add it.

**Comment by bkardell** [comment]
This has not had much interaction, and I don't believe there is a concrete action item that we've taken up.  I'm going to close this, but feel free to re-open if you feel that's wrong, )and let me know why if you can)
