### ISSUE TITLE
[popup] Naming for `show` and `hide` events

### ISSUE THREAD

**Issue by josepharhar** [openui/open-ui#607]
@domenic pointed out here that the `show` and `hide` event names may be too generic: https://github.com/whatwg/html/pull/8221#discussion_r965617087
> I feel bad using the generic event names "show" and "hide" for something pop-up specific? Like, if I do el.hidden = true, I would expect this to fire a hide event.

I couldn't find any discussion about these event names in the list of issues at the [bottom of the explainer](https://open-ui.org/components/popup.research.explainer#design-decisions). Does anyone know how we decided on these names? Does anyone have any thoughts?

**Comment by Kaiido** [comment]
That also struck me when reading the PR at whatwg/html. I believe it's particularily surprising since this event is also available on `window`. Reading `window.onshow = (evt) => {...` one would probably expect it to refer to the `pageshow` event rather than a popup in the document.

If I can start the bikeshedding, I guess `popupshow` and `popuphide` would be quite simple and clearer.

**Comment by mfreed7** [comment]
The counterpoint, I guess, might be that if later there are other non-pop-up things that show and hide, it'd be nice to re-use an easy set of events like `show` and `hide`.

If we indeed need to rename these, then `popupshow` and `popuphide` seem the most obvious and straightforward.

**Comment by domenic** [comment]
> other non-pop-up things that show and hide

Well, I think `<div>`s show and hide pretty frequently already, when you e.g. change them from `display: none` to `display: block`...

**Comment by mfreed7** [comment]
> > other non-pop-up things that show and hide
> 
> Well, I think `<div>`s show and hide pretty frequently already, when you e.g. change them from `display: none` to `display: block`...

Then lots of `show`/`hide` events! Just kidding. Probably best to go with `popupshow` and `popuphide`. I don't see any other downsides, and it does make the context more clear.

Any objections?

**Comment by mfreed7** [comment]
I filed an issue with WHATWG/dom, since this is now a more general feature.

https://github.com/whatwg/dom/issues/1118

**Comment by mfreed7** [comment]
I'm bringing this back due to [conversation on the html issue](https://github.com/whatwg/html/issues/8386#issuecomment-1307665110). I'm beginning to think we should just add `popovershow` and `popoverhide`, and not add more general events. They don't seem useful, upon further thought.

**Comment by mfreed7** [comment]
One thought I had was to perhaps combine these two events into a single `popover` event:

```javascript
popover.addEventListener('popover',() => {
  if (popover.matches(':closed')) {
    // This is a "show" event, because the popover
    // is going from :closed to :open
  } else {
    // This is a "hide" event, because the popover
    // is going from :open to :closed
  }
});
```

It takes more work to write the event handler, and it might be a bit confusing that the "show" event is detected by looking for `:closed` (because the event is fired before the state changes). Even more confusing (and perhaps worth a tweak to the [hide animation sequence](https://open-ui.org/components/popup.research.explainer#animation-of-pop-ups)) is that for the "hide" event, neither `:open` nor `:closed` will match. The code I wrote above will work correctly, but if written the other way (looking for `:open`) it won't work.

But people seem to like short, easy to remember names, and `popover` is definitely that. The behavior is roughly equivalent to [the `toggle` event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDetailsElement/toggle_event) for the `<details>` element.

Thoughts?

**Comment by domenic** [comment]
I like that direction. I think it will be less work for some use cases, e.g. event handlers that mainly want to sync the state change with some other part of the page and thus would have to listen to both events anyway.

Could we reuse the `toggle` event name? I guess we'd have to figure out what happens for `<details popover>` though. It'd be nice if we could make it work, but not sure it's worth it... Another option is `popovertoggle` as the event name.

To make writing such handlers easier, it might be worth considering adding an IDL attribute, e.g. `popover.popoverOpen` (or `popoverState` as an enum if it should be tri-state).

**Comment by scottaohara** [comment]
yah... though this has been humming along as a global attribute, I'd highly question why someone would even try to do `<details popover>`.  Seems it [doesn't even work correctly right now](https://codepen.io/scottohara/pen/PoapGvp), as with the popover attribute it is still visually rendered even if it hasn't been invoked - but even if it did, someone would need a button to invoke the popup, which if not in the open state by default, would then require someone to then toggle open the content they just toggled open?  that's some weird behavior... but arguably less weird than what can happen if `contenteditable` is put on the details element.

**Comment by mfreed7** [comment]
> yah... though this has been humming along as a global attribute, I'd highly question why someone would even try to do `<details popover>`. Seems it [doesn't even work correctly right now](https://codepen.io/scottohara/pen/PoapGvp), as with the popover attribute it is still visually rendered even if it hasn't been invoked 

This seems to be triggered by normalize.css containing this rule:

```css
menu, article, aside, details, footer, header, nav, section {
    display: block;
}
```

> but even if it did, someone would need a button to invoke the popup, which if not in the open state by default, would then require someone to then toggle open the content they just toggled open? that's some weird behavior... but arguably less weird than what can happen if `contenteditable` is put on the details element.

Well, you could do `<details popover open>` to have it start out open? I think the rest would still work though, right? I.e. when the `<details>` is shown (via `.showPopover()`), it'll still function as a normal details, where the user can toggle it. I hate ruling out elements, but if you think this is just too confusing, perhaps we could make `<details popover>` a disallowed element. It would be the only one at this point.

> I like that direction. I think it will be less work for some use cases, e.g. event handlers that mainly want to sync the state change with some other part of the page and thus would have to listen to both events anyway.

True, but I'd guess most common use cases need to know hide vs. show.

> Could we reuse the `toggle` event name? I guess we'd have to figure out what happens for `<details popover>` though. It'd be nice if we could make it work, but not sure it's worth it... Another option is `popovertoggle` as the event name.

Given the above, I do like "toggle" as an event name that we can re-use!


> To make writing such handlers easier, it might be worth considering adding an IDL attribute, e.g. `popover.popoverOpen` (or `popoverState` as an enum if it should be tri-state).

This has been [brought up before](https://github.com/openui/open-ui/issues/610), and this shape of the event might push even more for something like `popover.popoverOpen`. On the tri-state question, the third state would just be when `popover` isn't a popover (doesn't have the `popover` attribute). We could make it a nullable boolean? Or just return `false` in that case?

**Comment by domenic** [comment]
> On the tri-state question, the third state would just be when `popover` isn't a popover (doesn't have the `popover` attribute). We could make it a nullable boolean? Or just return `false` in that case?

I thought there was some third state while it was doing the animation, where neither `:open` nor `:closed` matches?

**Comment by mfreed7** [comment]
> > On the tri-state question, the third state would just be when `popover` isn't a popover (doesn't have the `popover` attribute). We could make it a nullable boolean? Or just return `false` in that case?
> 
> I thought there was some third state while it was doing the animation, where neither `:open` nor `:closed` matches?

Yeah, I was thinking `popoverOpen` would be just sugar for `popover.matches(':open')`, but you're right it would be more powerful to expose the full three states.

Perhaps instead of `popoverOpen`, we go with `popoverState`, with the following (nullable) enumerated values:
 1. "open"  === `matches(':open')`
 2. "closed" === `matches(':closed')`
 3. "transitioning"  === `!matches(':open') && !matches(':closed')`
 4. null  (when element doesn't have `popover` attribute)

**Comment by domenic** [comment]
That would make sense to me. Although, coming back to the event, I wonder if it will have expected values when the event fires? E.g. maybe it will always equal "transitioning" during that time, which would not be so useful?

**Comment by mfreed7** [comment]
> That would make sense to me. Although, coming back to the event, I wonder if it will have expected values when the event fires? E.g. maybe it will always equal "transitioning" during that time, which would not be so useful?

Yeah, I worried about that also. For the "show" transition, given the order of operations, the `popoverState` will still be `"closed"`, so that's ok. As currently spec'd and implemented, during the "hide" transition, the event is fired just *after* the `popoverState` changes to `"transitioning"`, which is unfortunate. But looking at the logic, I'm thinking we could/should reverse that, so that the state would still be `"open"` at that point. Then things here would be fairly clean, right?

**Comment by domenic** [comment]
Yeah, that sounds right. Although I guess all this complexity further convinces me that we should solve this without popover being a weird tri-state thing, as I communicated in https://github.com/whatwg/html/issues/7785#issuecomment-1317884823

**Comment by mfreed7** [comment]
> Yeah, that sounds right. Although I guess all this complexity further convinces me that we should solve this without popover being a weird tri-state thing, as I communicated in [whatwg/html#7785 (comment)](https://github.com/whatwg/html/issues/7785#issuecomment-1317884823)

See my response https://github.com/whatwg/html/issues/7785#issuecomment-1317926256 and maybe let's not have the conversation both places. But I don't think you can avoid a tri-state thing, when there is a "hidden" state, a "showing" state, and some other state while you're animating. No matter what the API looks like, and no matter if it's Popover or dialog.

**Comment by mfreed7** [comment]
Thanks all!
