### ISSUE TITLE
[popup] Boolean property for show state

### ISSUE THREAD

**Issue by 0kku** [openui/open-ui#610]
Is there a reason why there's no mention (that I can find) of a writable property for the "shown" state of a popup?

For example, it could look something like this:

```js
popup.popUpShown // false
popup.showPopUp();
popup.popUpShown // true
popup.popUpShown = false;
popup.popUpShown // false
```
Or alternatively, it could be called `popUpOpen`.

I realize that one can check if a popup is being shown using `popUp.matches(":open")` as described in the explainer. However, this does not allow assigning a boolean value for the state. This would be helpful in a framework setting:

```js
function MyComponent () {
  const shown = state(false);
  
  return html`
    <div popUp="auto" popUpShown=${shown} />
  `;
}
```

While, from what I understand, the current API would require one to write cumbersome code like this: 
```js
function MyComponent () {
  const shown = state(false);
  const popup = ref();
  
  if (shown && !popUp.matches(":open")) popup.showPopUp();
  else if (!shown && popUp.matches(":open")) popup.hidePopUp();
  
  return html`
    <div popUp="auto" ref=${popup} />
  `;
}
```
This would be less cumbersome if there was a toggle method that takes an argument for forcing the state similar to APIs like `element.toggleAttribute()`, `classList.toggle()`, etc. (which also doesn't seem to be present), though it would still be less ergonomic than having the proposed property: 
```js
function MyComponent () {
  const shown = state(false);
  const popup = ref();
  
  popup.togglePopUp(shown);
  
  return html`
    <div popUp="auto" ref=${popup} />
  `;
}
```

**Comment by tbondwilkinson** [comment]
I think the "toggle" API isn't a bad idea, perhaps you should open a separate issue for that case specifically?

I don't think I like the idea of a shown attribute controlling whether a popup is shown or not, and if it did exist it should be readonly rather than controlling behavior. I like having things that "do" things as methods, and things that are "observable" as properties.

**Comment by 0kku** [comment]
Can you elaborate on why a writable property would be undesirable? It seems like it would be idiomatic and in-line with other DOM API properties like `disabled`, `checked`, `indeterminate`, `required`, etc. on input elements for example. 

It seems like a settable property controlling its state would be vital for its adoption in contexts where a frontend UI framework that relies on setting properties is used. Without it, people would be left with having to create their own abstractions on top of the native element for each framework; as with the property missing, people would be unable to write templates declaratively, and would instead be forced to figure out a way to call a function in an imperative way. As demonstrated above, that makes for considerably less legible code.

**Comment by tbondwilkinson** [comment]
But it's inconsistent with other UI elements, like [showModal](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/showModal), read the [note in the spec](https://html.spec.whatwg.org/multipage/interactive-elements.html#note-dialog-remove-open-attribute) about removing the "open" attribute, since the attribute is now readonly.

Because events, animations, etc. might all be triggered by a close or open mutation, those mutations should in my opinion be best represented as a method, rather than a property.

The difference between a browser native that does show/hide and something like a web framework is that (taking React as an example), `setState` is not a synchronous call to mutate an observable DOM node. `setState` schedules a data mutation and performs a `render()` using that new data. React, and other web frameworks, use data mutations as the basis for rendering.

The vanilla web as currently written does no such thing, there is no "data" model that you can mutate to cause the browser to do a (batched) re-rendering of the DOM. When in React you're reading the "isOpen" property of your data model, that's different than reading properties directly from the underlying DOM node itself.

If there were a way to link data Objects with DOM Objects, I agree that it would be pretty reasonable to have a data property map to "open."

**Comment by mfreed7** [comment]
+100 to avoiding a writable attribute that "does" things, not just because of the arguments above, but because there are myriad corner cases. E.g. what happens when the element is not connected to a document (and so, can't be shown), but you do `popUp.shown=true`?

Assuming we don't do that, and just have a readable value, then I suppose this is just sugar over `popUp.matches(':open')`. I agree that's a bit cumbersome to type, but you could always write a helper function or something. But I'm not against adding it, if there's strong desire. We already have pushback on the number of attributes and properties being added for this API.

The suggestion to add `popUp.togglePopUp()` is interesting. Along the same lines as above, it's an ergonomic helper. However, I suppose I'd hope most such usage instead uses the `popuptoggletarget` attribute, to make sure e.g. a11y is correctly set up.

I'll agenda+ this to discuss.

**Comment by bkardell** [comment]
without commenting on more, I like the idea of adding a toggle for parity with some similar things in the platform already even
