### ISSUE TITLE
[popup] return focus to triggering element if dismissing popup

### ISSUE THREAD

**Issue by scottaohara** [openui/open-ui#612]
When closing a popup with the `popuphidetarget` attribute or via the <kbd>Esc</kbd> key, I noticed that presently focus is 'lost'.  

A general expectation here though is that if a popup / dialog is closed by use of a dismissal button or the <kbd>Esc</kbd> key, that focus should return to the invoking element, if it is available in the DOM.

So per the following example:

```
<button id=w popupshowtarget=d>Invoke the dialog!</button>
<dialog popup id=d anchor=w>
  <h2>Heyo</h2>
  <p>...</p>
  <button popuphidetarget=d autofocus>Get me outa here</button>
</dialog>
```

I would expect that activating the button to hide the popup, or pressing the <kbd>Esc</kbd> key would return focus to the "invoke the dialog!" button.

If that button were to no longer exist in the DOM, e.g., the popup contained a control to perform a "delete" action and by activating it the invoking button and the content it was deleting were removed from the page, then I'd not necessarily expect anything had to receive focus, but it'd be ideal if keyboard focus picked back up where the invoking element "was" in the DOM.

So per the following:
```
<!-- stuff the following button is associated with -->
<button id=a popupshowtarget=m>Actions</button>
...

<button>A</button>
<!-- oodles of other content and focusable elements -->

<!-- popup is down here for no particularly good reason -->
<div role=menu popup id=m anchor=a>
  <button role=menuitem>action 1</button>
  <button role=menuitem>action 2</button>
  <button popuphidetarget=m>Delete</button>
</div>

<button>B</button>
```

Ideally if delete was chosen and the content no longer existed in the DOM, pressing the tab key SHOULD move someone to button A (directly following the 'actions' button that would no longer be present).  Currently though, hitting <kbd>tab</kbd> would move someone to button B due to where the popup was positioned in the DOM (as would happen if <kbd>esc</kbd> was pressed) - and that's quite far away from where the user previously was.  

cc @aleventhal and @mfreed7

**Comment by mfreed7** [comment]
> So per the following example:
> 
> ```
> <button id=w popupshowtarget=d>Invoke the dialog!</button>
> <dialog popup id=d anchor=w>
>   <h2>Heyo</h2>
>   <p>...</p>
>   <button popuphidetarget=d autofocus>Get me outa here</button>
> </dialog>
> ```

This surprised me - I would have expected this example to "just work" as you expected. Focus should return to the "Invoke" button when you activate the "Get me outa here" button. [I'll look into the implementation](https://crbug.com/1371629) and spec to see what's missing...


 
> If that button were to no longer exist in the DOM, e.g., the popup contained a control to perform a "delete" action and by activating it the invoking button and the content it was deleting were removed from the page, then I'd not necessarily expect anything had to receive focus, but it'd be ideal if keyboard focus picked back up where the invoking element "was" in the DOM.

This is a bit of a different question. So if I understand you here, in addition to the provided code, the click handler on the "Delete" button would remove the "Actions" button from the DOM? So that when the pop-up is hidden (via the fixed `popuphidetarget` behavior from above), the "previously focused element" doesn't exist in the DOM. As-is, focus will return to the `<body>` in this case. I think you're suggesting that in this case, the [sequential focus navigation starting point](https://html.spec.whatwg.org/multipage/interaction.html#sequential-focus-navigation-starting-point) be set to the "hole" in the DOM where the "Actions" button would have been? I believe, per spec, that's up to the UA. But it certainly sounds reasonable to me. I believe this same behavior/issue applies to the `<dialog>` element, correct? Perhaps a more general WHATWG issue should be opened for this?

**Comment by scottaohara** [comment]
>So if I understand you here, in addition to the provided code, the click handler on the "Delete" button would remove the "Actions" button from the DOM?

yes. as i'm sure you're aware, a very common use case for a listing of items, or an action consistent within multiple rows of a table/grid UI.

>think you're suggesting that in this case, the [sequential focus navigation starting point](https://html.spec.whatwg.org/multipage/interaction.html#sequential-focus-navigation-starting-point) be set to the "hole" in the DOM where the "Actions" button would have been?

also yes.

>Perhaps a more general WHATWG issue should be opened for this?

I've created https://codepen.io/scottohara/pen/GRdXNEw to demonstrate and generally explain the issue.  If you think this does a good job getting the point across, then I can create an issue against HTML for this topic

**Comment by mfreed7** [comment]
> I've created https://codepen.io/scottohara/pen/GRdXNEw to demonstrate and generally explain the issue. If you think this does a good job getting the point across, then I can create an issue against HTML for this topic

Nice demo and explanation. (I recommend `<details open>` so it's visible on load.)

I'd say that's perfect, and I appreciate that your demo uses `<dialog>` rather than `popup`. I do think this issue applies to both, but it'll be easier to discuss in the context of `<dialog>`. +1 from me to open an issue for this, and thanks!

**Comment by mfreed7** [comment]
Ok, so I believe this issue is two things:
 1. [This Chromium bug](https://crbug.com/1371629), which might or might not still be an issue. Let's handle that as a bug - if anyone is able to reproduce that one in a recent Chromium Canary, please comment on the bug and we'll debug together.
 2. [This more general WHATWG issue](https://github.com/whatwg/html/issues/8367) that relates to both popover and `<dialog>`. Let's discuss over on that issue.

Given the above, I'm going to close this issue.
