### ISSUE TITLE
Tracking issue for bringing back `popover=hint` and hover-triggering behavior

### ISSUE THREAD

**Issue by mfreed7** [openui/open-ui#617]
On https://github.com/openui/open-ui/issues/526#issuecomment-1219845155 we decided to hold off on specifying the "hover triggering" behaviors, and the `popuphovertarget` attribute. But without that feature, it has been suggested that it will be more difficult to make `popup=hint` accessible, due to the lack of context about the triggering element.

Should we similarly punt the entire `popup=hint` part of this feature to V2, to be designed and shipped together with `popuphovertarget`?

One downside is that folks trying to build "hinty" things with the pop-up API will probably turn to `popup=auto` instead, which will likely make a11y worse for a while.

@scottaohara @aleventhal

**Comment by mfreed7** [comment]
Also-related issue with `popup=hint`: https://github.com/openui/open-ui/issues/530

**Comment by Westbrook** [comment]
That lack of `hint` is really troubling when ideating on an early consumption of this API within the context of [Spectrum Web Components](https://opensource.adobe.com/spectrum-web-components/index.html).

While the hover stuff is interesting, the biggest loss is:

- When opened, force-closes only other hints, but leaves all other popup types open.

This is a large part of what makes the `popover` API really expand the Top Layer Ecosystem beyond what's possible with `<dialog>.showModal()`. With `<dialog>` you loose the ability to interact with page behind the Top Layer content, while `:open`, which is correct for that case, but it was `popover="hint"` that added that back when leveraging `popover="auto|manual"`. Not having this leads to having to maintain an awkward user space overlay stack that will need to take into account whether `popover` is available or not AND how to manage "fake hints". My current pass at this is to make what would have been `hint` popovers be `manual` and then care for their stack separately. In this context, it's again not the hover stuff that makes it interesting but the removal of:

- Dismisses on [close signal](https://wicg.github.io/close-watcher/#close-signal), click outside, or when the anchor element loses focus.

Having to remake all of this functionality puts me back in the use space overlay business in a way that makes me question the benefits of moving to `popover` at a scale that could tilt that hand of late implementing browsers. 

### Alternatives while missing
My initial thought was to make it `popover="manual"` to start and then switch to `popover="auto"` when open, which would get much closer to the `popover="hint"` approach. However, changing the value of `popover` seems to close the popover in the current Chrome Canary implementation. Has there been discussion as to how changes should be managed, or is this something that is fully intended? There is some benefit to this in our use cases as there are application tutorials where we _DO_ want to have more than one "hint" available at a time. A switching approach would allow for opening as many as we want, but still getting them to close on outside `click`. This context would lead me to question whether specification like "when the anchor element loses focus" could be replaced with "when something that is not the anchor element (or within the popover) gains focus"?

There's also a path by which `hint` is separated from "hover" all together, as `hint` is really a concept of the "popover stack" and "hover" is a concept of the triggering interaction. In this way, we could leverage some of the discussion around `popover="transient"` or similar to give a popover the characteristics of `hint` on the popover stack while not binding specific triggering interactions. Then in the v2 proposals `hint` or similar can be reintroduced in the [triggering API or similar](https://github.com/openui/open-ui/issues/526).

**Comment by mfreed7** [comment]
Thanks for the comments and for looking deeply into Popover! Can you clarify one thing for me: you said this was the most important thing lost with `popover=hint`:

> When opened, force-closes only other hints, but leaves all other popup types open.

From that concern, it would seem that you are perhaps **only** concerned with making “tooltip” components? If so, could you not just use `popover=auto` for that? The behavior will be identical, as long as there aren’t other component types also using `popover=auto` that you want to leave open. But perhaps that’s exactly the problem you’re describing. Just trying to clarify!

I do really want to see `popover=hint` added back, along with the hover triggering stuff. As soon as we get the main popover feature landed, that’s next on my radar. So I appreciate these comments!

**Comment by Westbrook** [comment]
The reason that this lost is important is the part where "force-closed _only_ other hint" points to a _different_ popover class than the general popover class. One might say a transient popover class. That class does focus on "tooltip" components, but is necessary because there are "non-tooltip" components that deserve to be treated differently than `aria-modal="true"` popover (e.g. `<dialog>`). For illustration, see this UI in Photoshop Web:

<img width="726" alt="image" src="https://user-images.githubusercontent.com/1156657/204284173-1388f5ad-019f-470c-b31c-a5d8024c410e.png">

Here we see a popover that has been opened by clicking a button that features options about the context bar. While this overlay is open, it should not trap tab, as forward/backward tab should take up out of the popover. However, while open, we do want users to be able to active "tooltip" popovers off of other buttons so that they know what to expect from interacting with those buttons and we want them to be able to do so without dismissing the current non-modal popover. The "place image" popover would need the "only other hint" or similar directive within its stack algorithm to achieve this, without continues user space popover management.

So, while "hint" is what has outlined that we receive this capability to date, it is not specifically the interactions that might be implied by hint, but the additional class of overlays with a separate open/close algorithm that I'm wondering about the ability to persist in v1. As I attempted to clarify before, I _think_ this could be mimicked by a combination of `popover="manual"` and user space code, but it feels pretty fragile to combine this special handling with the native APIs and the knowledge that it _may_ be added (though possibly not the same) in the future.

**Comment by mfreed7** [comment]
Cool, thank you very much for the detailed explanation. That is indeed exactly what `popover=hint` is intended to solve, and I'm glad you feel it's an important and useful part of the overall API. This emphasizes the need to work quickly to add the `popover=hint` capability back, by addressing the open issues.

To summarize those in one place:
 - https://github.com/openui/open-ui/issues/526#issuecomment-1219845155 - open questions about the hover-triggering feature
 - https://github.com/openui/open-ui/issues/530 - keyboard access for non-focusable `popover=hint`.
 - Some of the discussion from https://github.com/openui/open-ui/issues/329 was about `popover=hint` (search for "popup=hint") and might need attention from either OpenUI or ARIA.
 - Please (!) let me know if I missed any open `popover=hint` issues.

In the meantime, I agree that if you want this behavior sooner, you'd have to use `popover=manual` and implement **all** of the functionality yourself, which is like a bag of footguns. Perhaps one approach would be to try adding `popover=hint` support back to the [polyfill](https://github.com/oddbird/popover-polyfill), so we can start to see what some solutions might be for the above issues? Once we get the "base" Popover API shipped, I can also put back the Chromium prototype that includes `popover=hint` support as well.

**Comment by mfreed7** [comment]
There is now [an explainer for `popover=hint` and hover triggering](https://open-ui.org/components/popover-hint.research.explainer/). I'm going to close this "tracking issue". Feel free to open fresh issues related to anything in (or not in) the explainer.
