### ISSUE TITLE
[popup] Should we rename popup due to potential developer confusion?

### ISSUE THREAD

**Issue by gregwhitworth** [openui/open-ui#627]
In the WHATWG [issue](https://github.com/whatwg/html/issues/7785), the are some valid concerns raised by @domenic and @annevk around cosistency in naming due to the web platform already having a paradigm that uses the term popup but it means to open a new window. @domenic outlines the potential dev confusion clearly here:

> So indeed, it seems unfortunate if, e.g., sandbox without allow-popups set, still allows popup="" attributes in the sandboxed iframe, due to the fact that popup="" is reusing the term "pop(-)up" for something different than what it's meant in web APIs so far.

So the question to the Open UI CG is whether we want to change the name, if so, to what? I'll readily admit that I'm torn on this as so many component libraries and design systems use this terminology so I don't think that we're necessarily incorrect in the current name, but the potential confusion outline by @domenic and @annevk are valid and should be weighed accordingly.

**Comment by mfreed7** [comment]
Thanks @gregwhitworth for opening this issue. It's unfortunate that at such a late stage, and more than a year after we had our original brainstorming on a name, we need to do it again.

Here's the list of alternative names we brainstormed in the past (from https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/438 and https://github.com/openui/open-ui/issues/296):

- float
- floatable
- popover
- positioned
- overlay
- popout
- popper

My personal favorite is `popover`. It's close to `popup`, it still indicates what "happens" when a pop-up/popover/whatever opens, and it'll be semi-easily found for developers looking for a "pop-up" because it starts with "pop".

Thoughts? I'd like to get this resolved ASAP, as it'll break just about everything (pop-up prototype, selectmenu prototype, blog posts, examples, origin trial code, etc.).

**Comment by Yay295** [comment]
I think "positioned" could be confused with CSS positioning. I think the original idea was that they are related, but since a CSS positioned element is not the same as a "positioned" element I think that could cause confusion.

**Comment by scottaohara** [comment]
from the list provided, popover or popout are my favorites.

of course, if we can get the rights to use poptart, any and all votes i can muster would go to that name.

**Comment by tbondwilkinson** [comment]
I believe all web dev should make me hungry, so poptart is +1

I dislike: float, floatable, positioned for existing CSS reasons and popper for no precedent.

I like overlay best, it also has precedent in [Angular](https://material.angular.io/cdk/overlay/overview) and [Bootstrap](https://getbootstrap.com/docs/5.0/extend/approach/#overlay-components).

I like popover second best. popout is third.

**Comment by hidde** [comment]
I like popover and overlay and agree with @tbondwilkinson re phrases that have existing meanings in CSS.

**Comment by aardrian** [comment]
> from the list provided, popover or popout are my favorites.

Same.

"Overlay" has gained negative connotations in the digital accessibility world owing to bad-actor digital accessibility overlay vendors. So I suggest against it.

Last year [I wrote](https://adrianroselli.com/2021/07/stop-using-pop-up.html) that I have seen the term "popup" used to refer to a dozen different things, so am happy to see it out of the running.

**Comment by mfreed7** [comment]
<img width="376" alt="popover" src="https://user-images.githubusercontent.com/29559695/198085050-2f81975d-022c-46a6-8673-87fd984709d2.png">

Just adding this, since several comments above indicate a desire for the new name to make you hungry. [This recipe](https://cooking.nytimes.com/recipes/1012941-popovers) is my favorite, though I have a few adjustments, so let me know if you want to try it.

------

On a serious note - let's plan to discuss and resolve this tomorrow if at all possible. I've heard positive comments on these:
- popover
- popout
- overlay (though see below)

And some negative comments on these:

- overlay (a11y issues?)
- positioned (confusion with CSS positioning)
- float (confusion with CSS float)
- floatable (maybe confusion with CSS float?)
- popper (conflict with the [JS library](https://popper.js.org/))

**Comment by mfreed7** [comment]
Thank you all. For the record, the final vote looks like 16 votes for `popover`, 2 votes for `pop` (both of which said "could live with `popover`), and no other votes.
