### ISSUE TITLE
SelectMenu multi-select, dismiss or not to dismiss?

### ISSUE THREAD

**Issue by jh3y** [openui/open-ui#638]
I can see this one working either way or people having a preference on a case-by-case basis.

How could a user define that they don't want the popover to close when selecting an option in a SelectMenu? For example, a custom multi-select where the user is likely to select multiple options would require the user to keep opening and closing the listbox. We can't cancel the `popuphide` event to get around this as far as I'm aware either.

The `react-select` version: https://react-select.com/home#custom-styles

cc @mfreed7

**Comment by mfreed7** [comment]
Are there use cases for this other than multi-select? We've [decided](https://github.com/openui/open-ui/issues/531#issuecomment-1145170806) that "v1" of selectmenu will not support multi-select, so it feels like this question just needs to be answered in the context of future multi-select work. But I thought I'd ask.

**Comment by brechtDR** [comment]
Maybe it would be a good idea to add an attribute for listbox in the future. Something like 
`<div popover="" slot="listbox" behavior="listbox" autoclose="auto">`

Maybe it would be an idea to add values such as:

- auto (current/default behaviour)
- manual (when user presses escape button, or clicks outside the box -> could be useful for multiselect)
- false/none (keeps the listbox open when clicked. could see usecases when a certain value has to be selected, and maybe JS could take over when that happened)

Just an idea i thought i might share

**Comment by gregwhitworth** [comment]
> Maybe it would be a good idea to add an attribute for listbox in the future. Something like
> <div popover="" slot="listbox" behavior="listbox" autoclose="auto">

This is akin to solutions we've discussed regarding how filtering should work for the combobox element (we need to land `<selectmenu>` first) where it could do what it does today but then also allow you to enable filtering so options that don't match aren't shown. I think it's a valid approach however I'm concerned about us potentially bloating the API surface so we should be very intentional and ensure that there are valid usecases that are commonly used and warrant the additional tech.

**Comment by josepharhar** [comment]
You can prevent the default behavior of clicking an option causing the listbox to close by calling preventDefault on the click event, I tested it out [here](https://jsfiddle.net/jarhar/3d89pkhx/):
```html
<selectmenu>
  <div popover=auto slot=listbox behavior=listbox>
    listbox
    <option>one</option>
    <option>two</option>
  </div>
</selectmenu>
<script>
const selectmenu = document.querySelector('selectmenu');
document.querySelectorAll('option').forEach(option => {
  option.addEventListener('click', event => {
    event.preventDefault();
    selectmenu.value = option.textContent;
  }, true);
});
</script>
```

You have to use the capture phase because the browser's bubbling phase event listener is registered first, but I could see this not being required if during the HTML spec review they ask us to integrate it into the event dispatching system instead of actually using addEventListener like they asked for popover.

Since I don't see any usecases for non-multiselect, and as Mason mentioned we have moved that to v2, I'm going to change the label from select to select-v2

**Comment by jh3y** [comment]
Nice. I didn't think of catching it on the `option` click 👍  I think partly I was wondering how people would approach this without writing up any scripts but I think that's kinda unavoidable.

This also frees people up to decide how they're going to manage the `selectmenu.value`. Multiselect could be a comma-separated string where the event concatenates and joins the value 🤔

**Comment by josepharhar** [comment]
> Are there use cases for this other than multi-select? We've https://github.com/openui/open-ui/issues/531#issuecomment-1145170806 that "v1" of selectmenu will not support multi-select, so it feels like this question just needs to be answered in the context of future multi-select work. But I thought I'd ask.

I'm not hearing any single-select use cases in this thread, and if someone really wants to do this, they can hack it in with the script example I provided earlier. This is how multi-select will certainly work by default when we go to make that, so I'm not sure what work needs to be done here.
