### ISSUE TITLE
Normalize css vs popover

### ISSUE THREAD

**Issue by scottaohara** [openui/open-ui#650]
Not really sure anything should be done about this here, but wanted to point out that while making codepen examples for popover, i have had to turn off the inclusion of normalize.css due that style sheet's use of `display: block` on HTML elements like `menu`, `article`, and such. 

May be worth a mention in future communication about the attribute that some of these sheets that were made for the purpose of resetting / normalizing HTML elements may actually cause issues with using new web features that these style sheets obviously could never have accounted for.

**Comment by gregwhitworth** [comment]
@scottaohara thanks - yeah I'm not entirely sure what to do with this issue outside of possibly raising it as a concern in the CG so that folks giving talks, etc can make sure to call this out. What specific issues were you hitting?

**Comment by scottaohara** [comment]
@gregwhitworth that the popover was shown by default because normalize was adding display block, per the old 'add display block to all the new html5 elements', to elements with the popover attribute.

**Comment by mfreed7** [comment]
This is a great point! I wonder if someone (OP, hint hint) would be willing to file an issue with the normalize.css folks about this? I guess this applies to any "reset" stylesheet framework, of which there are several.

@jh3y I wonder if you have some visibility into the folks behind those and could reach out? Or at least mention this in a post somewhere?

**Comment by jh3y** [comment]
> This is a great point! I wonder if someone (OP, hint hint) would be willing to file an issue with the normalize.css folks about this? I guess this applies to any "reset" stylesheet framework, of which there are several.
> 
> @jh3y I wonder if you have some visibility into the folks behind those and could reach out? Or at least mention this in a post somewhere?

This is only in places where `popover` isn't supported though, right? Because we have:

```css
[popover]:closed:not(dialog[open]) { display: none; }
```

In the user agent stylesheet which takes precedence over the one before it that would style `display: block`. It's definitely something to be mindful of if there are 3rd party stylesheets that might override this. I have this with `open-props` in some of the demos where I need to do something like:

```css
:where([popover]) {
  margin: auto;
  border-width: initial;
  border-style: solid;
}
```

To reset myself. Can see that in this basic demo: https://codepen.io/web-dot-dev/pen/qBowZXP

**Comment by jh3y** [comment]
Hmm. I have some stylesheets where I've had to put a reset or something in place. 

Perhaps this is something to make more prominent in the article/explainer? I didn't see this behavior with `article`. But, I tried `menu` and sure enough it applied `display: flex`. And ideally, you'd want something like:

```css
menu:not([popover]) { display: flex; }
```

The problem here is that it will be very hard to cater to all cases. That normalize example is a good one though. Perhaps an `aside` about stylesheet resets on the article/explainer wouldn't be a bad idea here. I think we need to update the explainer anyway because of the event changes. I planned on looking at that tomorrow.

**Comment by scottaohara** [comment]
@mfreed7, @jh3y  went to go file that issue today, but realized that at least latest version of normalize css (v8 - released 4 years ago) has removed this style.  Checking codepen (where i encountered this issue) they are using version 5... so, I've sent them an email via their support page to request they update their version of normalize, referencing this issue for more context.

**Comment by mfreed7** [comment]
> The problem here is that it will be very hard to cater to all cases. That normalize example is a good one though. Perhaps an `aside` about stylesheet resets on the article/explainer wouldn't be a bad idea here. I think we need to update the explainer anyway because of the event changes. I planned on looking at that tomorrow.

Thanks!

> @mfreed7, @jh3y went to go file that issue today, but realized that at least latest version of normalize css (v8 - released 4 years ago) has removed this style. Checking codepen (where i encountered this issue) they are using version 5... so, I've sent them an email via their support page to request they update their version of normalize, referencing this issue for more context.

At least that's good news that the potential breakage is more limited than originally thought.

**Comment by scottaohara** [comment]
Yah.  So from what I got back from codepen is that people _can_ change the normalize version if they want.  but it's defaulting to version 5 when it is used.  They're looking into updating that at some point, but they are hesitant to make any changes to existing pens - which makes sense.   Shrug... seems an issue that people may run into if they're unaware (as i was) to this super old version as the default.  But, there is an opt out, so maybe this can just be closed, or at least, this can serve as a reminder for when this eventually comes up?

**Comment by gregwhitworth** [comment]
@scottaohara @mfreed7 @jh3y any reason to keep this issue open?
