### ISSUE TITLE
Inconsistent ordering of anatomy slot and parts

### ISSUE THREAD

**Issue by lukewarlow** [openui/open-ui#743]
What's the correct way to make anatomies. Should slots be inside of parts or vice versa? Or is it dependent on context? 

I ask because currently the various anatomies aren't consistent in this regard

**Comment by gregwhitworth** [comment]
Posted this on discord, and will replicate it here:

This somewhat depends on issue [702](https://github.com/openui/open-ui/issues/702). However, whether it ends up using slots/parts is actually not as important as doing the research to understand the most common usecases and the necessary parts to unlock those. 

Here is a breakdown I did for a potential update to input type=range which when paired with usecases you can arrive at a general recommended anatomy. https://open-ui.org/components/slider.research.parts/

With regards to your specific question however, it depends as the slot is meant to provide flexibility. So you may have nested slots due to being within another part whereas there's another scenario where that isn't necessary.

**Comment by lukewarlow** [comment]
Adding this to the agenda to discuss. There's examples throughout the site that seem backwards to me 

The below being an example of the file structure currently and what I think it should be.

Current:

![image](https://github.com/openui/open-ui/assets/32498324/269c81ef-68d6-4219-a2ca-82990a508cf5)

Proposed:

![image](https://github.com/openui/open-ui/assets/32498324/a030a21f-1609-4d84-89b8-6918fcdb3bad)
