### ISSUE TITLE
[tooltip] Bikeshed the name for a `popovertargetaction` value to hover/focus trigger

### ISSUE THREAD

**Issue by mfreed7** [openui/open-ui#767]
See [this discussion](https://github.com/openui/open-ui/pull/766#discussion_r1223974688), but the current proposal is to do "hover triggering" via a new value for the `popovertargetaction` attribute:

```html
<button popovertarget=foo popovertargetaction=hover>
  Hover me!
</button>
<div popover id=foo> Popover </div>
```

However, "hover" triggering doesn't tell the whole story, since keyboard users need *focus* to trigger the popover, and touch users need *long press* to trigger it. So the question is: what should this value be called?

Here are some ideas I've heard, please feel free to add more:

- `popovertargetaction=hover`
- `popovertargetaction=over`
- `popovertargetaction=active`
- `popovertargetaction=interest`
- {your idea here}

**Comment by brechtDR** [comment]
Some other values that come to mind (not that I think they're better, but just brainstorming):

- focus (as this feels more on focus and hover, at least, feels like it)
- indeterminate
- hint? 
- float
- temp (or temporary)

One thing we might need to take account, is that some devs might want to trigger a popover on toggle for mobile devices and use the hover/focus state on the desktop versions. Although that a focus state kind of feels the same, so I guess that will be good enough for this?

**Comment by kbrilla** [comment]
thumb up for popovertargetaction=interest

Waht more `:interest` pseudo would be great - so it would jump to element that we are activly interacting with - so keybord interaction switching focus would give `:interest` to that element but then mouse move, touch long-press, would move interest to element under mouse, then again mouse keybord interaction would again move `:intrest` to that element.

**Comment by bkardell** [comment]
linking this so you dont have to drill into minutes to find it: https://github.com/whatwg/html/pull/9456

**Comment by mfreed7** [comment]
So quick summary of the discussion above:
- Please read https://github.com/whatwg/html/pull/9456, since it's quite related.
- That talks about a "more general" triggering mechanism for not just popovers, but also dialogs and other things. It is nominally **orthogonal to this issue**, which talks about which word to use to describe "hover or keyboard focus or long press".
- For that last question, the options I've heard are:
    - `popovertargetaction=active`
    - `popovertargetaction=float`
    - `popovertargetaction=focus`
    - `popovertargetaction=hover`
    - `popovertargetaction=indeterminate`
    - `popovertargetaction=interest`
    - `popovertargetaction=over`
    - `popovertargetaction=temp`
    - `popovertargetaction=temporary`

**Comment by keithamus** [comment]
I'll put some opinions down on the proposed options, hopefully useful (and hopefully informative for those just landing on this discussion). The TLDR is, in my humble opinion, that `focus`, `over`, and `interest` are the top candidates:

- `active`: `:active` exists in CSS, and is applied to `<a>` and `<button>`s which are being depressed. As this behaviour is related to interaction, but is quite different from the proposed hint popover behaviour, this could be confusing.
- `float`: `float:` exists in CSS and has a very different meaning. It's popularity is waning in modern CSS (although it was [on 80% of page loads that Chrome saw in the last 24h](https://chromestatus.com/metrics/css/popularity)). Self documenting code is subjective but I'd speculate canvasing developers and asking what `popovertargetaction=float` would do, a minority of the answers would be correct.
- `focus`: `:focus` exists in CSS and is very close to the interaction model for popover hints, to the point where this could be a top choice in my mind. However the interaction models _are_ subtly different which might cause frustration in the community as it sets false expectations. `:focus` won't be applied to elements that are hovered with a mouse but the intent is for a mouse hover to enact a hint popover. False expectations could lead to developer frustration.
- `hover`: `:hover` exists in CSS, so this has the same shape of problems as `:focus`, but worse; `:hover` is applied when a pointer device moves on top of an element, but it excludes touch/keyboard (which the popover=hint proposal does not). Due to the exclusionary nature of `:hover` in CSS, adding `hover` here may carry over the same negative connotations.
- `indeterminate`: This is the longest and most difficult to spell which causes genuine difficulties for folks such as those with dyslexia or those for which English is a second language. It also exists as an attribute for checkboxes to display a checkbox which is neither checked nor unchecked. I'm not sure how the meaning applies to hint popovers.
- `interest`: This has no current precedent in HTML, CSS or JS vernacular which is a nice benefit. It's ambiguous enough to encompass the interaction models without being too ambiguous. Or is it too ambiguous?
- `over`: The word itself has no precedent in HTML or CSS or JSS but it's very close to others - `hover`, `overflow`, `mouseover`. It may cause confusion in that regard. It may be mistaken for a typo of `hover`.
- `temp`/`temporary`: This describes the temporary nature of the hint popover but doesn't hint toward the interaction model. `temp` as a contraction of `temporary` is a slightly odd choice given the attribute name is `popovertargetaction`.

**Comment by mfreed7** [comment]
Ok, please see the very nice summary above. But let's vote:

- 👍 `popovertargetaction=focus`
- 👎 `popovertargetaction=over`
- 😀 `popovertargetaction=interest`
- 🎉  `popovertargetaction=active`
- 😐 `popovertargetaction=indeterminate`
- ♥️ `popovertargetaction=float`
- 🚀 `popovertargetaction=hover`
- 👀 `popovertargetaction=temp/temporary`

Please use the emoji button on Github that relates to the option you'd like to vote. Please vote only once.

**Comment by keithamus** [comment]
(Not to derail but we could use a [poll](https://github.com/openui/open-ui/discussions/new?category=polls))

**Comment by mfreed7** [comment]
> (Not to derail but we could use a [poll](https://github.com/openui/open-ui/discussions/new?category=polls))

Cool! Guess I should have known about that feature. Let’s let this one go as-is since there are already votes. But next time for sure - that’s a lot easier than trying to find the correct “meh” face for the poll.
