### ISSUE TITLE
<select> naming of button and its capabilities

### ISSUE THREAD

**Issue by gregwhitworth** [openui/open-ui#77]
We resolved in the issue #74 to not allow interactive elements within an option. @levithomason asked if this would also be true of the top part, which currently is named <button> which behaves as a button and an expectation of being a native `<button>`. That said, the web platform, due to the same issues as the `<option>` additional interactive elements are not allowed within them. Levi brought up scenarios such as a multi-select that shows the selected options in an input at the top that are clickable to deselect the option.

This is to review whether the current anatomy design would limit this capability or not.

For reference here is the current [anatomy design](https://open-ui.org/components/select#anatomy):

![image](https://user-images.githubusercontent.com/865244/80245392-77308c80-861f-11ea-8532-b40d8d060b2b.png)

Related to https://github.com/WICG/open-ui/issues/73

**Comment by gregwhitworth** [comment]
@una based on our discussions regarding the search capability in place of the button. This is another consideration to change it from simply being a button. At minimum it would need to be a part that is not actually a button element. This should be the issue we use to determine if the button being the default top part or input text should be done and it will answer the next steps for this part of the anatomy.

**Comment by josepharhar** [comment]
We should allow interactive elements to be slotted in to the marker, button, and selected-value slots but not into the default slot where the `<option>`s go, right?

**Comment by NeilWix** [comment]
Wouldn't mixed interaction modes for keyboard users result in
a problematic experience for screen reader users?
Neil Osman
Accessibility engineer @ accessibility team

**Comment by josepharhar** [comment]
There are multi-select and searchable combobox demos here, so I don't think that the current architecture limits these scenarios: https://microsoftedge.github.io/Demos/selectmenu/

I'm adding agenda+ to confirm that the current architecture is sufficient and we can close this issue.

> Wouldn't mixed interaction modes for keyboard users result in a problematic experience for screen reader users?

I don't fully understand... are you saying that if parts of a selectmenu are keyboard focusable then screen reader users won't be able to find them? Which part in particular?

**Comment by NeilWix** [comment]
Exactly. When SR users encounter a combo/list box, their expectations would be to navigate and explore the content with arrow keys only. Placing a tabbable button inside the panel of a listbox/combobox would probably be ignored by SR users

**Comment by mfreed7** [comment]
So we've discussed and resolved the issue of interactive elements within `<options>` (in https://github.com/openui/open-ui/issues/74) and within the listbox (in https://github.com/openui/open-ui/issues/540). This issue seems to be about interactive elements inside the **button**. My thoughts:

 - We obviously need to allow interactive elements to be slotted into the **button** part. It's a button after all.
 - Allowing interactive elements in the **marker** and **selected-value** slots feels broken/odd, since both of those parts are *inside* the button. Per-spec ([here](https://html.spec.whatwg.org/multipage/form-elements.html#the-button-element)), interactive content is not allowed within a button. I think we should not do anything special in these cases, however. We should just do whatever happens today when a developer does `<button><input></button>` for example.
