### ISSUE TITLE
Naming of the selected value element

### ISSUE THREAD

**Issue by josepharhar** [openui/open-ui#808]
In [this explainer PR](https://github.com/openui/open-ui/pull/798), I added `<selectedvalue>` as the new element name which is intended to replace `behavior=selected-value` as per this issue: https://github.com/openui/open-ui/issues/702
The reason I chose `<selectedvalue>` is simply because it matches `behavior=selected-value`.

@lukewarlow pointed out that perhaps if we named it `<value>` it could be used in a wider variety of future use cases: https://github.com/openui/open-ui/pull/798#discussion_r1299176644

Anyone have thoughts about what it should be called?

**Comment by josepharhar** [comment]
@una suggested that `<selectedoption>` would be a good name as well

**Comment by josepharhar** [comment]
Yeah I suppose that `<selectedoptions>` would make more sense than `<selectedoption>` for multi-select.
I'm not actively working on multi-select yet and plan to do that after we get single-select done. The "select-v2" label for issues in this repo contain multi-select issues.

If you have any ideas for a term that would unambiguously be for singular or multiple options, I'm all ears.

**Comment by jp-larose** [comment]
Why is this a tag, and not a property on the `<selectlist>` tag?  It could simply be the `value` property, matching the pattern of other form elements.

**Comment by josepharhar** [comment]
> Why is this a tag, and not a property on the `<selectlist>` tag? It could simply be the `value` property, matching the pattern of other form elements.

I'm not sure I understand what the API shape would look like.
Here is an example of how selectedoption would be used:
```html
<selectlist>
  <button type=selectlist>
    <span>selected option:</span>
    <selectedoption></selectedoption>
  </button>
  <listbox>
    <option>one</option>
    <option>two</option>
  </listbox>
</selectlist>
```
How would you rewrite this without the selectedoption tag?

**Comment by jp-larose** [comment]
> > Why is this a tag, and not a property on the `<selectlist>` tag? It could simply be the `value` property, matching the pattern of other form elements.
> 
> I'm not sure I understand what the API shape would look like. Here is an example of how selectedoption would be used:

[snip]

> How would you rewrite this without the selectedoption tag?

I guess my initial thought was that the form would simply submit text, in which case this would be sufficient:
```
<selectlist value="one">
  <button type=selectlist>
    <span>selected option:</span>
  </button>
  <listbox>
    <option>one</option>
    <option>two</option>
  </listbox>
</selectlist>
```

Overall, I'm finding this whole structure overly verbose, but I'm beginning to see how it can be useful for styling.  

The problem I'm having with a whole element/tag for the selected option, at least the way I'm seeing it here, is that it goes against the DRY principle.  This has consequences in regards to redundancy (duplication of data, duplication of effort for programming at all levels), data consistency/integrity (the selected option, if not null, should match exactly the item in the list it's aiming to represent, but an author could mess this up).

Perhaps a better alternative is to use a reference instead of duplicating the data.
```
<selectlist>
  <button type=selectlist>
    <span>selected option:</span>
    <selectedoption ref="op1"/>
  </button>
  <listbox>
    <option key="op1"><i>one</i></option>
    <option key="op2"><b>two</b></option>
  </listbox>
</selectlist>
```
The browser could then fill in the whole content of the option for 'op1' in the UI, and send that same data to the server when submitting.  When the user changes the selection to 'op2', the browser then simply updates the `ref` value.

I'm not really attached to the `ref` and `key` names for the properties, it's just what popped into mind.  The point is to have a way to identify different options without having to textually replicate the whole content.  I don't recommend relying on `id` because that's required to be unique thought out the whole document, whereas `key` would just need to be unique within the `selectlist` context.

**Comment by jp-larose** [comment]
> Yeah I suppose that `<selectedoptions>` would make more sense than `<selectedoption>` for multi-select. I'm not actively working on multi-select yet and plan to do that after we get single-select done. The "select-v2" label for issues in this repo contain multi-select issues.
> 
> If you have any ideas for a term that would unambiguously be for singular or multiple options, I'm all ears.

What about `<selected>` or `<chosen>`?  Something that avoids the whole singular vs plural...
