### ISSUE TITLE
Should we worry about existing button behavior?

### ISSUE THREAD

**Issue by bkardell** [openui/open-ui#809]
Opening this out of an abundance of caution, but I noticed only in the past few days that 3 weeks ago as part of #702 it was suggested that we use a `<button type="_something_">` and I just want to make sure that we're ok with that specific detail. 

I think the idea here would allow an author to supplant this and if we do use that approach, it seems to me that in any unsupported browser it would result in someone clicking a button to, say, expand the list, and instead it submits the form.

Maybe everyone is ok with that on purpose somehow, but I'd really like to just make sure it didn't get overlooked (I overlooked it) because there is _a lot_ happening in that issue.  It seems that this detail [originated](https://github.com/openui/open-ui/issues/702#issuecomment-1654256533) as one of many detail during the call by [josepharhar](https://github.com/josepharhar)  who then did a lot of real work to [come up with an actual proposal for _all of the things being discussed there_](https://github.com/openui/open-ui/issues/702#issuecomment-1662708138).

Everyone had positive responses, including @domenic (who opened the issue with concerns from the HTML POV), so that's good - but re-reading it I'm not entirely confident that wasn't mostly about the nice shift in all of the other moving parts (which I also like).

**Comment by mfreed7** [comment]
Perhaps an alternative is to use a new attribute instead, and require `type=button` to avoid form submissions on non-supported browsers?

```html
<selectlist>
  <button type="button" selectlistbutton>Pick a value</button>
</selectlist>
```

That new attribute would also have to be added to the `HTMLInputElement`:

```html
<selectlist>
  <input type="button" value="Pick a value" selectlistbutton>
</selectlist>
```

But that'd do the trick, right? The name needs bikeshedding, of course. Perhaps `activationbutton` or something semi-generic?

The other approach, which I'd **really** like to avoid, is inventing a new element for this button:

```html
<selectlist>
  <selectlistbutton> Pick a value </selectlistbutton>
</selectlist>
```

That's terrible by itself, because now you have yet another platform thing that is a button, but also, each new form control that we tackle will likely need its own set of new buttons. Think `<datepickertodaybutton>` and `<fileinputpickafilebutton>`, etc.

**Comment by domenic** [comment]
I agree with Joey's position. If you're running any sort of script, e.g. a polyfill, it's easy to set up a `preventDefault()` handler in that script to prevent incorrect behavior in downlevel browsers.

**Comment by lukewarlow** [comment]
Could unknown elements that aren't valid custom element (single word name) be changed to disable default behaviour of buttons submitting forms? Probably not web compatible but just an idea.

**Comment by josepharhar** [comment]
I created another issue which poses similar questions to this one: https://github.com/openui/open-ui/issues/821
