### ISSUE TITLE
Bikeshed a name for "light dismiss for dialog"

### ISSUE THREAD

**Issue by mfreed7** [openui/open-ui#834]
See https://github.com/whatwg/html/issues/9373 for more context about this issue.  Also see [the notes from the 2023 TPAC meeting](https://docs.google.com/document/d/1V6_s_VsaWcI9J-ZATbIKKijn59JbVmRMsHXYyH29sho/edit#heading=h.9gswhzv85q2).

There's a desire to add an attribute on `<dialog>` that adds "light dismiss" behavior to the dialog. The proposal is to add that via an attribute:

```html
<dialog lightdismiss> I'm a light dismiss dialog </dialog>
```

Adding `lightdismiss` to the `<dialog>` makes the dialog get closed (as if `dialog.close()` were called) when the user ["light dismisses"](https://developer.mozilla.org/en-US/docs/Web/API/Popover_API/Using#auto_state_and_light_dismiss) it, e.g. by clicking outside the bounds of the dialog.

At TPAC, there was fairly good support for adding this behavior, and for adding it via a new attribute on `<dialog>`. But there was concern about the name of the attribute. There was a strong desire to have a name that links closely to `close()`. There were also comments that "light dismiss" is not well defined, and maybe Popover documentation should be updated to link to a new name that is shared with the proposed `<dialog>` feature.

So this issue is to bikeshed the proper name for "light dismiss", particularly as it relates to the attribute discussed above. Some preliminary ideas I heard in the meeting:

- `lightdismiss`
- `closebehavior=something`
- `lightclose`
- `softdismiss`
- `softclose`
- `maximaldismiss` / `minimaldismiss`
- {your idea here}

**Comment by hidde** [comment]
Fwiw, in my talks and articles about popover I've been explaining _light dismiss_  (dismissed by some heuristic) as the opposite of _explicit dismiss_ (closed by user (eg a button click) or author (some script)). Maybe it's just because I've grown into it, but I wouldn't mind keeping “lightdismiss”.

As for the others: 

* I kind of like close and how that matches close in the method name, but if we're picking a different name, I prefer “soft” to “light” 
* I think maximal/minimal dismiss is a bit far fetched… and the dismissing itself isn't more or less, isn't the difference more about who/what does the closing?
* I feel closebehavior is a bit long. I also wonder if that wrongly suggests one closing behaviour will apply (I think multiple could exist, eg a light dismissable popover could additionally be closable with a button and/or via script?)

As an additional suggestion… maybe “auto” (instead of light) vs “manual” (instead of explicit) could work?

**Comment by lukewarlow** [comment]
I vote for "lightdismiss" it's the term people use to describe this behaviour (in my experience at least). It's what's already used to describe the behaviour for popover. It's also a term used in other platforms not just the web.

Example of usage: [web.dev: adding light dismiss](https://web.dev/building-a-dialog-component/#adding-light-dismiss) , [mdn: popover light dismiss](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/popover#:~:text=state%20can%20be%20%22-,light%20dismissed,-%22%20by%20selecting%20outside),
and even a [PR to Microsoft UI XML](https://github.com/microsoft/microsoft-ui-xaml/issues/2122) for a similar request with the same terminology.

**Comment by brechtDR** [comment]
> I vote for `lightdismiss` it's the term people use to describe this behaviour (in my experience at least). It's what's already used to describe the behaviour for popover. It's also a term used in other platforms not just the web.

I agree with this :)

**Comment by keithamus** [comment]
@domenic's request, I believe, was to _not_ use `dismiss` and instead use `close` as it aligns with the CloseWatcher work - but hopefully Domenic can correct me if that was wrong.

**Comment by domenic** [comment]
Yeah, I think it's pretty important that if we ever expose this term in the API, it matches the existing API name the web platform uses for closing things, which is "close". I'm not sure who decided to create the "dismiss" synonym, but let's not expose two names for the same thing in the API, even if the damage has already been done in some of the documentation.

To be clear on the landscape as it stands:

- `close`: used by `<dialog>` for `close()` and the `close` event. (Also used by `window.close()`, which sort of counts.)
- "close request" and `CloseWatcher`: introduced in https://github.com/whatwg/html/pull/9462 (which is not yet merged). A "close request" is a user-initiated platform-specific request to initiate the close process, like the <kbd>Esc</kbd> key or Android back gesture. A `CloseWatcher` watches for close requests and fires `cancel` + `close` events; it also has `requestClose()` and `close()` methods.

The API invented here should sit alongside these existing and upcoming APIs, so it really should use the word "close". How you want to qualify it, I have no current feelings about.

**Comment by lukewarlow** [comment]
There's currently 19 instances of the term dismiss (in various forms) within the HTML spec (excluding an example block quote) while obviously some will be light-dismiss from popover not all of them will be. So the term clearly pre-dates popover (some date back to 2013) and also I really do feel strongly that this is the terminology that people understand hence why it was used for popover in the first place. I'd also like to add this is a declarative behaviour being defined not an imperative instruction so the language being different isn't completely weird. We already have an `open` attribute for dialog which corresponds effectively to a `show` method? 

Also imo (the ship has sailed on this) but `close()` as a method name for dialog should be `hide()` because you `show()` it not `open()` it. Window is `close()` because it's `open()` AND also (iirc) gets destroyed by the action. Again this is something I consider popover to have gotten correct.

Having said all that if we can't use the dismiss terminology. could `clickoutside="close"` or `clickoutsideclose` be considered. I know it's bad that it uses click but what does this lightdismiss introduce other than the click outside?. Esc etc are already considered (heavy?/strong) close signals.

`backdropaction="close"` or `backdropclose`?

Or out of the options listed above I guess `lightclose` cause it's as close to `lightdismiss` without the dismiss contention.

**Comment by hidde** [comment]
I've thought of ‘light dismiss’ as ‘it goes away due to _some_ heuristic’. To me telling an element to _light dismiss_ (it goes away when deemed appropriate) is something quite different from telling it to dismiss or close (it goes away right now).

This ‘some heuristic’ is up to the browser / tool implementing it. It could be following a user's click outside, but in my mind it could also be other things, like tab outside or scroll outside (and in future environments maybe something even more different; eg 'user starts walking to a different direction in VR environment'). So, I'd say, yes it closes, but it closes specifically when certain circumstances are met. 

_Light close_ seems unusual, _light dismiss_ much more common.

**Comment by lukewarlow** [comment]
Okay the VR point is a very good one and knocks out all my suggestions other than we should just go with lightdismiss. I agree lightclose feels very very weird.

**Comment by lukewarlow** [comment]
Looking through various older open ui issues regarding light dismiss there's also talk of lightdismiss on window resize and scroll etc which all feel like reasonable discussions and extra wipe out my suggestions

**Comment by muan** [comment]
Not sure where that issue is but just want to [highlight this part about multiple values, ESL, and interpretation of heavy/light](https://github.com/whatwg/meta/issues/284#:~:text=Anne%3A%20reusing%20words,interpret%20them%20differently.) from TPAC specifically, and seconding preserving the potential for more than two multiple values.

**Comment by josepharhar** [comment]
@muan So you're saying that it would be better to do `close=light` rather than `lightclose`?

**Comment by muan** [comment]
@hidde and I had a chat about this and managed to convince him. I know everyone has already put a lot of thoughts into this, just bikeshedding here. I'd like to propose something like this:

```html
closebehavior="explicit" <!-- dialog default, or what UA decides what’s explicit -->
closebehavior="implicit" <!-- popover default, or what UA decides what’s implicit -->
closebehavior="backdrop focusout attentionlost vrwhatever"
<!-- optional now, enum for potential future use cases, 
     or some current use cases I can't think of,
     subjected to bikeshedding  -->
```

I think preserving the optional for enum (space separated) is more *future proof*. It's not about knowing what people want in the future but more about not limiting the options. I think the last thing we want is having authors saying "because this doesn't work consistently across UA" or "because I don’t like how `implicit` includes X", "here’s a snippet to roll your own `<dialog>/popover`".

My qualms with the above suggestions are:

- `light/soft/heavy`: I think they are up for interpretation, for their implicitness. I think of light like a light bulb or as a feather, and soft like a pillow, and not anything specific to do with behaviors/triggers. Even though `implicit/explicit` are indeed harder to spell, once you look it up it is clear. 
- `autoclose/autodismiss`: It reminds me of `autofocus` but the behavior is still **activated** by some sort of unknown user actions decided by the UA, very much unlike *auto*focus. 
- `dismiss`: Basically I agree with Domenic's comment.

💁🏻‍♀️

**Comment by keithamus** [comment]
If we're going that route, what about `closeaction=`?

**Comment by muan** [comment]
Sorry. Yes. I did read your comment above. I just added `close` and `closetrigger` to the comment as well. 

`closeaction` reminds me of `form[action]` and `[popovertargetaction]` which are for specifying what an element does instead of what will inform an element to [...].

**Comment by mayank99** [comment]
i feel that none of these options so far are intuitive unless you're already familiar with the term.

something like `closeonbackdropclick` or `closeonoutsideclick` feels more natural and reads like natural language.

**Comment by hidde** [comment]
@mayank99 thanks. Sorry, to me, a name using 'click' would notse seem suitable: lightdismiss can oftentimes be _not_ on click, but on scroll, window blur, “looking away in VR” (a made up use case, but maybe a real one?). 

And to be honest, I would have similar concerns adding 'backdrop' or 'outside', because the component could have no backdrop (well, no visible backdrop, top layer els always have a bakdrop).

**Comment by mayank99** [comment]
> thanks. To be honest, a name using 'click' would not seem suitable to me, for reasons mentioned in the discussions above: light dismiss can oftentimes be not on click, but on scroll, window blur, “looking away in VR” (a made up use case, but maybe a real one?).

i think this is even more reason to separate out these events. it may be desirable to close the dialog on backdrop click, but leave it open on scroll or window blur. i like **\@muan**'s `closebehavior` idea even more now.

> I would have similar concerns adding 'backdrop' or 'outside', because the component could have no backdrop (well, no visible backdrop, top layer els always have a bakdrop).

that's the thing though: `::backdrop` exists, it can be seen in dev tools, developers encounter this element directly, and can style it etc. whereas the concept of "light dismiss" is something developers would need to read up on (i hadn't heard this term until a few months ago, and i've been building dialogs for many years). if this concept is surfaced early on in documentation though, this unfamiliarity might not be big concern.

**Comment by hidde** [comment]
> i think this is even more reason to separate out these events. it may be desirable to close the dialog on backdrop click, but leave it open on scroll or window blur. i like @muan's closebehavior idea even more now.

I'm all for separating the events so that people have the option, but I do worry it makes it very easy for developers to forget use cases (I know I would… so would probably use`implicit` myself most of the time, so that the UA can decide what's most appropriate given the circumstancs they know more about).

> whereas the concept of "light dismiss" is something developers would need to read up on (i hadn't heard this term until a few months ago, and i've been building dialogs for many years)

Fwiw, popover is the first (?) time the web platform gets a way for an element to have “light dismiss”, it shipped some months ago, so you're right, it is fairly new. 

Bit of a tangient, but I think important for naming… for dialogs with visible backdrops, in many cases (not all) it would probably make more sense as a modal dialog, not a popover (because if visually obscuring rest of page, why not also make the rest of the page inert?).

**Comment by mayank99** [comment]
> I'm all for separating the events so that people have the option, but I do worry it makes it very easy for developers to forget use cases (I know I would… so would probably use`implicit` myself most of the time, so that the UA can decide what's most appropriate given the circumstancs they know more about).

This is a good point indeed. But the `implicit` behavior would need to make sense for most cases. And what makes sense may change based on what kind of popover it is. For a modal dialog, I can't think of why it should close on scroll; it could be very frustrating UX (depending on overscroll chaining behavior of the scrollbars inside the dialog). Instead of closing on scroll, I would want to prevent the document from scrolling altogether.

There may also be other events that would be useful to have shortcuts for but may not make sense as a default. On mobile devices for example, I would like the dialog to be closed when going "back" (similar to how it works in native mobile apps) instead of performing a page navigation. But this behavior might not be desirable by everyone, so it could be *opt-in*.

**Comment by keithamus** [comment]
It's worth pointing out to those who are getting involved now, that there is only one real concrete use case for this. Currently dialogs will close given a device gesture - which most typically is pressing Esc on a keyboard (but can also be triggered by other device specific gestures). Currently interacting with the backdrop _does not close_ a dialog. This proposal seeks to add an opt-in for users interacting with the backdrop (typically via mouse click) to _also_ close the dialog.

Any talk of looking away or interacting with another window or focusing out of the dialog are conjecture, and will need to be specified separately and all come with their own concerns such as privacy, usability, security. I'm not trying to shut down conversation around ensuring the opt-in is future-proof but I'd also think there's a high chance that _no other styles of interaction will be added_ and this will be the only opt-in enhancement. We should consider the trade-off around heavy discussions around such conjecture and try to remain productive toward solving the concrete problem we have today.

To reiterate; in this issue we're asking what is an ergonomic way to mark an element to say "when the backdrop is interacted with, this element should close".

**Comment by mayank99** [comment]
If this is only about backdrop, why not spell it out explicitly? i.e. `closetrigger="backdropclick"`.

The whole point of `implicit` was to introduce ambiguity in order to support additional triggers determined by the browser.

**Comment by mayank99** [comment]
@keithamus Those points were made before your added clarification that this issue is only about backdrop. In other words, light dismiss will in fact never not be a backdrop click (for the purposes of this issue).

As for "click", I understand it to be a generic term not necessarily tied to mouse, but it's the less important part of `backdropclick`. `closetrigger="backdrop"` would work just as well.

`implicit` makes sense when there are additional triggers. But if it initially ships only handling backdrop behavior, then it would be very risky to change the behavior 2 years later. Developers would use this attribute expecting it to only close on backdrop click, and then suddenly it might start closing on focusout/scroll/windowblur? That's a breaking change that reduces trust in the platform.

For this reason, `closetrigger="backdrop"` is the safer option.

**Comment by lukewarlow** [comment]
> For this reason, closetrigger="backdrop" is the safer option.

I'm concerned developers might think this would disable Esc and Android back?

**Comment by mayank99** [comment]
@lukewarlow That's a good point about <kbd>Esc</kbd>, although I haven't seen the dialog close on Back button on Android (i [tried](https://g56qrm.csb.app/) it just now to confirm that it performs page navigation).

To avoid confusion, i can see two ways:
1. bring back `backdrop` or `clickoutside` in the attribute name. examples:
	```
	closeonbackdrop=""
	```
	```
	backdropclose="auto"
	```
	```
	onclickoutside="close"
	```
2. use something like `closetrigger="backdrop escapekey"` for now.
   - In the future (potentially), this could be extended to `closetrigger="backdrop escapekey back focusout ..."` and once there is enough certainty about having covered the most common cases, `closetrigger="implicit"` could be added as a convenience api. Importantly, adding this in the future avoids breaking changes, whereas adding it now and introducing additional triggers in the future would be disruptive.

**Comment by lukewarlow** [comment]
I would avoid escape key because the new html closewatchers concept has a close signal which is deliberately abstract to include ESC and back button. I should have been more specific the Android back button will be supported soon but isn't currently.

**Comment by lukewarlow** [comment]
Removing agenda+ as it's not recent. Re add if that's a mistake and you do want to discuss this

**Comment by mfreed7** [comment]
I'd like to discuss this and get it moving. I feel like this issue has had quite some time to explore the area, and I'd like to finish bikeshedding a name.

A few comments, with my opinions:
 1. We've already defined the [algorithm](https://html.spec.whatwg.org/multipage/popover.html#popover-light-dismiss:light-dismiss-open-popovers) for this, which is already used by Popover. We're now just trying to find a name for the attribute that would enable it for `<dialog>`. I'd really like to avoid redesigning the feature, particularly the part that would affect Popover.
 2. I'd be fairly against providing direct access to different "ways" to dismiss a dialog (or popover) based on different user actions, such as ESC, click, scroll. The behavior we arrived on for popover took **significant** time and energy to ensure it worked well for most users. That was not trivial. It is unreasonable to assume all developers will spend as much time thinking about getting the particular set of actions just right. A better assumption is that developers will choose the value that sounds right to them and works for their particular way of interacting with the web, and that might not be the best for all users. That's not a knock on developers - it's just how time gets spent.
 3. Given the two above, let's just pick a name for a boolean attribute or equivalent.
 
I'd like to create a poll so we can vote. The names I've heard (and removing some that didn't seem popular):

- `lightdismiss`
- `closebehavior=light/explicit/implicit`
- `closetrigger=light/explicit/implicit`
- `close=light/explicit/implicit`
- `lightclose`
- `softdismiss`
- `softclose`
- `explicitdismiss`
- `explicitclose`
- `autodismiss`
- `autoclose`

Any others that I missed? Else I'll put together a poll and we can vote.

**Comment by domenic** [comment]
I agree with your 1-3. However, I hope we can remove all names that don't include `close` before starting any poll, per prior feedback from myself and others on this thread and at TPAC.

**Comment by mfreed7** [comment]
> I agree with your 1-3. However, I hope we can remove all names that don't include `close` before starting any poll, per prior feedback from myself and others on this thread and at TPAC.

My rough reading of the comments in this thread is that the names that include "close" are confusing to developers. Wouldn't it be interesting poll feedback if that's confirmed? Surely we don't want to choose a name that most people find confusing, do we? The entire point (I think?) of keeping things "consistent with the platform" is that they make it *easier* for developers. When that's not achieved, I'd hope we'd want to adjust.

**Comment by domenic** [comment]
I'm not comfortable introducing that sort of inconsistency, even if some of the people arguing above are promoting it.

**Comment by mfreed7** [comment]
> I'm not comfortable introducing that sort of inconsistency, even if some of the people arguing above are promoting it.

Presumably though, the strive for consistency is in the name of ease of understanding by developers. Would you agree with that? Or if not, why is self-consistency a top goal for the platform?

**Comment by domenic** [comment]
Consistency has many goals. It provides a foundation for the platform going forward, to give us a good path that other features can build on. It makes things easier to document and explain. It makes things easier to build. You can learn more in https://www.w3.org/TR/design-principles/#consistency .

**Comment by mfreed7** [comment]
Ok, I added a Github Poll for the naming of this attribute:

[ https://github.com/openui/open-ui/discussions/950 ](https://github.com/openui/open-ui/discussions/950)

I included only attributes that include "close", per the requirement from WHATWG. Please take a look and add your vote! Also please feel free to signal boost the above poll via social media.

**Comment by mfreed7** [comment]
Based on lots of discussion, I've closed the poll above, and started two more:

- https://github.com/openui/open-ui/discussions/960
- https://github.com/openui/open-ui/discussions/961

**Comment by keithamus** [comment]
This was useful data and the result seems to be a consensus on the attribute name of `closedby`, and the values being `any`, `closerequest`, `none`. See https://github.com/whatwg/html/pull/10157 & https://github.com/whatwg/html/issues/9373
