### ISSUE TITLE
Selectlist future compatibility questions

### ISSUE THREAD

**Issue by lukewarlow** [openui/open-ui#836]
Without wishing to re-raise a bunch of discussion that's already occurred I just wanted to double check some things.

In https://github.com/openui/open-ui/issues/531#issuecomment-1145170806 it was resolved that `<listbox>` as a standalone element and multiselect behaviour would be deferred. However, in https://github.com/openui/open-ui/issues/702 it was resolved to create a new `<listbox>` element for use inside of `<selectlist>`. I just want to ensure that by making this element but only usable in `<selectlist>` we're not making a compatability issue should we ever want the element to work standalone?

Also currently selectlist has `selectedOption` which wouldn't make sense for multi selects, and it doesn't seem to be clear from the deferment if it's been decided to move multi behaviour into its own new element or if it will be added to `<selectlist>` I again just want to double check the API isn't gonna be such that multi behaviour feels clunky when added (if it's its own element then this point is obviously void)

**Comment by lukewarlow** [comment]
If both of these have been addressed previously feel free to go ahead and close this out :)

**Comment by josepharhar** [comment]
The plan is to make `<listbox>` work as a standalone element, and hopefully it will ship with or before `<selectlist>`.

Yeah we will have to figure out a different IDL for multi-select, obviously having one `selectedOption` won't cut it.

I also wonder if multi-select should be a different element completely or not. `<selectlistmultiple>` vs `<selectlist multiple>`. I think that making a completely different element will solve issues of how the IDL is shared, since they won't have to share IDL. It will also make it easier to implement since we won't have to define what happens when you switch modes, which is a thing that makes `<input>` complicated.

**Comment by lukewarlow** [comment]
Closing in favour of #896
