### ISSUE TITLE
Is someone willing to pull together research on tooltip nestability?

### ISSUE THREAD

**Issue by mfreed7** [openui/open-ui#854]
The [OpenUI research page for tooltips](https://open-ui.org/components/tooltip.research/) does not include information on whether tooltips are allowed to be nested. On the WHATWG html issue for `popover=hint`, there's an [open question](https://github.com/whatwg/html/issues/9776#issuecomment-1741574741) about whether tooltips are most commonly allowed to be nested, or whether they're restricted to be one tooltip at a time.

Does anyone have the time to take a look into the design systems listed on the research page (or bring in more systems) and see if they allow nesting?

Additionally, do any a11y folks have input on whether nested tooltips are "ok"? I have been assuming not, but I realize (from the WHATWG conversation) that that's just an assumption that I can't justify with any data. @scottaohara @aleventhal

**Comment by brechtDR** [comment]
I'll try to kickstart this

**Comment by scottaohara** [comment]
another quick note in how the nesting of tooltips can lead to issues.

a standard tooltip is generally expected to provide an accessible description for the content that invokes it.  

so `<button title=blerp>edit</button>` is commonly exposed as "edit, button. blerb".

Let's modify that to create a custom tooltip that produces the same output

```
<button aria-describedby=t>edit</button> 
<div role=tooltip id=t>blerb</div>
```

if we add nested tooltips to this
```
<button aria-describedby=t>edit</button> 
<div role=tooltip id=t>
  blerb
  <button aria-describedby=t2>term</button>
  <div role=tooltip id=t2>
     content here
     <button aria-describedby=t3>nest again</button>
     <div role=tooltip id=t3>more stuff here</div>
  </div>
</div>
```

the above results in the initial "edit" button being exposed as such:
>edit, button. blerb term content here nest again more stuff here

Well that sucks.

But, can't we update the browser to not expose the tooltips which haven't been rendered yet?

Sure - but then when they are rendered that would fire a description change event for each nested instance.  So the initial button's description would change because of the new content added into the tooltip, causing a re-announcement of that initial content and everything nested within (see previous quote) - and then any further nested tooltip would be re-announced.

_but wouldn't this be covered by converting these to rich tooltips_?

yes, if the association from the invoking element to the popover revised from a description to a details a11y relationship - then the previous problems go away.  but new issues get introduced:
1. if an invoking element has a separate non-hint popover, and that popover is not a sibling element in the DOM - then there will already be a details relationship setup with that element.  Which then means that if someone has both the "rich tooltip" and the other popover open, it'll require someone to cycle through the associated details elements to reach the popover they actually want to interact with.  This becoming rather bothersome if the user just wants to get to the 'auto' popover - but because they've focused the element, the rich tooltip shows up and now they have to figure out if they went to the content they wanted to, or the _other_ content they didn't.   This is all just what needs to be considered before even getting into the nested content)
2. If we have tooltips that then contain their own nested tooltips (which can then be rich tooltips as well), this begs the question if these are really even 'tooltips' anymore, or if they're just stacking non-modal dialogs atop each other.  A 'rich tooltip' may be fine as a one off if there is an important reason to have a button that has its own primary function, and the rich tooltip provides hint content also has a learn more link, or something.  but if a tooltip contains buttons whose sole purpose is to invoke other tooltips, then those aren't hints anymore - those are the primary purpose of the button and then would make more sense as popover=autos.



(sorry,  stopping abruptly here as i could go on for some time about this / dont' actually expect people to read all that/more than that... maybe better to acknowledge any additional questions that arise from just the above)

**Comment by scottaohara** [comment]
that is a great example @keithamus and i've been talking with @smhigley a lot about this since yesterday, and she's convincing me that maybe the issue here is trying to add in any extra a11y considerations beyond what was already done for popover=auto/manual... as it's those extra considerations that can be what could create some of the problems i noted in my previous comment.

hmm... i'm having a bunch of conflicting thoughts on this now.

**Comment by lukewarlow** [comment]
> Here is an example of nested floating UI, which would one day like to use `popover=hint` for both cases:

What's the reasoning that the first one is a hint and not auto? (Sorry if it's obvious)

**Comment by keithamus** [comment]
> What's the reasoning that the first one (profile card) is a hint and not auto? (Sorry if it's obvious)

The card is supplementary info; it is not the main purpose of the link (the link takes you to a profile page). If we turned the feature off it wouldn't impact core functionality of the site. Also concretely we want the behaviour of `hint` in that only one hovercard should be present at a time, and it shouldn't disrupt existing `auto` popovers. Lastly we desire it to use the notion of "interest" because the main action is to go to the page. Based on the rubric I discussed in the meeting it strongly meets 2 of the three criteria (ephemeral, supplementary) and loosely meets the third (interactivity) - it has links inside of it but it doesn't have enough interactive content to exclude it from tooltip status.

**Comment by mfreed7** [comment]
So @brechtDR has nicely put together a starting table of behaviors, [in this PR](https://github.com/openui/open-ui/pull/860). It has some "to be investigated" rows that still need some work. Anyone up for giving that a go? The initial table should land soon, so you could put up a PR against it.

Also, given the [comments above](https://github.com/openui/open-ui/issues/854#issuecomment-1751731034) (thanks @keithamus), it seems like Github should be added as a design system in the table. With a link back to that comment, that has great context on the rationale.

**Comment by mfreed7** [comment]
> not against the change in direction, but definitely wondering what implications this can have on the a11y mappings/ux. definitely will want to take a peak at the updated proposal when it's ready / help how i can.

I am curious about this also, and will welcome your input! 😄
