### ISSUE TITLE
invokers: Behaviour when interesttarget and invoketarget point to the same element

### ISSUE THREAD

**Issue by lukewarlow** [openui/open-ui#872]
This isn't something I envisage happening often but as it's possible it's worth making clear. What's the behaviour for when you have both invoke and interest pointed at the same element.

```html
<button invoketarget="popover" interesttarget="popover">Double Target Button</button>
<div popover>Content</div>
```

Specifically what happens if you hover the button and then click it? Should it close the popover? 

Currently it's specced to call `togglePopover()` which would close it.

**Comment by lukewarlow** [comment]
I've come across menus before where both a click and a focus/hover would trigger the menu. I worry that people might do the above to try and do this and it not necessarily give the UX a user would expect?

This doesn't necessarily need a behaviour change it could probably just be a documentation thing or even just don't mention it and give people dodgy ideas 😅

**Comment by keithamus** [comment]
@lukewarlow does the current Chrome impl lose interest as the button is clicked?

**Comment by lukewarlow** [comment]
The current chrome impl has no concept of lose interest yet.

**Comment by mfreed7** [comment]
I don't think we should do anything special here. If you point both of them to the same element, and you hover and then click, you should get two events and two "toggles".

The one thing that would need to be specified is the ordering. I suppose that's automatically provided, since you can't (?) show interest and activate a control at the same time. But I just want to make sure there's not some corner case I'm not thinking of where they can come at the same time.
