### ISSUE TITLE
[selectlist] button pseudo element naming

### ISSUE THREAD

**Issue by lukewarlow** [openui/open-ui#886]
The current plan is to have a `::button` pseudo element to style the button type="selectlist". Could this name be confusing if you have multiple buttons in the markup? Would perhaps something more explicit like `::selectlist-button` or `::invoker-button` be better? Like we have `input[type="file"]::file-selector-button`?

![image](https://github.com/openui/open-ui/assets/32498324/1dc4f045-f9ae-404d-af07-29f503749d35)

**Comment by lukewarlow** [comment]
The counter to the `::file-selector-button` naming is the `::marker` element being generic. But generally speaking you can have multiple buttons a lot more often than markers. In fact some legacy file inputs did have multiple buttons and that was the reasoning behind this naming.

**Comment by brechtDR** [comment]
Yes and a bit no.. I think the difference with the file input is that the naming is different. 

It can be a `input::file-selector-button` selector.
now we need the "file-" prefix to make clear it's for file type inputs 

With selectlist on the other hand, you actually have the selectlist prefix already because your selector is an element and not a type.

`selectlist::button`

But... I'm not against the idea as it might be easier to read when using a class instead of element as selector eg:`.my-super-select::invoker-button`.

Just wanted to point this out. As for the name. I think invoker is more general, which might be the safe choice for the future. 

So, no strong opinions, but some thoughts

**Comment by josepharhar** [comment]
> But generally speaking you can have multiple buttons a lot more often than markers

Yeah I also realized that I wrote "targets the button slot", so now I feel uncertain what it should actually be targeting...

In this example, what should the target of `::button` be? `button-container` or `<button type=selectlist>`?

```html
<selectlist>
  <div id=button-container>
    <button type=button>do something</button>
    <button type=selectlist>open listbox</button>
  </div>
  <listbox>...</listbox>
</selectlist>
```

You could also do the above without a `<div id=button-container>`, which would be even more weird because the two buttons would be slotted into the button slot without a single "container" to actually target via `::button`. With that in mind, maybe `::button` should just target `<button type=selectlist>`...?

**Comment by lukewarlow** [comment]
My gut is it would target button type selectlist (technically could be multiple if you've done that). That's what I would think.

And that's what targets the slot means to me. Cause the slot is replaced with a default one.

**Comment by brechtDR** [comment]
> My gut is it would target button type selectlist

Same gut feeling here

**Comment by lukewarlow** [comment]
Is it worth adding this to the agenda?

**Comment by lukewarlow** [comment]
Closing this because select will require you to insert a button so no need for pseudo
